import { NextResponse } from "next/server";
import { getFirestore } from "@/lib/firebase/admin";
import { ApiError, caller, fail } from "@/lib/institution/server";
import { testDriveSlug, validTestDrive, type TestDrive, type TestDriveResult } from "@/lib/testDrive";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

/**
 * /api/test-drive - Career Test-Drive (lib/testDrive.ts).
 *
 * GET   ?career=Data Analyst - the drive for that career; generated by AI
 *       the first time (Claude if ANTHROPIC_API_KEY is set, else Groq with
 *       GROQ_API_KEY), checked strictly, stored in testDrives/{slug} and
 *       reused for every student after that
 * POST  { slug, ratings: number[], choices: number[] } - save the signed-in
 *       student's result on their profile (users/{uid}.testDrives.{slug})
 */
export async function GET(req: Request) {
  try {
    await caller(req);
    const career = (new URL(req.url).searchParams.get("career") || "").trim().slice(0, 80);
    if (career.length < 3) throw new ApiError(400, "Choose a career.");
    const slug = testDriveSlug(career);
    const db = await getFirestore();
    const ref = db.collection("testDrives").doc(slug);
    const cached = await ref.get();
    if (cached.exists) return NextResponse.json({ drive: cached.data() as TestDrive });
    const grounding = await roadmapGrounding(career, new URL(req.url).origin);
    const { json, model } = await generate(career, grounding);
    const drive: TestDrive = { ...json, slug, career, generatedAt: Date.now(), model };
    await ref.set(drive);
    return NextResponse.json({ drive });
  } catch (e) {
    return fail(e);
  }
}

export async function POST(req: Request) {
  try {
    const { uid } = await caller(req);
    const b = (await req.json().catch(() => ({}))) as { slug?: string; ratings?: unknown; choices?: unknown };
    const db = await getFirestore();
    const snap = await db.collection("testDrives").doc(String(b.slug || "")).get();
    if (!snap.exists) throw new ApiError(404, "Test-drive not found.");
    const drive = snap.data() as TestDrive;
    const ratings = (Array.isArray(b.ratings) ? b.ratings : []).map((r) => Math.min(5, Math.max(1, Math.round(Number(r) || 3)))).slice(0, drive.scenes.length);
    const choices = (Array.isArray(b.choices) ? b.choices : []).map((c) => Math.max(0, Math.round(Number(c) || 0))).slice(0, drive.scenes.length);
    if (ratings.length !== drive.scenes.length) throw new ApiError(400, "Finish every moment of the day first.");
    const best = choices.filter((c, i) => drive.scenes[i]?.choices[c]?.best).length;
    const result: TestDriveResult = {
      career: drive.career, ratings, choices,
      enjoyment: Math.round((ratings.reduce((s, r) => s + r, 0) / ratings.length) * 10) / 10,
      judgementPct: Math.round((best / drive.scenes.length) * 100),
      completedAt: Date.now(),
    };
    await db.collection("users").doc(uid).set({ testDrives: { [drive.slug]: result } }, { merge: true });
    return NextResponse.json({ result });
  } catch (e) {
    return fail(e);
  }
}

/** A short summary of OneGrasp's roadmap for the role, if one exists, so the day is built from real tasks. */
async function roadmapGrounding(career: string, origin: string): Promise<string> {
  try {
    const index = (await (await fetch(`${origin}/roadmaps/ug/index.json`)).json()) as { roles: Record<string, string[]> };
    const key = Object.keys(index.roles).find((r) => r.toLowerCase() === career.toLowerCase());
    if (!key) return "";
    const rm = (await (await fetch(`${origin}/roadmaps/ug/${index.roles[key][0]}.json`)).json()) as {
      summary?: string; sections?: { heading: string; kind: string; blocks: { type: string; text?: string; items?: { text: string }[] }[] }[];
    };
    const careers = rm.sections?.find((s) => s.kind === "careers");
    const lines = (careers?.blocks ?? []).flatMap((b) => (b.type === "list" ? (b.items ?? []).map((i) => i.text) : b.text ? [b.text] : [])).slice(0, 15);
    return [`Role summary: ${rm.summary ?? ""}`, lines.length ? `First jobs and related roles: ${lines.join("; ")}` : ""].filter(Boolean).join("\n").slice(0, 1500);
  } catch {
    return "";
  }
}

const PROMPT = (career: string, grounding: string) => `Write a realistic "day in the job" simulation for a student in India (age 13-21) who is considering the career: ${career}.

Return ONLY a JSON object, no other text, in exactly this shape:
{
  "intro": "2-3 sentences in second person setting the scene at a realistic Indian workplace on a normal working day, in an entry-level role (first 2 years)",
  "scenes": [
    {
      "time": "9:30 AM",
      "title": "3-6 word title",
      "situation": "3-4 sentences: a concrete, realistic task, problem or dilemma this job really involves",
      "choices": [
        { "text": "what you do (one sentence)", "outcome": "what honestly happens next (1-2 sentences)", "skill": "the skill this uses (2-4 words)", "best": true },
        { "text": "...", "outcome": "...", "skill": "...", "best": false },
        { "text": "...", "outcome": "...", "skill": "...", "best": false }
      ]
    }
  ],
  "reality": { "pros": ["3 short honest positives"], "cons": ["3 short honest downsides"], "facts": ["3 short facts: entry route in India, working hours or conditions, what the first year is like"] },
  "nextSteps": ["3 concrete things a student can do this month to explore this career"]
}

Rules: exactly 5 scenes from morning to evening, each with exactly 3 choices and exactly one "best": true; mix technical work, people, pressure and a small ethical or judgement call; simple English a 14-year-old understands; no real company or person names; no salary figures; no medical, legal or financial advice; keep every field short.${grounding ? `\n\nGround the day in this OneGrasp roadmap information for the role:\n${grounding}` : ""}`;

async function generate(career: string, grounding: string): Promise<{ json: Omit<TestDrive, "slug" | "career" | "generatedAt" | "model">; model: string }> {
  const prompt = PROMPT(career, grounding);
  let text = "", model = "";
  if (process.env.ANTHROPIC_API_KEY) {
    model = "claude-sonnet-5-5";
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "x-api-key": process.env.ANTHROPIC_API_KEY, "anthropic-version": "2023-06-01", "content-type": "application/json" },
      body: JSON.stringify({ model, max_tokens: 4000, messages: [{ role: "user", content: prompt }] }),
    });
    const data = (await res.json().catch(() => ({}))) as { content?: { type: string; text?: string }[]; error?: { message?: string } };
    if (!res.ok) throw new ApiError(502, `The AI service refused the request: ${data.error?.message ?? res.status}`);
    text = (data.content ?? []).filter((c) => c.type === "text").map((c) => c.text ?? "").join("");
  } else if (process.env.GROQ_API_KEY) {
    model = "llama-3.3-70b-versatile";
    const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${process.env.GROQ_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({ model, temperature: 0.6, max_tokens: 4000, response_format: { type: "json_object" }, messages: [{ role: "user", content: prompt }] }),
    });
    const data = (await res.json().catch(() => ({}))) as { choices?: { message?: { content?: string } }[]; error?: { message?: string } };
    if (!res.ok) throw new ApiError(502, `The AI service refused the request: ${data.error?.message ?? res.status}`);
    text = data.choices?.[0]?.message?.content ?? "";
  } else {
    throw new ApiError(503, "Career Test-Drive needs an AI key on the server: set ANTHROPIC_API_KEY (or GROQ_API_KEY).");
  }
  const start = text.indexOf("{"), end = text.lastIndexOf("}");
  let json: unknown = null;
  try { json = JSON.parse(text.slice(start, end + 1)); } catch { /* checked below */ }
  if (!validTestDrive(json)) throw new ApiError(502, "This test-drive couldn't be prepared right now - please try again in a minute.");
  return { json, model };
}
