import { Career, RiasecVector } from "./types";

// Curated career library — each career encoded as an ideal profile in the same
// canonical dimensions the user profile uses (blueprint §7). Sourced from
// O*NET-style RIASEC/aptitude/values patterns. This is a starter shortlist
// (~40 careers) spanning the families relevant to classes 6–12 and graduates;
// expand freely — the matcher only ranks careers you encode here.
//
// RIASEC values are 0-100 emphasis per Holland theme; aptitude values are
// approximate required levels (0-100); values/mi are qualitative tags.

const r = (
  R: number, I: number, A: number, S: number, E: number, C: number
): RiasecVector => ({ R, I, A, S, E, C });

export const CAREER_LIBRARY: Career[] = [
  // ---------- STEM ----------
  {
    id: "software_developer",
    title: "Software Developer",
    family: "STEM",
    cluster: "Information Technology",
    roles: ["Software Engineer", "Backend Developer", "App Developer"],
    riasec: r(25, 90, 40, 20, 30, 55),
    aptitude: { Numerical: 70, Abstract: 80, Verbal: 55, Spatial: 50 },
    bigFive: { O: 75, C: 75, E: 45, A: 50, N: 35 },
    values: ["intellectual", "achievement", "autonomy"],
    mi: ["logical-mathematical", "spatial"],
    eiMin: 40,
    entrySubjects: ["Mathematics", "Numeracy", "Logical"],
    blurb: "Designs, builds and maintains software systems and applications.",
  },
  {
    id: "data_scientist",
    title: "Data Scientist / Analyst",
    family: "STEM",
    cluster: "Information Technology",
    roles: ["Data Analyst", "ML Engineer", "Business Analyst"],
    riasec: r(20, 90, 35, 25, 40, 65),
    aptitude: { Numerical: 80, Abstract: 80, Verbal: 55 },
    bigFive: { O: 80, C: 70, E: 45, A: 45, N: 35 },
    values: ["intellectual", "achievement"],
    mi: ["logical-mathematical"],
    eiMin: 40,
    entrySubjects: ["Mathematics", "Statistical", "Data"],
    blurb: "Extracts insight from data using statistics, coding and modelling.",
  },
  {
    id: "mechanical_engineer",
    title: "Engineering (Mechanical / Core)",
    family: "STEM",
    cluster: "Science, Maths and Engineering",
    roles: ["Mechanical Engineer", "Design Engineer", "Production Engineer"],
    riasec: r(85, 75, 30, 20, 35, 45),
    aptitude: { Numerical: 70, Abstract: 70, Spatial: 75, Mechanical: 80 },
    bigFive: { O: 60, C: 75, E: 45, A: 45, N: 40 },
    values: ["achievement", "security"],
    mi: ["logical-mathematical", "spatial", "bodily-kinesthetic"],
    eiMin: 40,
    entrySubjects: ["Mathematics", "Engineering", "Science"],
    blurb: "Applies physics and materials science to design and build machines.",
  },
  {
    id: "doctor",
    title: "Medicine / Doctor",
    family: "Health",
    cluster: "Human Service",
    roles: ["Physician", "Surgeon", "Medical Specialist"],
    riasec: r(35, 85, 20, 70, 40, 40),
    aptitude: { Numerical: 65, Verbal: 70, Abstract: 65 },
    bigFive: { O: 60, C: 80, E: 50, A: 70, N: 30 },
    values: ["helping", "achievement", "recognition"],
    mi: ["logical-mathematical", "interpersonal", "naturalist"],
    eiMin: 65,
    entrySubjects: ["Science", "General Science", "Mathematics"],
    blurb: "Diagnoses and treats illness; high responsibility, people-facing.",
  },
  {
    id: "psychologist",
    title: "Counselling Psychology",
    family: "Health",
    cluster: "Human Service",
    roles: ["Career Counsellor", "Behavioural Counsellor", "Therapist"],
    riasec: r(15, 75, 45, 90, 40, 35),
    aptitude: { Verbal: 70, Abstract: 60 },
    bigFive: { O: 70, C: 60, E: 55, A: 80, N: 35 },
    values: ["helping", "intellectual", "affiliation"],
    mi: ["interpersonal", "intrapersonal", "linguistic"],
    eiMin: 80,
    entrySubjects: ["Reading", "Verbal", "General Science / Humanities"],
    blurb: "Helps people understand themselves and navigate life decisions.",
  },
  // ---------- Health / Human Service ----------
  {
    id: "mentor_coach",
    title: "Mentor and Coach",
    family: "Social",
    cluster: "Human Service",
    roles: ["Mentor", "Life Coach", "Guide"],
    riasec: r(20, 40, 45, 90, 65, 30),
    bigFive: { E: 70, A: 80, C: 55, O: 60, N: 35 },
    values: ["helping", "affiliation", "recognition"],
    mi: ["interpersonal", "linguistic"],
    eiMin: 80,
    blurb: "Guides individuals to grow personally and professionally.",
  },
  {
    id: "teacher",
    title: "Teaching / Education",
    family: "Social",
    cluster: "Education and Training",
    roles: ["Teacher", "Trainer", "Academic Coordinator"],
    riasec: r(25, 55, 45, 90, 45, 40),
    aptitude: { Verbal: 65 },
    bigFive: { E: 60, A: 75, C: 65, O: 60, N: 35 },
    values: ["helping", "affiliation", "security"],
    mi: ["linguistic", "interpersonal"],
    eiMin: 70,
    entrySubjects: ["Reading", "Verbal", "Comprehension"],
    blurb: "Educates and develops students across subjects and skills.",
  },
  {
    id: "home_science",
    title: "Home Science",
    family: "Social",
    cluster: "Human Service",
    roles: ["Healthcare Industry", "Teaching and Research", "Nutritionist"],
    riasec: r(40, 55, 45, 80, 40, 45),
    bigFive: { A: 75, C: 65, E: 50, O: 55, N: 40 },
    values: ["helping", "security", "creativity"],
    mi: ["interpersonal", "naturalist"],
    eiMin: 65,
    blurb: "Applies science to family, health, nutrition and community life.",
  },
  // ---------- Business ----------
  {
    id: "marketing_manager",
    title: "Marketing",
    family: "Business",
    cluster: "Marketing & Advertising",
    roles: ["Marketing Manager", "Product Marketing", "Brand Manager"],
    riasec: r(20, 40, 60, 55, 90, 45),
    aptitude: { Verbal: 65, Numerical: 55 },
    bigFive: { E: 80, O: 70, C: 60, A: 55, N: 35 },
    values: ["achievement", "recognition", "commerce"],
    mi: ["linguistic", "interpersonal"],
    eiMin: 65,
    blurb: "Plans and runs campaigns that promote products and grow demand.",
  },
  {
    id: "advertising",
    title: "Advertising & Communication",
    family: "Media",
    cluster: "Marketing & Advertising",
    roles: ["Advertising Manager", "Brand Manager", "Copywriter"],
    riasec: r(15, 40, 75, 50, 85, 40),
    aptitude: { Verbal: 65 },
    bigFive: { E: 75, O: 80, C: 55, A: 55, N: 35 },
    values: ["creativity", "recognition", "commerce"],
    mi: ["linguistic", "interpersonal"],
    eiMin: 60,
    blurb: "Crafts persuasive brand messages across media channels.",
  },
  {
    id: "sales",
    title: "Professional Sales",
    family: "Business",
    cluster: "Marketing & Advertising",
    roles: ["Sales Executive", "Sales Head", "Business Development Manager"],
    riasec: r(25, 25, 40, 60, 90, 45),
    bigFive: { E: 85, C: 55, A: 55, O: 55, N: 35 },
    values: ["achievement", "commerce", "recognition"],
    mi: ["interpersonal", "linguistic"],
    eiMin: 65,
    blurb: "Builds relationships and closes deals to drive revenue.",
  },
  {
    id: "apparel_management",
    title: "Apparel Merchandising & Management",
    family: "Business",
    cluster: "Business Management",
    roles: ["Fashion Management", "Fashion Brand Manager", "Merchandiser"],
    riasec: r(25, 30, 70, 45, 80, 55),
    bigFive: { E: 70, O: 70, C: 65, A: 50, N: 40 },
    values: ["creativity", "commerce", "recognition"],
    mi: ["spatial", "interpersonal"],
    eiMin: 55,
    blurb: "Manages product, brand and buying in the fashion business.",
  },
  {
    id: "entrepreneur",
    title: "Entrepreneurship / Startup",
    family: "Business",
    cluster: "Business Management",
    roles: ["Founder", "Business Owner", "Startup Operator"],
    riasec: r(30, 45, 55, 45, 95, 45),
    bigFive: { E: 80, O: 80, C: 60, A: 45, N: 35 },
    values: ["autonomy", "achievement", "commerce"],
    mi: ["interpersonal", "logical-mathematical"],
    eiMin: 60,
    blurb: "Builds and runs ventures, taking initiative and risk.",
  },
  {
    id: "accountant",
    title: "Accounting & Finance",
    family: "Business",
    cluster: "Accounts and Finance",
    roles: ["Accountant", "Financial Analyst", "Auditor"],
    riasec: r(20, 55, 20, 30, 45, 90),
    aptitude: { Numerical: 75, Clerical: 70 },
    bigFive: { C: 85, O: 45, E: 40, A: 50, N: 35 },
    values: ["security", "achievement", "commerce"],
    mi: ["logical-mathematical"],
    eiMin: 40,
    entrySubjects: ["Mathematics", "Numeracy", "Business & Finance"],
    blurb: "Manages money, records and compliance for organisations.",
  },
  {
    id: "corporate_trainer",
    title: "Corporate Trainer",
    family: "Social",
    cluster: "Education and Training",
    roles: ["Corporate Trainer", "Coach", "Motivator"],
    riasec: r(20, 40, 50, 85, 70, 40),
    bigFive: { E: 80, A: 70, O: 65, C: 60, N: 30 },
    values: ["helping", "recognition", "achievement"],
    mi: ["linguistic", "interpersonal"],
    eiMin: 75,
    blurb: "Builds workforce skills through training and facilitation.",
  },
  {
    id: "image_consultant",
    title: "Image Consultant",
    family: "Creative",
    cluster: "Education and Training",
    roles: ["Personality Trainer", "Soft Skills Trainer", "Fashion Stylist"],
    riasec: r(20, 30, 70, 75, 75, 40),
    bigFive: { E: 80, O: 70, A: 65, C: 55, N: 35 },
    values: ["creativity", "helping", "recognition"],
    mi: ["interpersonal", "spatial"],
    eiMin: 70,
    blurb: "Coaches people on presence, style and communication.",
  },
  // ---------- Hospitality ----------
  {
    id: "airhostess",
    title: "Airhostess / Cabin Crew",
    family: "Hospitality",
    cluster: "Hospitality and Tourism",
    roles: ["Airhostess", "Cabin Crew", "Flight Steward"],
    riasec: r(35, 20, 40, 80, 75, 45),
    bigFive: { E: 85, A: 75, C: 60, O: 55, N: 30 },
    values: ["affiliation", "variety", "recognition"],
    mi: ["interpersonal", "bodily-kinesthetic"],
    eiMin: 75,
    blurb: "Ensures passenger safety, comfort and service in the air.",
  },
  {
    id: "hotel_management",
    title: "Hotel Management",
    family: "Hospitality",
    cluster: "Hospitality and Tourism",
    roles: ["Restaurant Manager", "Hotel Manager", "Operations Head"],
    riasec: r(35, 25, 40, 70, 85, 55),
    bigFive: { E: 80, A: 65, C: 70, O: 55, N: 35 },
    values: ["achievement", "affiliation", "commerce"],
    mi: ["interpersonal"],
    eiMin: 70,
    blurb: "Runs hospitality operations and guest experience end to end.",
  },
  {
    id: "travel_tourism",
    title: "Travel & Tourism",
    family: "Hospitality",
    cluster: "Hospitality and Tourism",
    roles: ["Travel Consultant", "Tour Manager", "Destination Specialist"],
    riasec: r(40, 30, 50, 75, 75, 45),
    bigFive: { E: 80, A: 70, O: 65, C: 55, N: 35 },
    values: ["variety", "affiliation", "helping"],
    mi: ["interpersonal", "naturalist"],
    eiMin: 65,
    blurb: "Plans and delivers travel experiences and tours.",
  },
  {
    id: "event_management",
    title: "Event, Entertainment & Hospitality",
    family: "Hospitality",
    cluster: "Hospitality and Tourism",
    roles: ["Event Manager", "Hospitality Manager", "Show Producer"],
    riasec: r(30, 25, 60, 65, 90, 50),
    bigFive: { E: 85, O: 70, C: 65, A: 55, N: 35 },
    values: ["achievement", "recognition", "variety"],
    mi: ["interpersonal", "spatial"],
    eiMin: 70,
    blurb: "Conceives and runs events, shows and large gatherings.",
  },
  {
    id: "wedding_planner",
    title: "Wedding Planner",
    family: "Hospitality",
    cluster: "Hospitality and Tourism",
    roles: ["Wedding Event Manager", "Event Consultant", "Decor Planner"],
    riasec: r(25, 20, 70, 65, 85, 55),
    bigFive: { E: 80, O: 70, C: 70, A: 60, N: 35 },
    values: ["creativity", "recognition", "affiliation"],
    mi: ["interpersonal", "spatial"],
    eiMin: 70,
    blurb: "Designs and coordinates weddings from concept to delivery.",
  },
  // ---------- Creative / Arts ----------
  {
    id: "performing_arts",
    title: "Performing Arts",
    family: "Creative",
    cluster: "Arts & Language Arts",
    roles: ["Actor", "Singer", "Musician"],
    riasec: r(30, 25, 95, 55, 60, 25),
    bigFive: { O: 90, E: 75, A: 55, C: 45, N: 40 },
    values: ["creativity", "recognition", "aesthetics"],
    mi: ["musical", "bodily-kinesthetic", "linguistic"],
    eiMin: 60,
    blurb: "Expresses and entertains through stage and screen performance.",
  },
  {
    id: "fashion_design",
    title: "Fashion Designing",
    family: "Creative",
    cluster: "Arts & Language Arts",
    roles: ["Fashion Designer", "Stylist", "Costume Designer"],
    riasec: r(40, 30, 90, 40, 60, 40),
    aptitude: { Spatial: 65 },
    bigFive: { O: 90, C: 60, E: 60, A: 50, N: 40 },
    values: ["creativity", "aesthetics", "recognition"],
    mi: ["spatial", "bodily-kinesthetic"],
    eiMin: 50,
    blurb: "Designs clothing and looks blending art and craft.",
  },
  {
    id: "accessory_design",
    title: "Accessory Design",
    family: "Creative",
    cluster: "Arts & Language Arts",
    roles: ["Jewelry Designer", "Gemologist", "Accessory Maker"],
    riasec: r(55, 30, 90, 35, 55, 45),
    aptitude: { Spatial: 70 },
    bigFive: { O: 85, C: 65, E: 50, A: 50, N: 40 },
    values: ["creativity", "aesthetics"],
    mi: ["spatial", "bodily-kinesthetic"],
    eiMin: 45,
    blurb: "Designs jewellery and accessories with fine craftsmanship.",
  },
  {
    id: "cosmetology",
    title: "Cosmetology and Beautician",
    family: "Creative",
    cluster: "Arts & Language Arts",
    roles: ["Cosmetologist", "Stylist", "Beauty Expert"],
    riasec: r(55, 20, 80, 60, 60, 40),
    bigFive: { O: 75, E: 70, A: 65, C: 55, N: 40 },
    values: ["creativity", "aesthetics", "affiliation"],
    mi: ["spatial", "bodily-kinesthetic", "interpersonal"],
    eiMin: 60,
    blurb: "Enhances appearance through beauty and grooming craft.",
  },
  {
    id: "graphic_designer",
    title: "Graphic / UX Design",
    family: "Creative",
    cluster: "Media and Communication",
    roles: ["Graphic Designer", "UX Designer", "Visual Designer"],
    riasec: r(30, 45, 85, 35, 45, 45),
    aptitude: { Spatial: 65, Abstract: 55 },
    bigFive: { O: 85, C: 65, E: 45, A: 50, N: 40 },
    values: ["creativity", "aesthetics", "intellectual"],
    mi: ["spatial", "logical-mathematical"],
    eiMin: 45,
    blurb: "Designs visual and interactive experiences for products.",
  },
  // ---------- Media ----------
  {
    id: "mass_communication",
    title: "Mass Communication",
    family: "Media",
    cluster: "Media and Communication",
    roles: ["Journalist", "Radio Jockey", "Media Anchor"],
    riasec: r(20, 45, 80, 60, 70, 35),
    aptitude: { Verbal: 70 },
    bigFive: { E: 80, O: 80, A: 55, C: 55, N: 35 },
    values: ["creativity", "recognition", "affiliation"],
    mi: ["linguistic", "interpersonal"],
    eiMin: 60,
    blurb: "Reports, presents and produces content for mass audiences.",
  },
  {
    id: "public_relations",
    title: "Public Relations & Corporate Communication",
    family: "Media",
    cluster: "Media and Communication",
    roles: ["PR Specialist", "Corporate Communication", "Spokesperson"],
    riasec: r(15, 40, 65, 70, 85, 45),
    aptitude: { Verbal: 70 },
    bigFive: { E: 85, O: 70, A: 65, C: 60, N: 30 },
    values: ["affiliation", "recognition", "commerce"],
    mi: ["linguistic", "interpersonal"],
    eiMin: 75,
    blurb: "Shapes reputation and relationships for organisations.",
  },
  {
    id: "visual_merchandiser",
    title: "Visual Merchandiser",
    family: "Media",
    cluster: "Marketing & Advertising",
    roles: ["Fashion Communication", "In-Store Marketing", "Display Designer"],
    riasec: r(35, 30, 80, 45, 70, 50),
    bigFive: { O: 80, E: 65, C: 60, A: 50, N: 40 },
    values: ["creativity", "aesthetics", "commerce"],
    mi: ["spatial", "interpersonal"],
    eiMin: 50,
    blurb: "Designs retail spaces and displays that drive engagement.",
  },
  // ---------- Sports / Skilled ----------
  {
    id: "sports_person",
    title: "Sports Person",
    family: "Skilled-Trades",
    cluster: "Sports & Physical Activities",
    roles: ["Athlete", "Professional Sportsperson"],
    riasec: r(90, 20, 40, 55, 60, 25),
    aptitude: { Spatial: 55 },
    bigFive: { E: 70, C: 75, O: 50, A: 50, N: 30 },
    values: ["achievement", "recognition", "variety"],
    mi: ["bodily-kinesthetic"],
    eiMin: 55,
    blurb: "Competes and performs at a high level in a sport.",
  },
  {
    id: "physical_trainer",
    title: "Physical Trainer / Coach",
    family: "Skilled-Trades",
    cluster: "Sports & Physical Activities",
    roles: ["Physical Trainer", "Fitness Coach", "Sports Coach"],
    riasec: r(80, 30, 35, 70, 60, 30),
    bigFive: { E: 70, A: 65, C: 70, O: 50, N: 30 },
    values: ["helping", "achievement", "affiliation"],
    mi: ["bodily-kinesthetic", "interpersonal"],
    eiMin: 65,
    blurb: "Trains and motivates people toward fitness and performance.",
  },
  {
    id: "chef",
    title: "Culinary Arts / Chef",
    family: "Skilled-Trades",
    cluster: "Hospitality and Tourism",
    roles: ["Chef", "Culinary Artist", "Food Entrepreneur"],
    riasec: r(70, 25, 70, 45, 55, 40),
    bigFive: { O: 70, C: 70, E: 55, A: 50, N: 40 },
    values: ["creativity", "achievement", "aesthetics"],
    mi: ["bodily-kinesthetic", "spatial"],
    eiMin: 50,
    blurb: "Creates food experiences blending craft, taste and design.",
  },
  {
    id: "architect",
    title: "Architecture",
    family: "STEM",
    cluster: "Architecture and Construction",
    roles: ["Architect", "Urban Planner", "Interior Architect"],
    riasec: r(60, 65, 80, 35, 50, 45),
    aptitude: { Spatial: 80, Numerical: 60, Abstract: 60 },
    bigFive: { O: 85, C: 70, E: 50, A: 50, N: 40 },
    values: ["creativity", "achievement", "aesthetics"],
    mi: ["spatial", "logical-mathematical"],
    eiMin: 50,
    entrySubjects: ["Mathematics", "Spatial", "Engineering"],
    blurb: "Designs buildings and spaces balancing art and engineering.",
  },
  {
    id: "lawyer",
    title: "Law / Legal Services",
    family: "Social",
    cluster: "Legal Services",
    roles: ["Lawyer", "Legal Advisor", "Corporate Counsel"],
    riasec: r(15, 65, 45, 65, 80, 55),
    aptitude: { Verbal: 80, Abstract: 65 },
    bigFive: { C: 75, E: 65, O: 65, A: 45, N: 35 },
    values: ["achievement", "recognition", "power"],
    mi: ["linguistic", "logical-mathematical"],
    eiMin: 60,
    entrySubjects: ["Reading", "Verbal", "Critical Reading"],
    blurb: "Advises, advocates and resolves legal matters.",
  },
  {
    id: "civil_services",
    title: "Government / Civil Services",
    family: "Social",
    cluster: "Government Services",
    roles: ["Civil Servant", "Administrator", "Policy Officer"],
    riasec: r(30, 60, 40, 75, 70, 65),
    aptitude: { Verbal: 70, Numerical: 55, Abstract: 60 },
    bigFive: { C: 75, E: 60, A: 65, O: 60, N: 35 },
    values: ["helping", "power", "security"],
    mi: ["linguistic", "interpersonal"],
    eiMin: 65,
    entrySubjects: ["General Science / Humanities", "Reading", "Verbal"],
    blurb: "Serves the public through administration and policy.",
  },
];

export function getCareerLibrary(): Career[] {
  return CAREER_LIBRARY;
}
