/**
 * toolkitData — curated, real listings shown *inside* the dashboard toolkit.
 * Each row links to the official source. Kept current for 2026; institutes and
 * exam bodies use their permanent domains so links stay valid year to year.
 */

export type Listing = { name: string; meta: string; tag?: string; href: string };
export type ToolkitTab = { id: string; label: string; icon: string; blurb: string; items: Listing[] };

export const TOOLKIT_TABS: ToolkitTab[] = [
  {
    id: "colleges_in", label: "Colleges (India)", icon: "school",
    blurb: "Top NIRF-ranked institutes across engineering, medicine, management, law, design & the sciences. Tap to visit the official site.",
    items: [
      { name: "IIT Madras", meta: "Engineering · Chennai", tag: "NIRF #1", href: "https://www.iitm.ac.in/" },
      { name: "IIT Delhi", meta: "Engineering · New Delhi", href: "https://home.iitd.ac.in/" },
      { name: "IIT Bombay", meta: "Engineering · Mumbai", href: "https://www.iitb.ac.in/" },
      { name: "IIT Kanpur", meta: "Engineering · Kanpur", href: "https://www.iitk.ac.in/" },
      { name: "IIT Kharagpur", meta: "Engineering · Kharagpur", href: "https://www.iitkgp.ac.in/" },
      { name: "IIT Roorkee", meta: "Engineering · Roorkee", href: "https://www.iitr.ac.in/" },
      { name: "IIT Guwahati", meta: "Engineering · Guwahati", href: "https://www.iitg.ac.in/" },
      { name: "IIT (BHU) Varanasi", meta: "Engineering · Varanasi", href: "https://www.iitbhu.ac.in/" },
      { name: "IISc Bangalore", meta: "Science & Research · Bengaluru", tag: "Top University", href: "https://iisc.ac.in/" },
      { name: "NIT Tiruchirappalli", meta: "Engineering · Trichy", href: "https://www.nitt.edu/" },
      { name: "NIT Karnataka (Surathkal)", meta: "Engineering · Mangaluru", href: "https://www.nitk.ac.in/" },
      { name: "NIT Warangal", meta: "Engineering · Warangal", href: "https://www.nitw.ac.in/" },
      { name: "BITS Pilani", meta: "Engineering & Science · Pilani", href: "https://www.bits-pilani.ac.in/" },
      { name: "Anna University", meta: "Engineering · Chennai", href: "https://www.annauniv.edu/" },
      { name: "Jadavpur University", meta: "Engineering & Arts · Kolkata", href: "https://www.jadavpuruniversity.in/" },
      { name: "VIT Vellore", meta: "Engineering · Vellore", href: "https://vit.ac.in/" },
      { name: "AIIMS Delhi", meta: "Medical · New Delhi", tag: "Top Medical", href: "https://www.aiims.edu/" },
      { name: "PGIMER Chandigarh", meta: "Medical · Chandigarh", href: "https://www.pgimer.edu.in/" },
      { name: "CMC Vellore", meta: "Medical · Vellore", href: "https://www.cmch-vellore.edu/" },
      { name: "JIPMER Puducherry", meta: "Medical · Puducherry", href: "https://www.jipmer.edu.in/" },
      { name: "IIM Ahmedabad", meta: "Management · Ahmedabad", tag: "Top MBA", href: "https://www.iima.ac.in/" },
      { name: "IIM Bangalore", meta: "Management · Bengaluru", href: "https://www.iimb.ac.in/" },
      { name: "IIM Calcutta", meta: "Management · Kolkata", href: "https://www.iimcal.ac.in/" },
      { name: "IIM Lucknow", meta: "Management · Lucknow", href: "https://www.iiml.ac.in/" },
      { name: "XLRI Jamshedpur", meta: "Management · Jamshedpur", href: "https://www.xlri.ac.in/" },
      { name: "NLSIU Bangalore", meta: "Law · Bengaluru", tag: "Top Law", href: "https://www.nls.ac.in/" },
      { name: "NALSAR Hyderabad", meta: "Law · Hyderabad", href: "https://www.nalsar.ac.in/" },
      { name: "NLU Delhi", meta: "Law · New Delhi", href: "https://nludelhi.ac.in/" },
      { name: "University of Delhi", meta: "Arts, Science, Commerce · Delhi", href: "https://www.du.ac.in/" },
      { name: "St. Stephen's College", meta: "Arts & Science · Delhi", href: "https://www.ststephens.edu/" },
      { name: "SRCC", meta: "Commerce & Economics · Delhi", href: "https://www.srcc.edu/" },
      { name: "Miranda House", meta: "Arts & Science · Delhi", tag: "NIRF #1 College", href: "https://www.mirandahouse.ac.in/" },
      { name: "JNU", meta: "Humanities & Sciences · Delhi", href: "https://www.jnu.ac.in/" },
      { name: "BHU", meta: "Multidisciplinary · Varanasi", href: "https://www.bhu.ac.in/" },
      { name: "Ashoka University", meta: "Liberal Arts · Sonipat", href: "https://www.ashoka.edu.in/" },
      { name: "NID Ahmedabad", meta: "Design · Ahmedabad", tag: "Top Design", href: "https://www.nid.edu/" },
      { name: "NIFT", meta: "Fashion & Design · Pan-India", href: "https://www.nift.ac.in/" },
      { name: "Symbiosis (SIU)", meta: "Multidisciplinary · Pune", href: "https://www.siu.edu.in/" },
      { name: "Christ University", meta: "Multidisciplinary · Bengaluru", href: "https://christuniversity.in/" },
      { name: "Manipal (MAHE)", meta: "Multidisciplinary · Manipal", href: "https://manipal.edu/" },
      { name: "IIT Hyderabad", meta: "Engineering · Hyderabad", href: "https://www.iith.ac.in/" },
      { name: "IIT Indore", meta: "Engineering · Indore", href: "https://www.iiti.ac.in/" },
      { name: "IIT Gandhinagar", meta: "Engineering · Gandhinagar", href: "https://www.iitgn.ac.in/" },
      { name: "IIIT Hyderabad", meta: "CS & IT · Hyderabad", href: "https://www.iiit.ac.in/" },
      { name: "IIIT Delhi", meta: "CS & IT · New Delhi", href: "https://www.iiitd.ac.in/" },
      { name: "IIIT Bangalore", meta: "CS & IT · Bengaluru", href: "https://www.iiitb.ac.in/" },
      { name: "Delhi Technological University", meta: "Engineering · Delhi", href: "https://www.dtu.ac.in/" },
      { name: "NSUT", meta: "Engineering · Delhi", href: "https://www.nsut.ac.in/" },
      { name: "NIT Rourkela", meta: "Engineering · Rourkela", href: "https://www.nitrkl.ac.in/" },
      { name: "NIT Calicut", meta: "Engineering · Kozhikode", href: "https://www.nitc.ac.in/" },
      { name: "IISER Pune", meta: "Science & Research · Pune", href: "https://www.iiserpune.ac.in/" },
      { name: "IISER Kolkata", meta: "Science & Research · Kolkata", href: "https://www.iiserkol.ac.in/" },
      { name: "University of Hyderabad", meta: "Multidisciplinary · Hyderabad", href: "https://uohyd.ac.in/" },
      { name: "Jamia Millia Islamia", meta: "Multidisciplinary · Delhi", href: "https://jmi.ac.in/" },
      { name: "Aligarh Muslim University", meta: "Multidisciplinary · Aligarh", href: "https://www.amu.ac.in/" },
      { name: "University of Mumbai", meta: "Multidisciplinary · Mumbai", href: "https://mu.ac.in/" },
      { name: "Savitribai Phule Pune University", meta: "Multidisciplinary · Pune", href: "https://www.unipune.ac.in/" },
      { name: "TISS", meta: "Social Sciences · Mumbai", href: "https://www.tiss.edu/" },
      { name: "MDI Gurgaon", meta: "Management · Gurugram", href: "https://www.mdi.ac.in/" },
      { name: "SPJIMR", meta: "Management · Mumbai", href: "https://www.spjimr.org/" },
      { name: "GNLU", meta: "Law · Gandhinagar", href: "https://www.gnlu.ac.in/" },
      { name: "NLU Jodhpur", meta: "Law · Jodhpur", href: "https://www.nlujodhpur.ac.in/" },
      { name: "KGMU Lucknow", meta: "Medical · Lucknow", href: "https://www.kgmu.org/" },
      { name: "Maulana Azad Medical College", meta: "Medical · Delhi", href: "https://mamc.ac.in/" },
      { name: "AFMC Pune", meta: "Medical (Defence) · Pune", href: "https://www.afmc.nic.in/" },
      { name: "SRM Institute (SRMIST)", meta: "Engineering · Chennai", href: "https://www.srmist.edu.in/" },
      { name: "Thapar University", meta: "Engineering · Patiala", href: "https://www.thapar.edu/" },
      { name: "PES University", meta: "Engineering · Bengaluru", href: "https://www.pes.edu/" },
      { name: "Amity University", meta: "Multidisciplinary · Noida", href: "https://www.amity.edu/" },
      { name: "Lovely Professional University", meta: "Multidisciplinary · Punjab", href: "https://www.lpu.in/" },
    ],
  },
  {
    id: "colleges_ab", label: "Universities (Abroad)", icon: "compass",
    blurb: "QS World-ranked universities across the US, UK, Europe, Asia, Canada & Australia. Explore programmes and admissions.",
    items: [
      { name: "MIT", meta: "USA · Engineering & Tech", tag: "QS #1", href: "https://www.mit.edu/" },
      { name: "Stanford University", meta: "USA · Multidisciplinary", href: "https://www.stanford.edu/" },
      { name: "Harvard University", meta: "USA · Multidisciplinary", href: "https://www.harvard.edu/" },
      { name: "Caltech", meta: "USA · Science & Engineering", href: "https://www.caltech.edu/" },
      { name: "Princeton University", meta: "USA · Multidisciplinary", href: "https://www.princeton.edu/" },
      { name: "Yale University", meta: "USA · Multidisciplinary", href: "https://www.yale.edu/" },
      { name: "Columbia University", meta: "USA · Multidisciplinary", href: "https://www.columbia.edu/" },
      { name: "University of Chicago", meta: "USA · Multidisciplinary", href: "https://www.uchicago.edu/" },
      { name: "UC Berkeley", meta: "USA · Public research", href: "https://www.berkeley.edu/" },
      { name: "Carnegie Mellon", meta: "USA · CS & Engineering", href: "https://www.cmu.edu/" },
      { name: "Cornell University", meta: "USA · Multidisciplinary", href: "https://www.cornell.edu/" },
      { name: "University of Oxford", meta: "UK · Multidisciplinary", href: "https://www.ox.ac.uk/" },
      { name: "University of Cambridge", meta: "UK · Multidisciplinary", href: "https://www.cam.ac.uk/" },
      { name: "Imperial College London", meta: "UK · Science, Engg, Medicine", href: "https://www.imperial.ac.uk/" },
      { name: "UCL", meta: "UK · Multidisciplinary", href: "https://www.ucl.ac.uk/" },
      { name: "LSE", meta: "UK · Social Sciences & Economics", href: "https://www.lse.ac.uk/" },
      { name: "University of Edinburgh", meta: "UK · Multidisciplinary", href: "https://www.ed.ac.uk/" },
      { name: "ETH Zurich", meta: "Switzerland · Engg & Science", href: "https://ethz.ch/" },
      { name: "EPFL", meta: "Switzerland · Engg & Tech", href: "https://www.epfl.ch/" },
      { name: "NUS", meta: "Singapore · Multidisciplinary", tag: "Top Asia", href: "https://www.nus.edu.sg/" },
      { name: "NTU Singapore", meta: "Singapore · Engg & Business", href: "https://www.ntu.edu.sg/" },
      { name: "Tsinghua University", meta: "China · Engg & Science", href: "https://www.tsinghua.edu.cn/en/" },
      { name: "University of Tokyo", meta: "Japan · Multidisciplinary", href: "https://www.u-tokyo.ac.jp/en/" },
      { name: "University of Toronto", meta: "Canada · Multidisciplinary", href: "https://www.utoronto.ca/" },
      { name: "McGill University", meta: "Canada · Multidisciplinary", href: "https://www.mcgill.ca/" },
      { name: "University of British Columbia", meta: "Canada · Multidisciplinary", href: "https://www.ubc.ca/" },
      { name: "University of Melbourne", meta: "Australia · Multidisciplinary", href: "https://www.unimelb.edu.au/" },
      { name: "University of Sydney", meta: "Australia · Multidisciplinary", href: "https://www.sydney.edu.au/" },
      { name: "Australian National University", meta: "Australia · Research", href: "https://www.anu.edu.au/" },
      { name: "Technical University of Munich", meta: "Germany · Engg & Tech", href: "https://www.tum.de/en/" },
      { name: "Johns Hopkins University", meta: "USA · Medicine & Research", href: "https://www.jhu.edu/" },
      { name: "University of Pennsylvania", meta: "USA · Multidisciplinary", href: "https://www.upenn.edu/" },
      { name: "UCLA", meta: "USA · Public research", href: "https://www.ucla.edu/" },
      { name: "University of Michigan", meta: "USA · Multidisciplinary", href: "https://umich.edu/" },
      { name: "University of Illinois Urbana-Champaign", meta: "USA · Engg & CS", href: "https://illinois.edu/" },
      { name: "Georgia Institute of Technology", meta: "USA · Engineering", href: "https://www.gatech.edu/" },
      { name: "University of Texas at Austin", meta: "USA · Multidisciplinary", href: "https://www.utexas.edu/" },
      { name: "King's College London", meta: "UK · Multidisciplinary", href: "https://www.kcl.ac.uk/" },
      { name: "University of Manchester", meta: "UK · Multidisciplinary", href: "https://www.manchester.ac.uk/" },
      { name: "University of Warwick", meta: "UK · Business & Engg", href: "https://warwick.ac.uk/" },
      { name: "University of Bristol", meta: "UK · Multidisciplinary", href: "https://www.bristol.ac.uk/" },
      { name: "Delft University of Technology", meta: "Netherlands · Engg & Tech", href: "https://www.tudelft.nl/en/" },
      { name: "KU Leuven", meta: "Belgium · Multidisciplinary", href: "https://www.kuleuven.be/english/" },
      { name: "University of Amsterdam", meta: "Netherlands · Multidisciplinary", href: "https://www.uva.nl/en" },
      { name: "PSL University", meta: "France · Multidisciplinary", href: "https://psl.eu/en" },
      { name: "KAIST", meta: "South Korea · Science & Tech", href: "https://www.kaist.ac.kr/en/" },
      { name: "Seoul National University", meta: "South Korea · Multidisciplinary", href: "https://en.snu.ac.kr/" },
      { name: "University of Hong Kong", meta: "Hong Kong · Multidisciplinary", href: "https://www.hku.hk/" },
      { name: "University of Waterloo", meta: "Canada · Engg & CS", href: "https://uwaterloo.ca/" },
      { name: "Monash University", meta: "Australia · Multidisciplinary", href: "https://www.monash.edu/" },
      { name: "University of New South Wales", meta: "Australia · Engg & Business", href: "https://www.unsw.edu.au/" },
      { name: "University of Queensland", meta: "Australia · Multidisciplinary", href: "https://www.uq.edu.au/" },
      { name: "Trinity College Dublin", meta: "Ireland · Multidisciplinary", href: "https://www.tcd.ie/" },
      { name: "Politecnico di Milano", meta: "Italy · Engineering & Design", href: "https://www.polimi.it/en/" },
    ],
  },
  {
    id: "exams", label: "Entrance Exams", icon: "answer",
    blurb: "Key Indian & international entrance exams with official portals for dates, forms, syllabus & results.",
    items: [
      { name: "JEE Main", meta: "Engineering · NTA · Jan & Apr", href: "https://jeemain.nta.nic.in/" },
      { name: "JEE Advanced", meta: "IIT admission · May", href: "https://jeeadv.ac.in/" },
      { name: "BITSAT", meta: "BITS Pilani · May–Jun", href: "https://www.bitsadmission.com/" },
      { name: "GATE", meta: "PG Engineering · IISc/IITs · Feb", href: "https://gate2025.iitr.ac.in/" },
      { name: "NEET (UG)", meta: "Medical · NTA · May", href: "https://neet.nta.nic.in/" },
      { name: "NEET PG", meta: "PG Medical · NBEMS", href: "https://natboard.edu.in/" },
      { name: "CUET (UG)", meta: "Central universities · NTA · May", href: "https://cuet.nta.nic.in/" },
      { name: "CUET (PG)", meta: "PG central universities · NTA", href: "https://pgcuet.samarth.ac.in/" },
      { name: "CAT", meta: "MBA · IIMs · Nov", href: "https://iimcat.ac.in/" },
      { name: "XAT", meta: "MBA · XLRI · Jan", href: "https://www.xatonline.in/" },
      { name: "CMAT", meta: "MBA · NTA", href: "https://cmat.nta.nic.in/" },
      { name: "CLAT", meta: "Law · Consortium of NLUs · Dec", href: "https://consortiumofnlus.ac.in/" },
      { name: "AILET", meta: "Law · NLU Delhi", href: "https://nationallawuniversitydelhi.in/" },
      { name: "UGC NET", meta: "Research/Lectureship · NTA · Jun & Dec", href: "https://ugcnet.nta.nic.in/" },
      { name: "CSIR NET", meta: "Science research · NTA", href: "https://csirnet.nta.nic.in/" },
      { name: "UPSC Civil Services", meta: "IAS/IPS/IFS · UPSC", href: "https://upsc.gov.in/" },
      { name: "NDA & CDS", meta: "Defence · UPSC", href: "https://upsc.gov.in/" },
      { name: "SSC CGL", meta: "Govt jobs · SSC", href: "https://ssc.gov.in/" },
      { name: "NATA", meta: "Architecture · CoA", href: "https://www.nata.in/" },
      { name: "UCEED / CEED", meta: "Design · IIT Bombay", href: "https://www.uceed.iitb.ac.in/" },
      { name: "NID DAT", meta: "Design · NID · Dec–Jan", href: "https://admissions.nid.edu/" },
      { name: "SAT", meta: "US undergrad · College Board", href: "https://satsuite.collegeboard.org/sat" },
      { name: "GRE", meta: "Grad study abroad · ETS", href: "https://www.ets.org/gre.html" },
      { name: "GMAT", meta: "MBA abroad · GMAC", href: "https://www.mba.com/exams/gmat-exam" },
      { name: "IELTS", meta: "English proficiency", href: "https://www.ielts.org/" },
      { name: "TOEFL", meta: "English proficiency · ETS", href: "https://www.ets.org/toefl.html" },
      { name: "VITEEE", meta: "Engineering · VIT", href: "https://viteee.vit.ac.in/" },
      { name: "SRMJEEE", meta: "Engineering · SRM", href: "https://www.srmist.edu.in/" },
      { name: "COMEDK UGET", meta: "Engineering · Karnataka", href: "https://www.comedk.org/" },
      { name: "MHT CET", meta: "Engineering & Pharmacy · Maharashtra", href: "https://cetcell.mahacet.org/" },
      { name: "WBJEE", meta: "Engineering · West Bengal", href: "https://wbjeeb.nic.in/" },
      { name: "KCET", meta: "Engineering & Medical · Karnataka", href: "https://cetonline.karnataka.gov.in/kea/" },
      { name: "AP EAPCET", meta: "Engineering & Agri · Andhra Pradesh", href: "https://cets.apsche.ap.gov.in/" },
      { name: "IPMAT", meta: "Integrated MBA · IIM Indore/Rohtak", href: "https://www.iimidr.ac.in/" },
      { name: "SNAP", meta: "MBA · Symbiosis", href: "https://www.snaptest.org/" },
      { name: "NMAT", meta: "MBA · GMAC", href: "https://www.mba.com/exams/nmat" },
      { name: "IIT JAM", meta: "MSc admission · IITs", href: "https://jam2025.iitd.ac.in/" },
      { name: "CSIR UGC NET", meta: "Science research · NTA", href: "https://csirnet.nta.nic.in/" },
      { name: "AIIMS / INI CET", meta: "PG Medical · AIIMS", href: "https://www.aiimsexams.ac.in/" },
      { name: "CA Foundation (ICAI)", meta: "Chartered Accountancy", href: "https://www.icai.org/" },
      { name: "CS Foundation (ICSI)", meta: "Company Secretary", href: "https://www.icsi.edu/" },
      { name: "NEET MDS", meta: "PG Dental · NBEMS", href: "https://natboard.edu.in/" },
      { name: "DUET / PG", meta: "Delhi University admissions", href: "https://www.du.ac.in/" },
      { name: "PTE Academic", meta: "English proficiency", href: "https://www.pearsonpte.com/" },
      { name: "ACT", meta: "US undergrad admissions", href: "https://www.act.org/" },
    ],
  },
  {
    id: "internships", label: "Virtual Internships", icon: "briefcase",
    blurb: "200+ free virtual job simulations from real companies (Forage) plus live internship platforms — build experience & earn certificates.",
    items: [
      { name: "JPMorgan — Software Engineering", meta: "Tech · ~5 hrs · Certificate", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "JPMorgan — Investment Banking", meta: "Finance · Certificate", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Goldman Sachs — Engineering", meta: "Tech · Finance", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "BCG — Strategy Consulting", meta: "Consulting · Certificate", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Accenture — Coding & Development", meta: "Tech · Beginner-friendly", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Deloitte — Technology", meta: "Tech · Business", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Deloitte — Audit", meta: "Accounting & Assurance", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "PwC — Digital Assurance", meta: "Tech · Audit", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "KPMG — Data Analytics", meta: "Data · Audit", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "EY — Financial Accounting", meta: "Finance & Audit", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Citi — Markets", meta: "Finance", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Wells Fargo — Software Engineering", meta: "Tech · Finance", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Tata — Cybersecurity", meta: "Security · Tech", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Cognizant — Agile Methodology", meta: "Tech · Delivery", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Quantium — Data Analytics", meta: "Data Science", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Electronic Arts — Software Engineering", meta: "Gaming · Tech", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "GE Aerospace — Engineering", meta: "Mechanical / Aero", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Mastercard — Cybersecurity", meta: "Security · Tech", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Verizon — Cloud & AI", meta: "Tech", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Lloyds Banking — Data Science", meta: "Data · Finance", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Browse all 200+ programmes", meta: "Software, data, law, marketing, healthcare, design…", tag: "Forage", href: "https://www.theforage.com/simulations" },
      { name: "Internshala", meta: "Live internships & trainings across India", href: "https://internshala.com/" },
      { name: "LinkedIn — Internships", meta: "Live internship openings worldwide", href: "https://www.linkedin.com/jobs/internship-jobs/" },
      { name: "Microsoft — Software Engineering", meta: "Tech", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "AWS (Amazon) — Solutions Architecture", meta: "Cloud · Tech", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Cisco — Cybersecurity", meta: "Security · Networking", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Standard Bank — Africa Markets", meta: "Finance", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Commonwealth Bank — Intro to Banking", meta: "Finance", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "AIG — Data Analytics", meta: "Insurance · Data", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "BP — Trading & Shipping", meta: "Energy · Finance", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Walmart — Advanced Software Engineering", meta: "Retail · Tech", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Datacom — Cybersecurity", meta: "Security · Tech", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "TATA — Data Visualisation", meta: "Data · Consulting", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "BCG — GAMMA Data Science", meta: "Data & AI · Consulting", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Goldman Sachs — Operations", meta: "Finance", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "JPMorgan — Agile", meta: "Tech · Delivery", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "GE Aerospace — Data Analytics", meta: "Engineering · Data", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Verizon — Data Analytics", meta: "Data · Tech", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Accenture — Data Analytics & Visualisation", meta: "Data · Consulting", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "PwC — Cyber Security", meta: "Security · Audit", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "KPMG — Cyber Security", meta: "Security", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Citi — Technology Software Development", meta: "Tech · Finance", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Lloyds — Cyber Security", meta: "Security · Finance", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Bloomberg — Financial Data", meta: "Finance · Data", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Clifford Chance — Corporate Law", meta: "Law", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "White & Case — Corporate Law", meta: "Law", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "L'Oréal — Marketing", meta: "Marketing · Brand", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Ford — Software Engineering", meta: "Automotive · Tech", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "Wipro — Design Thinking", meta: "Tech · Consulting", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "SAP — Software Engineering", meta: "Enterprise · Tech", tag: "Free", href: "https://www.theforage.com/simulations" },
      { name: "AICTE Internship Portal", meta: "Govt of India internship platform", href: "https://internship.aicte-india.org/" },
      { name: "Unstop (internships & competitions)", meta: "India · internships, hackathons, jobs", href: "https://unstop.com/internships" },
      { name: "LetsIntern / Naukri Campus", meta: "Entry-level internships", href: "https://www.naukri.com/campus/" },
    ],
  },
  {
    id: "scholarships", label: "Scholarships", icon: "star",
    blurb: "Government and private scholarships, fellowships & education-loan portals — for study in India and abroad.",
    items: [
      { name: "National Scholarship Portal (NSP)", meta: "Govt — central & state · single window", tag: "Govt", href: "https://scholarships.gov.in/" },
      { name: "INSPIRE (SHE) Scholarship", meta: "Science UG · ₹80,000/year", href: "https://online-inspire.gov.in/" },
      { name: "PM Scholarship Scheme", meta: "Wards of ex-servicemen / forces", href: "https://scholarships.gov.in/" },
      { name: "Reliance Foundation Scholarships", meta: "UG & PG · strong for STEM", href: "https://www.reliancefoundation.org/" },
      { name: "Tata Trusts Scholarships", meta: "Merit-cum-means · across fields", href: "https://www.tatatrusts.org/" },
      { name: "Aditya Birla Scholarship", meta: "Top IIT/IIM/Law students", href: "https://www.adityabirlascholars.net/" },
      { name: "Sitaram Jindal Foundation", meta: "School & college · merit + means", href: "https://www.sitaramjindalfoundation.org/" },
      { name: "Glow & Lovely Careers", meta: "For young women", href: "https://www.glowandlovelycareers.in/" },
      { name: "Buddy4Study", meta: "Search thousands of scholarships", href: "https://www.buddy4study.com/" },
      { name: "Vidyalakshmi (Education Loans)", meta: "Govt portal for student loans", href: "https://www.vidyalakshmi.co.in/" },
      { name: "Fulbright-Nehru Fellowships", meta: "Postgraduate study in the USA", href: "https://www.usief.org.in/" },
      { name: "Chevening Scholarships", meta: "Fully-funded Master's in the UK", href: "https://www.chevening.org/" },
      { name: "Commonwealth Scholarships", meta: "Study in the UK", href: "https://cscuk.fcdo.gov.uk/" },
      { name: "DAAD Scholarships", meta: "Study in Germany", href: "https://www.daad.de/en/" },
      { name: "Erasmus Mundus", meta: "Joint Master's across Europe", href: "https://erasmus-plus.ec.europa.eu/" },
      { name: "Rhodes Scholarship", meta: "Fully-funded · University of Oxford", href: "https://www.rhodeshouse.ox.ac.uk/" },
      { name: "Gates Cambridge", meta: "Fully-funded · University of Cambridge", href: "https://www.gatescambridge.org/" },
      { name: "Inlaks Shivdasani Scholarship", meta: "Postgraduate study abroad", href: "https://www.inlaksfoundation.org/" },
      { name: "JN Tata Endowment", meta: "Loan-scholarship for study abroad", href: "https://www.jntataendowment.org/" },
      { name: "Narotam Sekhsaria Foundation", meta: "Postgraduate study loan-scholarship", href: "https://www.nsfoundation.co.in/" },
      { name: "HDFC Bank Parivartan (ECSS)", meta: "School to PG · merit-cum-means", href: "https://www.hdfcbankparivartan.com/" },
      { name: "L&T Build India Scholarship", meta: "MTech at IIT Delhi · construction", href: "https://www.lntecc.com/" },
      { name: "Kotak Kanya Scholarship", meta: "Girl students · professional courses", href: "https://kotakeducation.org/" },
      { name: "Colgate Keep India Smiling", meta: "Merit-cum-means · UG & PG", href: "https://www.colgatecares.in/" },
      { name: "Legrand Empowering Scholarship", meta: "Engineering & polytechnic", href: "https://www.buddy4study.com/" },
      { name: "Swami Vivekananda Merit-cum-Means", meta: "West Bengal students", href: "https://svmcm.wbhed.gov.in/" },
      { name: "Post-Matric (SC/ST/OBC)", meta: "Govt · reserved categories", href: "https://scholarships.gov.in/" },
      { name: "Maulana Azad Scholarship", meta: "Minority students", href: "https://www.maef.nic.in/" },
      { name: "Central Sector Scheme (CSS)", meta: "Merit · Class 12 toppers", href: "https://scholarships.gov.in/" },
      { name: "Prime Minister's Research Fellowship", meta: "PhD at IITs/IISc", href: "https://pmrf.in/" },
      { name: "AAUW International Fellowships", meta: "Women · study in the USA", href: "https://www.aauw.org/resources/programs/fellowships-grants/" },
      { name: "Knight-Hennessy Scholars", meta: "Fully-funded grad · Stanford", href: "https://knight-hennessy.stanford.edu/" },
      { name: "Schwarzman Scholars", meta: "Master's · Tsinghua, China", href: "https://www.schwarzmanscholars.org/" },
      { name: "Australia Awards", meta: "Study in Australia · Govt", href: "https://www.dfat.gov.au/people-to-people/australia-awards" },
      { name: "New Zealand Excellence Awards", meta: "Study in New Zealand", href: "https://www.studywithnewzealand.govt.nz/" },
    ],
  },
  {
    id: "careers", label: "Career Library", icon: "cap",
    blurb: "Explore what careers actually involve — day-to-day tasks, skills, pay and job outlook (O*NET occupational data).",
    items: [
      { name: "Software Developer", meta: "Tech · high growth", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/15-1252.00" },
      { name: "Data Scientist", meta: "Data & AI · high growth", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/15-2051.00" },
      { name: "Web & Digital Interface Designer", meta: "UX / Front-end", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/15-1255.00" },
      { name: "Information Security Analyst", meta: "Cybersecurity", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/15-1212.00" },
      { name: "Database Administrator", meta: "Data & Systems", href: "https://www.onetonline.org/link/summary/15-1242.00" },
      { name: "Computer & IS Manager", meta: "Tech leadership", href: "https://www.onetonline.org/link/summary/11-3021.00" },
      { name: "Mechanical Engineer", meta: "Engineering", href: "https://www.onetonline.org/link/summary/17-2141.00" },
      { name: "Civil Engineer", meta: "Engineering & Construction", href: "https://www.onetonline.org/link/summary/17-2051.00" },
      { name: "Electrical Engineer", meta: "Engineering", href: "https://www.onetonline.org/link/summary/17-2071.00" },
      { name: "Aerospace Engineer", meta: "Engineering", href: "https://www.onetonline.org/link/summary/17-2011.00" },
      { name: "Architect", meta: "Design & Construction", href: "https://www.onetonline.org/link/summary/17-1011.00" },
      { name: "Registered Nurse", meta: "Healthcare", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/29-1141.00" },
      { name: "Physician (Family Medicine)", meta: "Healthcare", href: "https://www.onetonline.org/link/summary/29-1215.00" },
      { name: "Surgeon", meta: "Healthcare", href: "https://www.onetonline.org/link/summary/29-1248.00" },
      { name: "Pharmacist", meta: "Healthcare", href: "https://www.onetonline.org/link/summary/29-1051.00" },
      { name: "Physical Therapist", meta: "Healthcare", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/29-1123.00" },
      { name: "Graphic Designer", meta: "Arts & Design", href: "https://www.onetonline.org/link/summary/27-1024.00" },
      { name: "Financial Analyst", meta: "Business & Finance", href: "https://www.onetonline.org/link/summary/13-2051.00" },
      { name: "Accountant & Auditor", meta: "Business & Finance", href: "https://www.onetonline.org/link/summary/13-2011.00" },
      { name: "Management Consultant", meta: "Business", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/13-1111.00" },
      { name: "Marketing Manager", meta: "Business", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/11-2021.00" },
      { name: "Lawyer", meta: "Law", href: "https://www.onetonline.org/link/summary/23-1011.00" },
      { name: "Clinical Psychologist", meta: "Human Services", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/19-3033.00" },
      { name: "Secondary School Teacher", meta: "Education", href: "https://www.onetonline.org/link/summary/25-2031.00" },
      { name: "News Reporter & Journalist", meta: "Media & Communication", href: "https://www.onetonline.org/link/summary/27-3023.00" },
      { name: "Biomedical Engineer", meta: "Engineering & Healthcare", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/17-2031.00" },
      { name: "Statistician", meta: "Data & Analytics", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/15-2041.00" },
      { name: "Actuary", meta: "Finance & Risk", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/15-2011.00" },
      { name: "Computer Programmer", meta: "Tech", href: "https://www.onetonline.org/link/summary/15-1251.00" },
      { name: "Industrial Engineer", meta: "Engineering", href: "https://www.onetonline.org/link/summary/17-2112.00" },
      { name: "Chemical Engineer", meta: "Engineering", href: "https://www.onetonline.org/link/summary/17-2041.00" },
      { name: "Environmental Engineer", meta: "Engineering & Sustainability", href: "https://www.onetonline.org/link/summary/17-2081.00" },
      { name: "Economist", meta: "Social Science & Policy", href: "https://www.onetonline.org/link/summary/19-3011.00" },
      { name: "Microbiologist", meta: "Life Sciences", href: "https://www.onetonline.org/link/summary/19-1022.00" },
      { name: "Chemist", meta: "Physical Sciences", href: "https://www.onetonline.org/link/summary/19-2031.00" },
      { name: "Physicist", meta: "Physical Sciences", href: "https://www.onetonline.org/link/summary/19-2012.00" },
      { name: "Urban & Regional Planner", meta: "Public Services", href: "https://www.onetonline.org/link/summary/19-3051.00" },
      { name: "Veterinarian", meta: "Healthcare (Animals)", href: "https://www.onetonline.org/link/summary/29-1131.00" },
      { name: "Dentist", meta: "Healthcare", href: "https://www.onetonline.org/link/summary/29-1021.00" },
      { name: "Occupational Therapist", meta: "Healthcare", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/29-1122.00" },
      { name: "Speech-Language Pathologist", meta: "Healthcare", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/29-1127.00" },
      { name: "Human Resources Manager", meta: "Business", href: "https://www.onetonline.org/link/summary/11-3121.00" },
      { name: "Sales Manager", meta: "Business", href: "https://www.onetonline.org/link/summary/11-2022.00" },
      { name: "Public Relations Specialist", meta: "Media & Communication", href: "https://www.onetonline.org/link/summary/27-3031.00" },
      { name: "Technical Writer", meta: "Media & Communication", href: "https://www.onetonline.org/link/summary/27-3042.00" },
      { name: "Interior Designer", meta: "Arts & Design", href: "https://www.onetonline.org/link/summary/27-1025.00" },
      { name: "Fashion Designer", meta: "Arts & Design", href: "https://www.onetonline.org/link/summary/27-1022.00" },
      { name: "Film & Video Editor", meta: "Media & Arts", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/27-4032.00" },
      { name: "Chef & Head Cook", meta: "Hospitality", tag: "Bright Outlook", href: "https://www.onetonline.org/link/summary/35-1011.00" },
      { name: "Airline Pilot", meta: "Aviation & Transport", href: "https://www.onetonline.org/link/summary/53-2011.00" },
    ],
  },
];
