/**
 * "Based on your specific strengths" — the Class 12 JEE page's third
 * source of alternatives, distinct from both the job-role ranking
 * (careerFitEngine1112.ts) and the degree-eligibility matrix
 * (degreeStreamMatrix.ts). Where those two answer "what fits your measured
 * profile" and "what can your stream reach", this one answers a third,
 * genuinely different question: "given the SPECIFIC combination of
 * strengths you actually showed — not a domain, a named dimension like
 * Mathematical Ability or Coding Interest — what does that point toward?"
 *
 * Extracted verbatim from the user-provided workbook "11-12th Streams list
 * (1).xlsx", sheet "After 12th Career Paths", rows 49-64: a dimension × the
 * three broad stream groups (MPC/PCM, BiPC/PCB, CEC) table, each cell with
 * a real question, courses, job roles, skills to build, an Indicative
 * Salary Range, and — uniquely among everything else in this report —
 * actual Government Jobs / Career Pathways for that specific dimension.
 * (One stray malformed row, "Student Profile" under BiPC/PCB — a leftover
 * header from a different mini-table further down the same sheet — is
 * dropped rather than encoded as a dimension.)
 *
 * The dimension NAMES differ per stream group (e.g. BiPC/PCB has "Medical /
 * Healthcare Interest", CEC has "Legal & Civic Interest") because the
 * workbook itself tailors which strengths are even worth asking about per
 * stream — this is preserved as-is rather than forced into one shared list.
 */
import type { PsychometricProfile } from "@/lib/newAssessment/scoring11_12";
import type { StreamKey1112 } from "@/lib/report/careerfit1112";

export type StreamGroup = "MPC/PCM" | "BiPC/PCB" | "CEC";

export interface DimensionEntry {
  dimension: string;
  question: string;
  courses: string;
  jobs: string;
  skills: string;
  salary: string;
  govtJobs: string;
}

/** MPC and PCMB both draw on the MPC/PCM group — PCMB is MPC's subjects plus Biology, so its quantitative dimensions still apply directly. Humanities and Vocational/Other have no matching group in the source sheet. */
export function streamGroupFor(streamKey: StreamKey1112): StreamGroup | null {
  if (streamKey === "MPC" || streamKey === "PCMB") return "MPC/PCM";
  if (streamKey === "BiPC") return "BiPC/PCB";
  if (streamKey === "Commerce+Maths" || streamKey === "Commerce (CEC, no Maths)") return "CEC";
  return null;
}

export const DIMENSION_GUIDE: Record<StreamGroup, DimensionEntry[]> = {
  "MPC/PCM": [
    { dimension: "Mathematical Ability", question: "How naturally strong am I at mathematics?", courses: "B.Sc Mathematics, BS Mathematics, B.Math, B.Stat, B.Sc Statistics, B.Sc Actuarial Science, B.Sc Data Science, B.Sc Economics, B.Sc Economics & Mathematics, Integrated M.Sc Mathematics, Integrated M.Sc Statistics, B.Tech Mathematics & Computing", jobs: "Mathematician, Statistician, Data Analyst, Data Scientist, Actuary, Risk Analyst, Quantitative Analyst, Financial Analyst, Econometrician, Operations Research Analyst, Researcher, Mathematics Teacher/Professor", skills: "Advanced Mathematics, Calculus, Linear Algebra, Probability, Statistics, Mathematical Modelling, Excel, Python, R, SQL, Data Analysis, Critical Thinking, Problem Solving, Financial Mathematics", salary: "₹3–8 LPA entry; ₹8–20 LPA mid-career; ₹20–50+ LPA senior/specialist. Quant/actuarial/data specialists can go substantially higher.", govtJobs: "Indian Statistical Service (ISS)*, Statistical Investigator/Statistical Assistant posts, SSC CGL statistical posts where eligible, RBI/NABARD/SEBI analytical roles, government statistical departments, economic/statistical research roles, State PSC statistical services" },
    { dimension: "Logical Reasoning", question: "Do I enjoy solving unfamiliar problems?", courses: "B.Tech CSE, B.Tech AI & ML, B.Tech Data Science, B.Sc Computer Science, BCA, B.Sc Mathematics, B.Sc Statistics, B.Stat, B.Sc Data Science, B.Sc Cybersecurity, B.Sc Operations Research, B.Tech Robotics & Automation", jobs: "Software Developer, AI/ML Engineer, Data Scientist, Data Analyst, Cybersecurity Analyst, Systems Analyst, Operations Research Analyst, Robotics Engineer, Algorithm Engineer, Researcher", skills: "Logical Reasoning, Algorithms, Data Structures, Programming, Python/Java/C++, SQL, Problem Solving, Computational Thinking, Statistics, Debugging, System Thinking", salary: "₹4–10 LPA entry; ₹10–25 LPA mid-career; ₹25–60+ LPA senior/specialist. Strong product-company/AI roles can exceed this.", govtJobs: "UPSC Civil Services, SSC CGL, Banking PO, RBI Grade B, NABARD Grade A, SEBI Grade A, government analytical/technical recruitment, State PSC examinations" },
    { dimension: "Coding Interest", question: "Do I genuinely enjoy programming, or am I only considering CSE because everyone recommends it?", courses: "B.Tech CSE, B.Tech IT, B.Tech AI & ML, B.Tech Data Science, B.Tech Cybersecurity, B.Sc Computer Science, B.Sc Data Science, BCA, B.Sc IT, B.Sc Artificial Intelligence, B.Tech Software Engineering, B.Tech Computer Engineering", jobs: "Software Engineer, Full-Stack Developer, Backend Developer, Frontend Developer, Mobile App Developer, AI Engineer, ML Engineer, Data Engineer, Cloud Engineer, DevOps Engineer, Cybersecurity Engineer, QA Engineer", skills: "Python, Java, C++, JavaScript/TypeScript, HTML/CSS, Data Structures & Algorithms, Git/GitHub, SQL, APIs, Databases, Cloud, Linux, Testing, Debugging, System Design", salary: "₹4–12 LPA entry; ₹12–30 LPA mid-career; ₹30–70+ LPA senior. 2026 benchmarks show wide variation between services, GCCs and product companies.", govtJobs: "Government IT/technical recruitment, NIC technical roles, NIELIT-related recruitment, MeitY/Ministry technical posts, ISRO technical/scientific recruitment, DRDO technical/scientific roles, PSU IT/technology recruitment" },
    { dimension: "Scientific Interest", question: "Do I enjoy understanding scientific concepts deeply?", courses: "B.Sc Physics, BS Physics, B.Sc Chemistry, B.Sc Mathematics, B.Sc Geology, B.Sc Environmental Science, B.Sc Materials Science, Integrated M.Sc Physics, Integrated M.Sc Chemistry, Integrated M.Sc Mathematics, BS Research, B.Sc Astronomy/Astrophysics where offered", jobs: "Research Scientist, Laboratory Analyst, Physicist, Chemist, Materials Scientist, Geologist, Environmental Scientist, Scientific Officer, R&D Associate, Science Educator, Scientific Data Analyst", skills: "Scientific Method, Experimental Design, Laboratory Skills, Data Analysis, Statistics, Scientific Writing, Research Methodology, Python/MATLAB/R, Instrumentation, Documentation, Critical Thinking", salary: "₹3–7 LPA entry; ₹6–15 LPA mid-career; ₹12–30+ LPA experienced/specialist. Research careers can require M.Sc/PhD for higher-level positions.", govtJobs: "ISRO Scientist/Engineer*, DRDO Scientist*, BARC/DAE scientific recruitment*, CSIR laboratories, government scientific laboratories, Scientific Officer roles, Geological Survey-related careers, State scientific departments" },
    { dimension: "Spatial Ability", question: "Can I visualize objects, structures and spaces?", courses: "B.Arch, B.Plan, B.Des Spatial Design, B.Des Industrial Design, B.Des Product Design, B.Tech Civil Engineering, B.Tech Mechanical Engineering, B.Tech Aerospace Engineering, B.Tech Automobile Engineering, B.Tech Mechatronics, B.Tech Robotics", jobs: "Architect, Urban Planner, Product Designer, Industrial Designer, CAD Designer, Mechanical Engineer, Civil Engineer, Aerospace Engineer, Automotive Engineer, Robotics Engineer, 3D Designer", skills: "Spatial Reasoning, Technical Drawing, AutoCAD, SolidWorks, CATIA, 3D Modelling, CAD, Design Thinking, Engineering Drawing, Structural Thinking, Prototyping, Visualization", salary: "₹3–7 LPA entry; ₹7–18 LPA mid-career; ₹15–35+ LPA senior/specialist. Product/industrial design and specialized engineering can command higher compensation.", govtJobs: "UPSC Engineering Services (after eligible engineering degree)*, CPWD engineering roles, Central/State PWD, Railways engineering services, Defence engineering organisations, municipal/urban development departments, government architecture/planning roles. UPSC Engineering Services is specifically degree-based; engineering qualifications are required. (UPSC)" },
    { dimension: "Creativity", question: "Do I enjoy creating something new?", courses: "B.Des Product Design, B.Des Industrial Design, B.Des UX/UI/Interaction Design, B.Des Communication Design, B.Arch, B.Des Animation, B.Des Game Design, BFA Animation, B.Sc Animation & VFX, Design/Technology programmes", jobs: "Product Designer, UX Designer, UI Designer, Interaction Designer, Industrial Designer, Graphic Designer, Animation Artist, 3D Artist, Game Designer, Game Artist, Motion Designer, Creative Technologist", skills: "Design Thinking, User Research, Figma, Adobe Creative Suite, Prototyping, Typography, Visual Communication, Storytelling, 3D Tools, Animation, Portfolio Development, User-Centred Design", salary: "₹3–8 LPA entry; ₹8–20 LPA mid-career; ₹20–40+ LPA senior. UX/product design in strong technology companies can be considerably higher. 2026 benchmarks put UI/UX around ₹5–10 LPA for many freshers and ₹30–45+ LPA for senior specialists in product-led markets.", govtJobs: "Government design/communication positions, public-sector creative/communication roles, government media/design departments, cultural institutions, public broadcasting/design roles, recruitment through SSC/UPSC/State PSC where design/communication posts are notified" },
    { dimension: "People Orientation", question: "Do I enjoy working with and influencing people?", courses: "BBA, BMS, BA Economics, B.Sc Economics, BA LLB, BBA LLB, B.Com, Bachelor of Hotel Management, BJMC, BSW, B.A. Psychology where eligible, Integrated Management", jobs: "HR Executive, HR Business Partner, Management Trainee, Sales Manager, Business Development Executive, Consultant, Lawyer, Corporate Relations Manager, Recruiter, Customer Success Manager, Hospitality Manager, Communications Specialist", skills: "Communication, Public Speaking, Negotiation, Presentation, Leadership, Emotional Intelligence, Relationship Management, Sales, Conflict Resolution, Teamwork, Networking, Business Writing", salary: "₹3–7 LPA entry; ₹7–18 LPA mid-career; ₹15–35+ LPA senior. Consulting, corporate law, sales leadership and senior management can go much higher.", govtJobs: "UPSC Civil Services, State PSC, SSC CGL, Banking PO, EPFO/ESIC-related recruitment, public-sector HR/administrative roles, government management/administrative positions" },
    { dimension: "Business Orientation", question: "Do I enjoy money, markets, strategy and entrepreneurship?", courses: "BBA, BMS, BBA Business Analytics, BBA Finance, B.Com, B.Com Finance, B.Sc Economics, B.A. Economics, B.Sc Economics & Mathematics, Integrated Management, BBA Entrepreneurship, BBA FinTech", jobs: "Business Analyst, Financial Analyst, Investment Analyst, Management Consultant, Product Manager, Business Development Manager, Entrepreneur, FinTech Analyst, Strategy Analyst, Operations Manager, Marketing Manager", skills: "Financial Literacy, Excel, Financial Modelling, Business Analysis, Market Research, Strategy, Communication, Presentation, Negotiation, Leadership, SQL/Data Analytics, Entrepreneurship, Project Management", salary: "₹4–10 LPA entry; ₹10–25 LPA mid-career; ₹20–50+ LPA senior. Product management, consulting and high-end finance can exceed these ranges substantially.", govtJobs: "RBI Grade B, SEBI Grade A, NABARD Grade A, SIDBI-related recruitment, public-sector bank PO, LIC AAO, government financial/regulatory institutions, PSU management/administrative recruitment, UPSC Civil Services" },
    { dimension: "Research Orientation", question: "Do I enjoy experimentation and discovering new things?", courses: "BS Research, B.Sc Physics, B.Sc Mathematics, B.Sc Chemistry, B.Sc Biology where eligibility permits, B.Sc Statistics, B.Sc Data Science, Integrated M.Sc Physics, Integrated M.Sc Chemistry, Integrated M.Sc Mathematics, Integrated M.Sc Data Science, BS-MS Research programmes", jobs: "Research Assistant, Research Scientist, R&D Associate, Data Scientist, Scientific Analyst, Research Analyst, University Researcher, Academic Researcher, Laboratory Researcher, Scientific Programmer", skills: "Research Methodology, Experimental Design, Statistics, Data Analysis, Scientific Writing, Literature Review, Academic Publishing, Python/R/MATLAB, Critical Thinking, Presentation, Documentation", salary: "₹3–8 LPA entry; ₹7–18 LPA mid-career; ₹15–35+ LPA specialist/research-industry roles. Academic/research salaries depend heavily on qualification, institution and experience.", govtJobs: "ISRO, DRDO, CSIR laboratories, BARC/DAE, government research institutes, scientific departments, research positions in central/state institutions, government statistical/economic research roles" },
    { dimension: "Risk Orientation", question: "Am I comfortable with uncertain/high-risk/high-reward careers?", courses: "BBA Entrepreneurship, BBA, BMS, Economics, Finance, BBA FinTech, B.Sc Data Science, B.Tech CSE, B.Tech AI & ML, BBA Business Analytics, B.Des Product Design, Integrated Management, Aviation/CPL pathways", jobs: "Entrepreneur, Startup Founder, Product Manager, Investment Analyst, Venture Capital Analyst, FinTech Professional, Business Strategist, Risk Analyst, Aviation Professional, Product Entrepreneur", skills: "Risk Assessment, Financial Literacy, Decision Making, Leadership, Negotiation, Sales, Market Research, Product Development, Financial Modelling, Communication, Networking, Resilience, Adaptability", salary: "₹4–12 LPA entry for salaried roles; ₹12–35+ LPA experienced; ₹50 LPA–₹1Cr+ possible in senior finance/product roles. Entrepreneurship has no predictable salary range because income depends on business performance.", govtJobs: "RBI Grade B, SEBI Grade A, NABARD Grade A, IRDAI Assistant Manager*, PFRDA Grade A*, public-sector bank PO, LIC AAO, insurance-sector government recruitment, financial/regulatory institutions" },
    { dimension: "Work Environment", question: "Do I prefer office, laboratory, field, travel, technology or people-facing work?", courses: "Office/Technology → B.Tech CSE, BCA, B.Sc CS, B.Sc Data Science; Laboratory → B.Sc Physics, Chemistry, Materials Science; Field → B.Sc Geology, Environmental Science, Civil Engineering; Travel → Aviation, Nautical Science, Merchant Navy; People-facing → BBA, Management, Law, Economics; Design → B.Arch, B.Des Product Design, Industrial Design", jobs: "Software Engineer, Data Analyst, Research Scientist, Laboratory Analyst, Geologist, Environmental Consultant, Civil Engineer, Pilot, Marine Officer, Architect, Product Designer, Business Manager, Lawyer, Consultant", skills: "Technology: Coding, SQL, Cloud; Lab: Research, Laboratory Techniques; Field: Field Research, GIS, Project Management; Travel: Communication, Safety, Navigation; People: Communication, Negotiation, Leadership; Design: Design Thinking, CAD, Figma, Portfolio", salary: "Highly role-dependent: approximately ₹3–12 LPA entry; ₹8–30 LPA mid-career; ₹20–60+ LPA senior/specialist. Technology/product roles generally have the widest upside.", govtJobs: "Technology → ISRO/DRDO/NIC/MeitY; Engineering → Railways/CPWD/PWD/PSUs; Research → CSIR/DAE/DRDO/ISRO; Administration → UPSC/State PSC/SSC; Banking → RBI/PSU banks; Defence → NDA/CDS/technical entries" },
    { dimension: "Motivators", question: "What matters most: income, stability, prestige, freedom, research, creativity or impact?", courses: "Income → Quant Finance, Actuarial Science, AI/ML, Data Science, CSE; Stability → Statistics, Mathematics, Government/Defence, Science; Prestige → Research, Law, Management, Engineering; Freedom → Entrepreneurship, Design, Technology; Research → Physics, Mathematics, Chemistry, Data Science; Creativity → Architecture, Product Design, UX/UI, Animation; Impact → Environmental Science, Sustainability, Healthcare Technology, Defence, Research", jobs: "Quant Analyst, Actuary, AI Engineer, Data Scientist, Software Engineer, Research Scientist, Lawyer, Management Consultant, Entrepreneur, Architect, Product Designer, Environmental Scientist, Defence Officer, Sustainability Professional", skills: "Income: Finance, AI, Data, Business; Stability: Core expertise, certifications, competitive exams; Research: Research methodology, academic writing; Creativity: Design tools, portfolio; Leadership: Communication, management; Impact: Domain expertise, project management, sustainability knowledge", salary: "₹3–15 LPA entry depending on career; ₹10–35 LPA mid-career; ₹20–60+ LPA senior/specialist. Quant, AI, technology, consulting and senior management can exceed these ranges.", govtJobs: "Stability → SSC/Banking/RBI/PSU/Government; Prestige/Administration → UPSC/State PSC; Research → ISRO/DRDO/CSIR/DAE; Mathematics → ISS; Economics → IES; Engineering → ESE/PSUs; Defence → NDA/CDS/technical entries" },
  ],
  "BiPC/PCB": [
    { dimension: "Mathematical Ability", question: "How comfortable am I with numbers, calculations, data and quantitative thinking?", courses: "B.Sc Statistics, B.Sc Data Science, B.Sc Mathematics where eligible, B.Sc Economics where eligibility permits, B.Sc Biostatistics, B.Sc Biotechnology, B.Sc Bioinformatics, B.Sc Computational Biology, B.Sc Actuarial Science where eligible, B.Tech Biotechnology, B.Tech Bioinformatics", jobs: "Biostatistician, Data Analyst, Bioinformatics Analyst, Computational Biologist, Clinical Data Analyst, Research Data Analyst, Statistical Analyst, Healthcare Data Analyst", skills: "Statistics, Probability, Excel, Python, R, SQL, Data Visualization, Biostatistics, Mathematical Modelling, Data Interpretation, Critical Thinking", salary: "₹3–8 LPA entry; ₹8–20 LPA mid-career; ₹20–40+ LPA senior/specialist", govtJobs: "Indian Statistical Service (ISS)*, Statistical Investigator roles, government health-data/statistical departments, ICMR research/data roles, public-health analytics, government research organisations" },
    { dimension: "Logical Reasoning", question: "Do I enjoy analysing problems, symptoms, evidence and finding solutions?", courses: "MBBS, BDS, B.Pharm, Pharm.D, B.Sc Biotechnology, B.Sc Microbiology, B.Sc Biochemistry, B.Sc Genetics, B.Sc Bioinformatics, B.Sc Neuroscience, B.Sc Biomedical Science, B.Sc Forensic Science", jobs: "Doctor, Dentist, Pharmacist, Clinical Research Associate, Microbiologist, Biochemist, Geneticist, Biomedical Scientist, Forensic Scientist, Clinical Data Analyst", skills: "Analytical Thinking, Clinical Reasoning, Problem Solving, Observation, Evidence-Based Thinking, Research Methodology, Data Analysis, Scientific Reasoning", salary: "₹3–10 LPA entry; ₹8–25 LPA mid-career; ₹20–60+ LPA senior/specialist", govtJobs: "UPSC Civil Services, State PSC, SSC CGL, government healthcare/research recruitment, forensic science departments, government laboratories, public-sector healthcare institutions" },
    { dimension: "Scientific Interest", question: "Do I enjoy understanding living organisms, diseases, chemistry and how the human body works?", courses: "MBBS, BDS, BVSc & AH, B.Pharm, Pharm.D, B.Sc Nursing, BPT, BOT, B.Sc Biotechnology, B.Sc Microbiology, B.Sc Biochemistry, B.Sc Genetics, B.Sc Zoology, B.Sc Botany, B.Sc Biomedical Science, Integrated M.Sc Life Sciences", jobs: "Doctor, Dentist, Veterinarian, Pharmacist, Physiotherapist, Microbiologist, Biotechnologist, Biochemist, Biomedical Scientist, Research Scientist, Laboratory Scientist", skills: "Biology, Chemistry, Laboratory Techniques, Scientific Method, Experimental Design, Observation, Research Methodology, Scientific Writing, Data Analysis", salary: "₹3–8 LPA entry; ₹8–20 LPA mid-career; ₹20–50+ LPA specialist", govtJobs: "Government medical services, veterinary services, government laboratories, ICMR/CSIR research institutions, DRDO/defence research, BARC/DAE scientific roles, government universities/research institutions" },
    { dimension: "Medical / Healthcare Interest", question: "Do I want to directly diagnose, treat, rehabilitate or care for people?", courses: "MBBS, BDS, BAMS, BHMS, BUMS, BSMS, BVSc & AH, B.Sc Nursing, BPT, BOT, B.Pharm, Pharm.D, BASLP, B.Optom, B.Sc Medical Laboratory Technology, B.Sc Radiology/Medical Imaging, B.Sc Emergency Care", jobs: "Doctor, Dentist, Ayurvedic Physician, Homeopathic Physician, Veterinary Doctor, Nurse, Physiotherapist, Occupational Therapist, Pharmacist, Optometrist, Medical Lab Technologist, Radiology Technologist, Audiologist", skills: "Clinical Knowledge, Patient Communication, Observation, Clinical Reasoning, Anatomy & Physiology, Diagnosis/Treatment Skills, Empathy, Ethics, Teamwork", salary: "₹3–8 LPA entry; ₹8–25 LPA experienced; ₹20–60+ LPA specialists. Doctors and specialists can earn substantially more with experience/private practice.", govtJobs: "UPSC Combined Medical Services (MBBS)*, Central/State government Medical Officer, government hospitals, ESIC hospitals, CGHS, Railways medical services, Armed Forces medical services, government nursing/pharmacy/allied-health recruitment. UPSC conducted CMS 2026 for medical-service recruitment." },
    { dimension: "Research Orientation", question: "Do I enjoy experiments, discovering new findings and understanding why things happen?", courses: "BS-MS Research, B.Sc Biotechnology, B.Sc Microbiology, B.Sc Biochemistry, B.Sc Genetics, B.Sc Molecular Biology, B.Sc Biomedical Science, B.Sc Neuroscience, B.Sc Zoology, B.Sc Botany, Integrated M.Sc Life Sciences, B.Sc Bioinformatics", jobs: "Research Assistant, Research Scientist, R&D Associate, Molecular Biologist, Microbiologist, Biochemist, Geneticist, Biomedical Researcher, Clinical Researcher, Bioinformatics Researcher", skills: "Research Methodology, Laboratory Skills, Molecular Biology, Cell Biology, Experimental Design, Statistics, Scientific Writing, Literature Review, Data Analysis, Publication Skills", salary: "₹3–8 LPA entry; ₹7–18 LPA mid-career; ₹15–40+ LPA specialist/research-industry", govtJobs: "ICMR, CSIR laboratories, DBT-supported institutions, DRDO, BARC/DAE, government universities, agricultural/life-science research institutes, government scientific organisations" },
    { dimension: "People Orientation", question: "Do I enjoy helping, communicating with and working closely with people?", courses: "B.Sc Nursing, MBBS, BDS, BPT, BOT, BASLP, B.Optom, BSW, Psychology-related programmes where eligible, Public Health, Healthcare Management, Hospital Administration", jobs: "Nurse, Doctor, Dentist, Physiotherapist, Occupational Therapist, Audiologist, Optometrist, Counsellor where qualified, Healthcare Manager, Patient Care Coordinator, Public Health Professional", skills: "Communication, Empathy, Active Listening, Patient Counselling, Emotional Intelligence, Teamwork, Leadership, Conflict Management, Documentation", salary: "₹3–8 LPA entry; ₹7–18 LPA mid-career; ₹15–35+ LPA senior", govtJobs: "Government Nursing Services, AIIMS/central institutes, ESIC, Railways, State Health Departments, government hospitals, Public Health Departments, National Health Mission and other notified healthcare recruitment" },
    { dimension: "Creativity", question: "Do I enjoy creating new solutions, products, treatments or ways of communicating science?", courses: "B.Sc Biotechnology, B.Sc Bioinformatics, B.Des, B.Sc Nutrition & Dietetics, Food Technology, B.Sc Food Science, Biomedical Design-related programmes, Communication/Media programmes where eligible", jobs: "Biotech Product Developer, Food Product Developer, Nutrition Content Specialist, Scientific Communicator, Biomedical Product Designer, UX/Health-tech Designer, Innovation Associate", skills: "Creative Problem Solving, Design Thinking, Communication, Product Development, Scientific Communication, Prototyping, Presentation, Visualisation", salary: "₹3–8 LPA entry; ₹8–20 LPA mid-career; ₹20–40+ LPA senior/specialist", govtJobs: "Government innovation/research programmes, biotechnology missions, food research institutions, agricultural innovation organisations, public research laboratories, scientific communication roles where notified" },
    { dimension: "Business Orientation", question: "Do I enjoy healthcare, pharmaceuticals, business, markets and entrepreneurship?", courses: "B.Pharm, Pharm.D, BBA Healthcare Management, BBA, B.Sc Biotechnology, B.Sc Food Technology, B.Sc Nutrition, Hospital Administration, Healthcare Management, B.Sc Life Sciences", jobs: "Pharmaceutical Sales Manager, Product Executive, Healthcare Business Analyst, Hospital Administrator, Pharma Product Manager, Medical Representative, Healthcare Consultant, Biotech Business Development Manager, Entrepreneur", skills: "Business Communication, Sales, Marketing, Financial Literacy, Market Research, Healthcare Economics, Product Management, Negotiation, Leadership, Excel, Data Analysis", salary: "₹3–8 LPA entry; ₹8–20 LPA mid-career; ₹20–50+ LPA senior", govtJobs: "Government pharmaceutical/public-health administration, PSU pharma organisations, government hospital administration, health-programme management, public-sector healthcare organisations, UPSC/State PSC administrative pathways" },
    { dimension: "Environmental / Nature Interest", question: "Do I enjoy plants, animals, ecosystems, environment and the natural world?", courses: "B.Sc Botany, B.Sc Zoology, B.Sc Environmental Science, B.Sc Forestry, B.Sc Agriculture, B.Sc Horticulture, B.Sc Fisheries, B.Sc Wildlife Science, B.Sc Geology where eligible, B.Sc Marine Biology where offered", jobs: "Environmental Scientist, Botanist, Zoologist, Wildlife Biologist, Ecologist, Forest Officer, Agricultural Scientist, Horticulturist, Fisheries Scientist, Conservation Specialist, Sustainability Analyst", skills: "Field Research, Ecology, GIS, Data Collection, Environmental Assessment, Scientific Writing, Statistics, Geographic Information Systems, Conservation Methods", salary: "₹3–7 LPA entry; ₹7–18 LPA mid-career; ₹15–35+ LPA specialist", govtJobs: "Indian Forest Service (IFS)*, State Forest Service, Forest Range Officer, Wildlife Department, Forest Department, Agricultural Departments, Fisheries Departments, Environmental Departments, government conservation organisations. UPSC's 2026 examination schedule included the Indian Forest Service examination." },
    { dimension: "Risk Orientation", question: "Am I comfortable making important decisions where outcomes may be uncertain?", courses: "MBBS, BDS, Pharmacy, Biotechnology, Healthcare Management, BBA, Entrepreneurship, Food Technology, Agriculture, Public Health, Hospital Administration", jobs: "Doctor, Clinical Researcher, Healthcare Entrepreneur, Pharma Entrepreneur, Hospital Manager, Biotech Entrepreneur, Healthcare Product Manager, Public Health Programme Manager", skills: "Decision Making, Risk Assessment, Ethics, Leadership, Crisis Management, Financial Literacy, Communication, Research, Project Management, Adaptability", salary: "₹3–10 LPA entry; ₹10–30+ LPA experienced; entrepreneurship has no fixed salary ceiling", govtJobs: "Medical Officer, Public Health administration, Disaster/Emergency health services, government healthcare management, Civil Services, State PSC, defence medical/health services and other public-sector healthcare pathways" },
    { dimension: "Work Environment", question: "Where would I prefer to work: hospital, laboratory, field, office, research centre or community?", courses: "Hospital → MBBS, BDS, Nursing, BPT, Pharmacy; Laboratory → Biotechnology, Microbiology, Biochemistry, MLT; Field → Agriculture, Forestry, Zoology, Environmental Science; Office → Healthcare Management, Public Health, Biotech Business; Research → Life Sciences, Genetics, Molecular Biology", jobs: "Doctor, Nurse, Dentist, Pharmacist, Lab Scientist, Microbiologist, Agricultural Scientist, Environmental Scientist, Researcher, Healthcare Manager, Public Health Professional", skills: "Hospital: Clinical Skills, Patient Care; Lab: Laboratory Techniques, Research; Field: Field Research, GIS; Office: Communication, Management, Analytics; Research: Scientific Writing, Data Analysis, Experimental Skills", salary: "₹3–10 LPA entry; ₹8–25 LPA mid-career; ₹20–60+ LPA senior/specialist, depending heavily on profession", govtJobs: "Hospital → Government hospitals/AIIMS/ESIC/Railways; Laboratory → ICMR/CSIR/DAE/State labs; Field → Forest/Agriculture/Wildlife/Fisheries; Research → CSIR/ICMR/DRDO/DBT institutions; Public Health → Central/State Health Departments" },
    { dimension: "Motivators", question: "What matters most to me: income, stability, service, prestige, research, independence or impact?", courses: "Income → Medicine, Dentistry, Pharmacy, Healthcare Management, Biotech; Stability → Nursing, Pharmacy, Government Healthcare, Public Health; Service → Medicine, Nursing, Physiotherapy, Public Health; Research → Biotechnology, Genetics, Microbiology, Life Sciences; Independence → Medicine/Private Practice, Pharmacy, Entrepreneurship; Impact → Public Health, Biotechnology, Environmental Science, Agriculture", jobs: "Doctor, Specialist, Dentist, Pharmacist, Nurse, Research Scientist, Biotechnologist, Public Health Professional, Healthcare Entrepreneur, Environmental Scientist, Agricultural Scientist", skills: "Domain Expertise, Leadership, Communication, Research, Entrepreneurship, Clinical/Technical Skills, Continuous Learning, Professional Ethics", salary: "₹3–15 LPA entry depending on field; ₹10–35 LPA mid-career; ₹20–60+ LPA senior/specialist. Private practice and entrepreneurship can vary significantly.", govtJobs: "Service → Government healthcare/Public Health; Stability → Nursing/Pharmacy/Government Health Services; Research → ICMR/CSIR/DRDO/DAE; Nature → Forest Service/Agriculture/Wildlife; Medical → CMS/Government Medical Officer; Administration → UPSC/State PSC" },
  ],
  "CEC": [
    { dimension: "Numerical & Financial Ability", question: "How comfortable am I with numbers, calculations, accounts and financial information?", courses: "B.Com, B.Com (Hons), B.Com Accounting & Finance, B.Com Banking & Insurance, B.Com Financial Markets, BBA Finance, B.Sc Finance, B.Sc Economics, B.Sc Economics & Mathematics, BBA FinTech, B.Stat where eligible", jobs: "Accountant, Financial Analyst, Investment Analyst, Credit Analyst, Banking Analyst, Financial Planner, Risk Analyst, Tax Associate, Audit Associate, Treasury Analyst", skills: "Accounting, Financial Analysis, Excel, Financial Modelling, Statistics, Financial Statements, Tax Basics, Tally/ERP, Power BI, Data Analysis, Critical Thinking", salary: "₹3–8 LPA entry; ₹8–20 LPA mid-career; ₹20–50+ LPA senior/specialist. Finance, investment and specialist roles can vary significantly by employer and qualification.", govtJobs: "RBI Grade B, NABARD Grade A, SEBI Grade A, SBI/IBPS PO, SBI/IBPS Clerk, RBI Assistant, LIC AAO, SSC CGL – Auditor/Accountant/AAO, Income Tax Inspector, GST/Customs roles, State PSC Finance/Accounts posts" },
    { dimension: "Logical Reasoning", question: "Do I enjoy analysing information, identifying patterns and solving business problems?", courses: "B.Com, B.Com (Hons), BBA Business Analytics, BBA, B.Sc Economics, B.Sc Statistics where eligible, B.Sc Data Science where eligibility permits, BMS, Economics & Mathematics", jobs: "Business Analyst, Financial Analyst, Data Analyst, Operations Analyst, Risk Analyst, Strategy Analyst, Management Consultant, Research Analyst", skills: "Analytical Thinking, Excel, SQL, Statistics, Business Analysis, Problem Solving, Power BI/Tableau, Financial Modelling, Research, Presentation", salary: "₹4–10 LPA entry; ₹10–25 LPA mid-career; ₹20–50+ LPA senior/specialist", govtJobs: "UPSC Civil Services, SSC CGL, SSC CHSL, Banking PO, RBI Grade B, NABARD Grade A, SEBI Grade A, Railway/other government analytical and administrative posts, State PSC examinations" },
    { dimension: "Business & Commercial Interest", question: "Do I enjoy understanding how businesses make money, compete and grow?", courses: "BBA, BMS, B.Com, B.Com (Hons), BBA Business Analytics, BBA Finance, BBA Marketing, BBA International Business, BBA Entrepreneurship, Integrated Management", jobs: "Business Analyst, Business Development Executive, Product Manager, Operations Manager, Marketing Manager, Strategy Analyst, Management Trainee, Consultant, Entrepreneur", skills: "Business Strategy, Market Research, Sales, Marketing, Financial Literacy, Communication, Negotiation, Presentation, Leadership, Project Management, CRM", salary: "₹3–8 LPA entry; ₹8–20 LPA mid-career; ₹20–50+ LPA senior. Consulting, product management and senior business roles may exceed these ranges.", govtJobs: "UPSC Civil Services, SSC CGL, RBI Grade B, SEBI Grade A, NABARD Grade A, public-sector bank PO, LIC AAO, PSU management/administrative recruitment, State PSC" },
    { dimension: "Economics Interest", question: "Do I enjoy understanding markets, inflation, employment, trade and economic behaviour?", courses: "B.A. Economics, B.Sc Economics, B.Sc Economics & Mathematics, B.A. Economics (Hons), B.Sc Economics (Hons), B.Com Economics-related programmes, Integrated M.Sc Economics", jobs: "Economist, Economic Analyst, Research Analyst, Market Analyst, Policy Researcher, Economic Consultant, Investment Analyst, Business Economist", skills: "Economics, Microeconomics, Macroeconomics, Econometrics, Statistics, Excel, R/Python, Data Analysis, Research, Report Writing, Critical Thinking", salary: "₹4–10 LPA entry; ₹8–25 LPA mid-career; ₹20–45+ LPA senior/specialist. Advanced economics roles often benefit from postgraduate qualifications.", govtJobs: "UPSC Indian Economic Service (IES)*, RBI Grade B/DEPR*, NABARD, NITI Aayog/central government economic roles, Ministry/Department economic posts, State PSC Economics posts, Statistical/Economic departments" },
    { dimension: "Accounting Interest", question: "Do I enjoy maintaining, analysing and understanding financial records?", courses: "B.Com, B.Com (Hons), B.Com Accounting & Finance, B.Com Professional, B.Com Banking & Insurance, B.Com Taxation, B.Com Corporate Accounting", jobs: "Accountant, Financial Accountant, Accounts Executive, Tax Associate, Audit Associate, Management Accountant, Financial Reporting Analyst, Accounts Manager", skills: "Accounting, Tally/ERP, Excel, GST basics, Financial Reporting, Auditing, Taxation, IFRS/Ind AS basics, Attention to Detail, Financial Analysis", salary: "₹3–7 LPA entry; ₹7–15 LPA mid-career; ₹15–30+ LPA senior. Professional qualifications can significantly change the career trajectory.", govtJobs: "SSC CGL – Auditor/Accountant/AAO, CAG-related posts, CGA/Accounts departments, State Treasury & Accounts departments, government Accountant/Auditor posts, PSU Accounts roles, municipal/local-government accounts posts" },
    { dimension: "People Orientation", question: "Do I enjoy communicating, negotiating, influencing and working with people?", courses: "BBA, BMS, B.Com, B.A. Economics, BJMC, BA LLB, BBA LLB, BSW, B.A. Psychology where eligible, Hotel Management, Integrated Management", jobs: "HR Executive, Recruiter, Sales Executive, Business Development Manager, Customer Success Manager, HR Manager, Corporate Relations Manager, Consultant, Communications Specialist", skills: "Communication, Public Speaking, Negotiation, Sales, Leadership, Emotional Intelligence, Networking, Presentation, Conflict Resolution, Relationship Management", salary: "₹3–7 LPA entry; ₹7–18 LPA mid-career; ₹15–35+ LPA senior", govtJobs: "UPSC Civil Services – IAS/IPS/other services, State PSC, SSC CGL – administrative roles, government HR/administration posts, public-sector bank officer, ESIC/EPFO-related recruitment, Railways administrative roles" },
    { dimension: "Communication & Language Ability", question: "Do I enjoy writing, speaking, presenting arguments and explaining ideas?", courses: "BJMC, BA Journalism, BA Mass Communication, BA English, BBA, B.A. Economics, BA LLB, BBA LLB, B.A. Public Relations, B.A. Advertising/Communication where offered", jobs: "Journalist, Content Strategist, Corporate Communications Executive, PR Executive, Copywriter, Media Planner, Communications Manager, Public Relations Manager, Legal Associate", skills: "Writing, Public Speaking, Storytelling, Research, Presentation, Digital Media, Content Strategy, SEO, Negotiation, Interviewing, Business Communication", salary: "₹3–7 LPA entry; ₹7–18 LPA mid-career; ₹15–35+ LPA senior. Media and independent careers can vary widely.", govtJobs: "Indian Information Service through UPSC CSE*, government media/information roles, PIB-related roles, Doordarshan/Prasar Bharati recruitment, SSC CGL Assistant Section Officer and communication-heavy government posts, State Information/Public Relations departments" },
    { dimension: "Legal & Civic Interest", question: "Do I enjoy understanding laws, government, rights, institutions and how society is governed?", courses: "BA LLB, BBA LLB, B.Com LLB where offered, B.A. Political Science, B.A. Public Administration, B.A. Economics, B.A. International Relations where offered, integrated law programmes", jobs: "Lawyer, Legal Associate, Corporate Legal Executive, Compliance Analyst, Legal Researcher, Policy Researcher, Public Affairs Analyst, Regulatory Affairs Professional", skills: "Legal Research, Legal Writing, Case Analysis, Communication, Argumentation, Negotiation, Critical Thinking, Policy Analysis, Documentation", salary: "₹3–8 LPA entry; ₹8–25 LPA mid-career; ₹20–50+ LPA senior. Corporate law and specialized legal careers can have substantially different compensation.", govtJobs: "Judicial Services*, Assistant Public Prosecutor*, Government Pleader/Legal Officer*, UPSC/State PSC, Legal Officer recruitment in PSUs/banks, Law Officer roles in government institutions, regulatory bodies" },
    { dimension: "Public Policy & Governance Interest", question: "Do I want to understand how governments, institutions and public policies affect society?", courses: "BA Political Science, BA Public Administration, BA Economics, BA International Relations, BA Development Studies, BA Public Policy where offered, Integrated Management/Public Policy programmes", jobs: "Policy Analyst, Research Associate, Public Affairs Analyst, Governance Consultant, Development Professional, Programme Manager, Policy Researcher", skills: "Policy Research, Data Analysis, Report Writing, Economics, Statistics, Research Methodology, Communication, Stakeholder Management, Presentation", salary: "₹3–8 LPA entry; ₹7–18 LPA mid-career; ₹15–35+ LPA senior/specialist. Government and development-sector compensation follows different structures.", govtJobs: "UPSC Civil Services, State PSC, Indian Administrative Service, Indian Revenue Service, Indian Audit & Accounts Service, Indian Information Service, government administrative departments, public-sector regulatory/administrative roles" },
    { dimension: "Research Orientation", question: "Do I enjoy studying markets, society, economics, business or public issues deeply?", courses: "BA/BS Economics, B.Com (Hons), BBA, B.A. Political Science, B.A. Public Administration, B.A. Sociology where eligible, B.Sc Economics, Research-oriented bachelor's programmes", jobs: "Research Analyst, Economic Researcher, Market Research Analyst, Policy Researcher, Business Research Analyst, Social Researcher, Academic Researcher", skills: "Research Methodology, Statistics, Data Collection, Literature Review, Excel, R/Python, Survey Design, Report Writing, Data Interpretation, Academic Writing", salary: "₹3–8 LPA entry; ₹7–18 LPA mid-career; ₹15–35+ LPA specialist. Research-heavy academic roles generally require postgraduate study.", govtJobs: "UPSC research/economic/statistical services where eligible, government research institutes, Indian Economic Service*, Indian Statistical Service*, Ministry/department research posts, CSIR/ICSSR-related opportunities, State government research/statistical departments" },
    { dimension: "Entrepreneurial Orientation", question: "Do I enjoy creating businesses, taking decisions and turning ideas into opportunities?", courses: "BBA Entrepreneurship, BBA, BMS, B.Com, BBA Innovation & Entrepreneurship, BBA Marketing, BBA Finance, Integrated Management, Economics", jobs: "Entrepreneur, Startup Founder, Business Development Manager, Product Manager, Growth Manager, Business Strategist, Startup Operations Manager, Franchise Owner", skills: "Entrepreneurship, Sales, Market Research, Financial Management, Product Development, Digital Marketing, Leadership, Negotiation, Networking, Pitching, Risk Management", salary: "Salaried roles: ₹3–10 LPA entry; ₹8–25+ LPA experienced. Entrepreneurial income has no predictable salary range and depends on business performance.", govtJobs: "Government entrepreneurship ecosystem roles, MSME-related government programmes, Startup/Innovation missions, SIDBI-related opportunities, public-sector management roles, UPSC/State PSC administration" },
    { dimension: "Risk & Decision-Making", question: "Am I comfortable making decisions when information is incomplete and outcomes are uncertain?", courses: "BBA Finance, B.Com, B.Sc Economics, BBA FinTech, BBA Business Analytics, B.Sc Statistics where eligible, BBA Entrepreneurship, BMS, Economics & Mathematics", jobs: "Risk Analyst, Credit Analyst, Investment Analyst, Business Strategist, Financial Analyst, Portfolio Analyst, Insurance Analyst, FinTech Analyst", skills: "Risk Analysis, Financial Modelling, Statistics, Probability, Decision Making, Excel, SQL, Data Analysis, Financial Markets, Critical Thinking", salary: "₹4–10 LPA entry; ₹10–25 LPA mid-career; ₹20–50+ LPA senior/specialist", govtJobs: "RBI Grade B, SEBI Grade A, NABARD Grade A, IRDAI Assistant Manager*, PFRDA Grade A*, public-sector bank PO, LIC AAO, General Insurance recruitment, SSC CGL financial/regulatory roles" },
    { dimension: "Work Environment", question: "Where would I prefer to work: corporate office, bank, finance, court, government, startup, research or public-facing environment?", courses: "Corporate → BBA/BMS/B.Com; Banking → B.Com/Finance/Economics; Law → BA LLB/BBA LLB; Government/Policy → Political Science/Public Administration/Economics; Startup → BBA Entrepreneurship; Research → Economics/Commerce/Political Science", jobs: "Business Analyst, Banker, Financial Analyst, Lawyer, Policy Analyst, Management Consultant, Entrepreneur, HR Professional, Research Analyst, Corporate Manager", skills: "Corporate: Business & Communication; Banking: Finance & Analysis; Law: Legal Research; Policy: Research & Data; Startup: Entrepreneurship & Sales; Research: Statistics & Academic Writing", salary: "₹3–10 LPA entry; ₹8–25 LPA mid-career; ₹20–50+ LPA senior/specialist, depending on career and sector", govtJobs: "UPSC Civil Services, State PSC, SSC CGL, Banking exams, RBI, SEBI, NABARD, LIC, Railways, government ministries/departments, PSU recruitment, judicial services after LLB" },
    { dimension: "Motivators", question: "What matters most to me: income, stability, leadership, influence, independence, public service or entrepreneurship?", courses: "Income → Finance, Economics, Business Analytics, Consulting; Stability → Accounting, Banking, Government, Compliance; Leadership → BBA, BMS, Integrated Management; Influence → Law, Public Affairs, Communications; Independence → Entrepreneurship, Finance, Consulting; Public Service → Political Science, Public Administration, Economics, Law", jobs: "Financial Analyst, Consultant, Manager, Lawyer, Economist, Entrepreneur, Policy Analyst, Banker, HR Manager, Business Strategist, Public Affairs Professional", skills: "Leadership, Communication, Financial Literacy, Data Analysis, Strategy, Negotiation, Research, Problem Solving, Networking, Decision Making, Project Management", salary: "₹3–10 LPA entry depending on field; ₹8–25 LPA mid-career; ₹20–50+ LPA senior/specialist. Senior finance, consulting, management and specialized legal roles can exceed these ranges.", govtJobs: "Public Service → UPSC/State PSC; Financial Stability → Banking/RBI/NABARD/SEBI/LIC; Administration → UPSC/SSC CGL/State PSC; Law → Judicial Services/Legal Officer; Economics → IES/Indian Statistical Service where eligible; Defence → NDA/other eligible pathways" },
  ],
};

// Proxy formulas mapping each dimension name to a 0-100 score derived from
// the student's actual measured profile (PsychometricProfile) — this is
// what makes the selection "based on their responses" rather than a fixed
// per-stream default. Not every dimension has a genuine measurable proxy in
// this app's profile (Risk Orientation, Work Environment and Motivators
// have no corresponding scored field) — those are left out of `proxyScore`
// on purpose rather than guessed at, so they're never picked, though they
// stay in DIMENSION_GUIDE in case a future dimension gets added.
function riasecPct(l1: PsychometricProfile, code: string): number {
  return l1.riasec.find((r) => r.code === code)?.percentile ?? 0;
}
function strengthPct(l1: PsychometricProfile, domain: string): number {
  const d = l1.strengthDomains.find((s) => s.domain === domain);
  return d ? Math.max(0, Math.min(100, (d.score / 5) * 100)) : 0;
}

const PROXY: Record<string, (l1: PsychometricProfile) => number> = {
  "Mathematical Ability": (l1) => l1.aptitude.numerical.score,
  "Numerical & Financial Ability": (l1) => l1.aptitude.numerical.score,
  "Logical Reasoning": (l1) => l1.aptitude.logical.score,
  "Coding Interest": (l1) => (l1.aptitude.logical.score + riasecPct(l1, "I")) / 2,
  "Scientific Interest": (l1) => riasecPct(l1, "I"),
  "Spatial Ability": (l1) => l1.aptitude.spatial.score,
  "Creativity": (l1) => Math.max(0, Math.min(100, (l1.creativity.score / 5) * 100)),
  "People Orientation": (l1) => riasecPct(l1, "S"),
  "Business Orientation": (l1) => riasecPct(l1, "E"),
  "Business & Commercial Interest": (l1) => riasecPct(l1, "E"),
  "Research Orientation": (l1) => (riasecPct(l1, "I") + strengthPct(l1, "Intrapersonal")) / 2,
  "Medical / Healthcare Interest": (l1) => (riasecPct(l1, "I") + riasecPct(l1, "S")) / 2,
  "Environmental / Nature Interest": (l1) => strengthPct(l1, "Naturalistic") || riasecPct(l1, "I"),
  "Accounting Interest": (l1) => (l1.aptitude.numerical.score + riasecPct(l1, "C")) / 2,
  "Economics Interest": (l1) => (l1.aptitude.numerical.score + riasecPct(l1, "I")) / 2,
  "Communication & Language Ability": (l1) => l1.aptitude.verbal.score,
  "Legal & Civic Interest": (l1) => (l1.aptitude.verbal.score + riasecPct(l1, "S")) / 2,
  "Public Policy & Governance Interest": (l1) => (riasecPct(l1, "S") + riasecPct(l1, "E")) / 2,
  "Entrepreneurial Orientation": (l1) => riasecPct(l1, "E"),
};

export interface ScoredDimension extends DimensionEntry {
  score: number;
}

/** Top N dimensions (by proxy score) from the student's stream group — the "based on your specific strengths" picks. */
export function topDimensionsForStudent(streamKey: StreamKey1112, l1: PsychometricProfile, count = 3): ScoredDimension[] {
  const group = streamGroupFor(streamKey);
  if (!group) return [];
  const entries = DIMENSION_GUIDE[group];
  const scored = entries
    .filter((e) => PROXY[e.dimension])
    .map((e) => ({ ...e, score: Math.round(PROXY[e.dimension](l1)) }));
  return scored.sort((a, b) => b.score - a.score).slice(0, count);
}
