#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Career catalogue, part 3: design, media, humanities, education, hospitality.

Same contract as part 1 - see demo_11_12_careers_stem.py for the field meanings.
"""

CAREERS_CREATIVE = [
    # ---------------------------------------------------------------- DESIGN
    {
        "id": "ux-designer", "title": "UX / Product Designer", "cluster": "D", "family": "design",
        "degrees": ["UX/UI Design", "B.Des", "Product Design", "Communication Design", "B.Tech Computer Science", "BFA"],
        "blurb": "Designs how digital products work and feel, so people can actually use them.",
        "whatYouDo": ["Research how users behave, not how they say they behave",
                      "Design flows, wireframes and interfaces",
                      "Prototype and test with real users",
                      "Work with engineers on what is buildable"],
        "dayInLife": "User interviews, Figma, a design critique, and an engineering conversation about trade-offs.",
        "coreSkills": ["Figma", "Interaction and visual design", "User research", "Information architecture",
                       "Explaining why a design decision was made"],
        "buildNow": ["Redesign an app you find frustrating and write up the reasoning - that is a case study",
                     "Learn Figma; it is free for students and it is the industry standard",
                     "Build a portfolio of 3-4 deep case studies rather than many shallow screens"],
        "salary": {"entry": "Rs 5-15 LPA", "mid": "Rs 15-40 LPA", "senior": "Rs 40 LPA-1.5 Cr+"},
        "alternates": ["product-designer", "graphic-designer", "product-manager", "software-engineer"],
    },
    {
        "id": "product-designer", "title": "Industrial / Product Designer", "cluster": "D", "family": "design",
        "degrees": ["Product Design", "B.Des", "B.Tech Mechanical", "BFA", "Interior Design"],
        "blurb": "Designs physical products - how they look, feel, work and get manufactured.",
        "whatYouDo": ["Sketch and model concepts in CAD",
                      "Prototype and test ergonomics",
                      "Choose materials and manufacturing methods",
                      "Balance beauty, cost and manufacturability"],
        "dayInLife": "Sketching, 3D modelling, foam and printed prototypes, and a factory conversation.",
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-30 LPA", "senior": "Rs 30-75 LPA+"},
        "alternates": ["ux-designer", "mechanical-engineer", "interior-designer", "graphic-designer"],
    },
    {
        "id": "graphic-designer", "title": "Graphic / Communication Designer", "cluster": "D", "family": "design",
        "degrees": ["Communication Design", "B.Des", "BFA", "UX/UI Design", "Advertising & Brand Communication"],
        "blurb": "Communicates ideas visually - identity, publications, packaging, campaigns.",
        "whatYouDo": ["Develop visual identity and design systems",
                      "Design across print and digital",
                      "Work to a brief and to brand rules",
                      "Present and defend creative choices"],
        "dayInLife": "Concepts in the morning, execution in the afternoon, and revisions after feedback.",
        "salary": {"entry": "Rs 3-9 LPA", "mid": "Rs 9-24 LPA", "senior": "Rs 24-60 LPA+ (freelance uncapped)"},
        "alternates": ["ux-designer", "animator", "art-director", "illustrator"],
    },
    {
        "id": "fashion-designer", "title": "Fashion Designer", "cluster": "D", "family": "design",
        "degrees": ["Fashion Design", "B.Des", "BFA"],
        "blurb": "Designs clothing and accessories, from concept through to production.",
        "whatYouDo": ["Research trends and develop collections",
                      "Sketch, drape and produce technical patterns",
                      "Select fabrics and work with mills and karigars",
                      "Oversee sampling and production quality"],
        "dayInLife": "Sketching and fabric sourcing, fittings, and production follow-up before a show or drop.",
        "entranceExams": [
            {"name": "NIFT Entrance", "when": "Class 12, Feb", "opens": "National Institute of Fashion Technology"},
            {"name": "NID DAT", "when": "Class 12, Dec-Jan", "opens": "NID textile and fashion programmes"},
            {"name": "Pearl Academy / Symbiosis entrance", "when": "Class 12", "opens": "Private design schools"},
        ],
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-22 LPA", "senior": "Rs 22-70 LPA+ (own label uncapped and risky)"},
        "realityCheck": "Glamorous from outside, and mostly technical and commercial from inside. Early years in a design studio pay modestly.",
        "alternates": ["textile-designer", "graphic-designer", "product-designer", "art-director"],
    },
    {
        "id": "interior-designer", "title": "Interior Designer", "cluster": "D", "family": "design",
        "degrees": ["Interior Design", "B.Des", "B.Arch", "BFA"],
        "blurb": "Designs interior spaces so they work well and feel right.",
        "whatYouDo": ["Plan spatial layouts and circulation",
                      "Select materials, lighting and furniture",
                      "Produce drawings for contractors",
                      "Manage site execution and budget"],
        "dayInLife": "Client meetings, drawings and 3D views, material sourcing, and site supervision.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-22 LPA", "senior": "Rs 22-60 LPA+ (own studio)"},
        "alternates": ["architect", "product-designer", "art-director", "graphic-designer"],
    },
    {
        "id": "textile-designer", "title": "Textile Designer", "cluster": "D", "family": "design",
        "degrees": ["Fashion Design", "B.Des", "BFA"],
        "blurb": "Designs fabrics - weave, print, surface and colour.",
        "whatYouDo": ["Develop prints, weaves and surface treatments",
                      "Work with mills, dyers and craft clusters",
                      "Build seasonal colour and material stories",
                      "Balance craft technique with production reality"],
        "dayInLife": "Studio design work, mill visits, and sampling until the hand-feel is right.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-45 LPA+"},
        "alternates": ["fashion-designer", "graphic-designer", "product-designer"],
    },
    {
        "id": "animator", "title": "Animator", "cluster": "D", "family": "design",
        "degrees": ["Animation", "B.Des", "BFA", "Film & Television", "VFX"],
        "blurb": "Brings characters and worlds to life frame by frame, in 2D or 3D.",
        "whatYouDo": ["Design and rig characters",
                      "Animate performance, timing and weight",
                      "Work within a studio pipeline",
                      "Iterate to a director's notes"],
        "dayInLife": "Long focused hours on short sequences - a few seconds a day is normal and expected.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-22 LPA", "senior": "Rs 22-60 LPA+"},
        "buildNow": ["Animate something every week, even a bouncing ball done properly",
                     "Learn Blender - free, industry-capable, and enough for a portfolio",
                     "Study movement in real life; animation is observation before software"],
        "alternates": ["vfx-artist", "game-developer", "graphic-designer", "filmmaker"],
    },
    {
        "id": "vfx-artist", "title": "VFX Artist", "cluster": "D", "family": "design",
        "degrees": ["VFX", "Animation", "B.Des", "Film & Television", "BFA"],
        "blurb": "Creates and integrates effects that have to look like they were really filmed.",
        "whatYouDo": ["Composite CG elements into live footage",
                      "Build simulations - fire, water, destruction",
                      "Match lighting, grain and camera movement",
                      "Deliver shots to a hard release deadline"],
        "dayInLife": "Shot work in Nuke or Houdini, dailies review, and revisions until it is invisible.",
        "salary": {"entry": "Rs 3-9 LPA", "mid": "Rs 9-25 LPA", "senior": "Rs 25-70 LPA+"},
        "realityCheck": "India is a major global VFX hub, so work is plentiful, but much of it is service work on other people's projects with deadline-driven crunch.",
        "alternates": ["animator", "game-developer", "filmmaker", "photographer"],
    },
    {
        "id": "art-director", "title": "Art Director", "cluster": "D", "family": "media",
        "degrees": ["Advertising", "Advertising & Brand Communication", "Communication Design", "B.Des", "BFA", "Mass Communication"],
        "blurb": "Owns the visual idea of a campaign, publication or production.",
        "whatYouDo": ["Develop the visual concept behind a campaign",
                      "Direct photographers, designers and illustrators",
                      "Maintain a consistent visual voice",
                      "Sell the idea to clients"],
        "dayInLife": "Concept development, a shoot or design review, and a client presentation.",
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-32 LPA", "senior": "Rs 32-90 LPA+"},
        "alternates": ["graphic-designer", "advertising-professional", "filmmaker", "brand-manager"],
    },
    {
        "id": "illustrator", "title": "Illustrator", "cluster": "D", "family": "design",
        "degrees": ["BFA", "B.Des", "Communication Design", "Animation"],
        "blurb": "Draws for publishing, editorial, advertising, games and children's books.",
        "whatYouDo": ["Interpret a brief into original imagery",
                      "Develop a recognisable personal style",
                      "Work to format and print requirements",
                      "Manage clients and licensing, mostly freelance"],
        "dayInLife": "Drawing, client revisions, and running your own small business alongside.",
        "salary": {"entry": "Rs 2.5-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-50 LPA+ (reputation-driven)"},
        "alternates": ["graphic-designer", "animator", "artist", "content-creator"],
    },
    {
        "id": "artist", "title": "Fine Artist", "cluster": "D", "family": "design",
        "degrees": ["BFA", "B.Des"],
        "blurb": "Makes original work - painting, sculpture, print, installation - and exhibits it.",
        "whatYouDo": ["Develop a sustained body of work and a point of view",
                      "Exhibit through galleries, fairs and residencies",
                      "Apply for grants and residencies",
                      "Often teach or take commissions alongside"],
        "dayInLife": "Studio time, and the business of getting work seen.",
        "salary": {"entry": "Highly variable, often supplemented", "mid": "Rs 5-20 LPA", "senior": "Rs 20 LPA-uncapped"},
        "realityCheck": "Income is genuinely unpredictable and most working artists teach or freelance alongside. Choose it with that arrangement planned, not hoped for.",
        "alternates": ["illustrator", "teacher", "graphic-designer", "curator"],
    },
    # ------------------------------------------------------------------ MEDIA
    {
        "id": "journalist", "title": "Journalist", "cluster": "D", "family": "media",
        "degrees": ["BA Journalism", "Journalism", "BA Mass Communication", "Mass Communication", "BA English",
                    "BA Political Science", "Broadcasting"],
        "blurb": "Finds out what is happening and reports it accurately, including when it is inconvenient.",
        "whatYouDo": ["Develop sources and verify information",
                      "Report and write to deadline",
                      "Investigate stories that take months",
                      "Stand behind what you published"],
        "dayInLife": "Calls, a field visit, and filing copy against a deadline that does not move.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-20 LPA", "senior": "Rs 20-60 LPA+"},
        "realityCheck": "Pay is modest relative to the skill and hours, and the industry is under commercial pressure. Independent and newsletter journalism is changing that for some.",
        "alternates": ["content-creator", "editor", "public-relations-specialist", "policy-analyst"],
    },
    {
        "id": "editor", "title": "Editor / Content Strategist", "cluster": "D", "family": "media",
        "degrees": ["BA English", "BA Journalism", "Journalism", "BA Mass Communication", "Content Creation", "BA Linguistics"],
        "blurb": "Shapes what gets published and makes writing sharper before it goes out.",
        "whatYouDo": ["Commission and plan content",
                      "Edit for structure, accuracy and voice",
                      "Manage writers and schedules",
                      "Own the standard everything is held to"],
        "dayInLife": "Editing, commissioning conversations, and an editorial calendar.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-22 LPA", "senior": "Rs 22-60 LPA+"},
        "alternates": ["journalist", "content-creator", "digital-marketer", "author"],
    },
    {
        "id": "filmmaker", "title": "Filmmaker / Director", "cluster": "D", "family": "media",
        "degrees": ["Film & Television", "BA Mass Communication", "Mass Communication", "B.Des", "Broadcasting", "BFA"],
        "blurb": "Makes films - fiction, documentary or commercial - and takes the creative decisions.",
        "whatYouDo": ["Develop the script and visual approach",
                      "Cast, plan and direct the shoot",
                      "Work with editor, sound and music in post",
                      "Raise money and get the film seen"],
        "dayInLife": "Very uneven - months of development and funding, then intense weeks of production.",
        "topColleges": ["FTII Pune", "SRFTI Kolkata", "Whistling Woods Mumbai", "Jamia (AJK MCRC)", "NID Ahmedabad"],
        "salary": {"entry": "Project-based, often minimal", "mid": "Rs 8-30 LPA", "senior": "Rs 30 LPA-uncapped"},
        "realityCheck": "Income is project-based and irregular, especially early. Most directors spent years as assistants first, and that apprenticeship is how the craft is actually learned.",
        "alternates": ["cinematographer", "editor", "content-creator", "animator"],
    },
    {
        "id": "cinematographer", "title": "Cinematographer", "cluster": "D", "family": "media",
        "degrees": ["Film & Television", "Photography", "Mass Communication", "B.Des", "BFA"],
        "blurb": "Decides how a film looks - camera, lens, lighting and movement.",
        "whatYouDo": ["Design the visual language with the director",
                      "Light scenes to create mood",
                      "Operate or lead the camera team",
                      "Supervise colour grading"],
        "dayInLife": "On a shoot, twelve-hour days built around light. Between shoots, prep and testing.",
        "salary": {"entry": "Project-based, Rs 3-8 LPA equivalent", "mid": "Rs 8-30 LPA", "senior": "Rs 30 LPA-uncapped"},
        "alternates": ["photographer", "filmmaker", "vfx-artist", "content-creator"],
    },
    {
        "id": "photographer", "title": "Photographer", "cluster": "D", "family": "media",
        "degrees": ["Photography", "Film & Television", "Mass Communication", "BFA", "B.Des"],
        "blurb": "Makes images for editorial, commercial, documentary or event work.",
        "whatYouDo": ["Plan and light shoots",
                      "Shoot to a brief, or to your own project",
                      "Edit and retouch",
                      "Find and keep clients"],
        "dayInLife": "A shoot, then hours of selection and editing, then invoicing.",
        "salary": {"entry": "Rs 2.5-7 LPA", "mid": "Rs 7-20 LPA", "senior": "Rs 20-60 LPA+ (reputation-driven)"},
        "alternates": ["cinematographer", "content-creator", "journalist", "illustrator"],
    },
    {
        "id": "content-creator", "title": "Content Creator / Digital Storyteller", "cluster": "D", "family": "media",
        "degrees": ["Content Creation", "Digital Media", "Mass Communication", "BA Journalism", "Advertising", "Media Management"],
        "blurb": "Builds an audience directly and makes a living from attention.",
        "whatYouDo": ["Develop a distinct voice and format",
                      "Write, shoot and edit consistently",
                      "Grow and hold an audience",
                      "Monetise via brands, subscriptions or products"],
        "dayInLife": "Scripting, filming, editing, and reading analytics to decide what to make next.",
        "buildNow": ["Publish weekly starting now - the archive is the asset and consistency beats quality early",
                     "Learn video editing properly",
                     "Study which of your posts worked and why, rather than guessing"],
        "salary": {"entry": "Often near zero for 1-2 years", "mid": "Rs 6-25 LPA", "senior": "Rs 25 LPA-uncapped"},
        "realityCheck": "The top of this field is extremely visible and extremely unrepresentative. Most creators earn little; the ones who succeed usually published for years before it worked.",
        "alternates": ["digital-marketer", "journalist", "filmmaker", "editor"],
    },
    {
        "id": "public-relations-specialist", "title": "Public Relations Specialist", "cluster": "E", "family": "media",
        "degrees": ["Public Relations", "Mass Communication", "BA Mass Communication", "Advertising",
                    "BA Journalism", "Media Management", "BBA"],
        "blurb": "Manages how an organisation is perceived, especially when something goes wrong.",
        "whatYouDo": ["Build relationships with media and stakeholders",
                      "Write releases, statements and briefing notes",
                      "Manage crisis communication",
                      "Position spokespeople and shape narrative"],
        "dayInLife": "Media calls, a statement to draft quickly, and an event to run.",
        "salary": {"entry": "Rs 3-9 LPA", "mid": "Rs 9-25 LPA", "senior": "Rs 25-70 LPA+"},
        "alternates": ["journalist", "brand-manager", "marketing-manager", "advertising-professional"],
    },
    {
        "id": "advertising-professional", "title": "Advertising Professional", "cluster": "E", "family": "media",
        "degrees": ["Advertising", "Advertising & Brand Communication", "Mass Communication", "BA Mass Communication", "BBA", "Digital Media"],
        "blurb": "Creates the campaigns that make people notice and remember a brand.",
        "whatYouDo": ["Interpret a client brief into a creative idea",
                      "Write copy or develop the art direction",
                      "Plan media and channel strategy",
                      "Present and sell the work"],
        "dayInLife": "Brainstorming, a client presentation, and a pitch weekend before a deadline.",
        "salary": {"entry": "Rs 3-10 LPA", "mid": "Rs 10-30 LPA", "senior": "Rs 30-90 LPA+"},
        "alternates": ["brand-manager", "art-director", "digital-marketer", "public-relations-specialist"],
    },
    {
        "id": "media-manager", "title": "Media / Broadcast Manager", "cluster": "E", "family": "media",
        "degrees": ["Media Management", "Broadcasting", "Mass Communication", "BA Mass Communication", "BBA", "Digital Media"],
        "blurb": "Runs the business and operations of a media organisation or channel.",
        "whatYouDo": ["Plan programming and scheduling",
                      "Manage budgets, rights and distribution",
                      "Lead production and technical teams",
                      "Grow audience and revenue"],
        "dayInLife": "Ratings review, a commissioning decision, and an operational problem mid-broadcast.",
        "salary": {"entry": "Rs 4-10 LPA", "mid": "Rs 10-28 LPA", "senior": "Rs 28-80 LPA+"},
        "alternates": ["filmmaker", "brand-manager", "operations-manager", "advertising-professional"],
    },
    # ------------------------------------------------------------ HUMANITIES
    {
        "id": "psychologist", "title": "Psychologist / Counsellor", "cluster": "F", "family": "humanities",
        "degrees": ["BA Psychology", "B.Sc Psychology"],
        "blurb": "Assesses and treats psychological difficulty, or studies behaviour scientifically.",
        "whatYouDo": ["Assess and diagnose using structured tools",
                      "Deliver therapy across sessions",
                      "Work with families, schools or organisations",
                      "Keep detailed, confidential clinical records"],
        "dayInLife": "A handful of client sessions - deliberately few, because the work is intense - plus notes and supervision.",
        "afterSchool": [
            {"stage": "BA/B.Sc Psychology", "years": "3 years", "what": "General grounding, plus statistics and research methods"},
            {"stage": "MA/M.Sc Psychology", "years": "2 years", "what": "Clinical, counselling, organisational or research specialisation"},
            {"stage": "M.Phil / PsyD or RCI registration", "years": "+2 years", "what": "Required to practise clinically in India"},
        ],
        "topColleges": ["NIMHANS Bengaluru", "TISS Mumbai", "Christ University", "Delhi University", "Ambedkar University Delhi"],
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-20 LPA", "senior": "Rs 20-60 LPA+ (private practice highest)"},
        "realityCheck": "Clinical practice in India requires RCI registration via an M.Phil or equivalent - a bachelor's alone does not let you practise. Plan for 6-7 years.",
        "alternates": ["psychiatrist", "hr-manager", "social-worker", "special-educator", "ux-designer"],
    },
    {
        "id": "psychiatrist", "title": "Psychiatrist", "cluster": "C", "family": "medical",
        "degrees": ["MBBS"],
        "blurb": "A medical doctor specialising in mental illness, able to prescribe and treat medically.",
        "whatYouDo": ["Diagnose psychiatric conditions medically",
                      "Prescribe and monitor medication",
                      "Combine pharmacological and psychological treatment",
                      "Manage acute crisis and inpatient care"],
        "dayInLife": "Outpatient consultations, ward work, and long-term patient relationships.",
        "salary": {"entry": "Rs 8-15 LPA", "mid": "Rs 15-40 LPA", "senior": "Rs 40 LPA-1.5 Cr+"},
        "alternates": ["doctor", "psychologist", "medical-researcher"],
    },
    {
        "id": "teacher", "title": "School Teacher", "cluster": "F", "family": "humanities",
        "degrees": ["BA English", "BA History", "BA Political Science", "BA Geography", "B.Sc Physics",
                    "B.Sc Chemistry", "B.Sc Mathematics", "BA Sociology", "BA Economics", "B.Sc Psychology"],
        "blurb": "Teaches a subject, and shapes how students think about it.",
        "whatYouDo": ["Plan and deliver lessons",
                      "Assess and give feedback that helps",
                      "Manage a classroom of very different learners",
                      "Work with parents and colleagues"],
        "dayInLife": "Teaching periods, preparation, marking, and pastoral conversations.",
        "afterSchool": [
            {"stage": "Bachelor's in your subject", "years": "3 years", "what": "Or a 4-year integrated B.A. B.Ed"},
            {"stage": "B.Ed", "years": "2 years", "what": "Required for most school teaching posts"},
            {"stage": "CTET / State TET", "years": "After B.Ed", "what": "Mandatory for government school appointment"},
        ],
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-15 LPA", "senior": "Rs 15-35 LPA+ (international schools higher)"},
        "alternates": ["professor", "special-educator", "professor", "content-creator"],
    },
    {
        "id": "professor", "title": "Professor / Academic", "cluster": "F", "family": "humanities",
        "degrees": ["BA English", "BA History", "BA Economics", "B.Sc Physics", "B.Sc Mathematics",
                    "BA Political Science", "BA Philosophy", "B.Sc Chemistry", "BA Sociology"],
        "blurb": "Teaches at university level and produces original research.",
        "whatYouDo": ["Teach and supervise students",
                      "Conduct and publish research",
                      "Win grants and build a research group",
                      "Serve on academic committees"],
        "dayInLife": "Teaching, writing, supervision, and administration that expands to fill any gap.",
        "afterSchool": [
            {"stage": "Bachelor's and Master's", "years": "5 years", "what": "In your discipline"},
            {"stage": "UGC-NET / JRF", "years": "After Master's", "what": "Qualifies you to lecture and to receive a research fellowship"},
            {"stage": "PhD", "years": "4-6 years", "what": "Required for a permanent academic post"},
        ],
        "salary": {"entry": "Rs 6-12 LPA (Assistant Professor)", "mid": "Rs 12-22 LPA", "senior": "Rs 22-40 LPA+"},
        "realityCheck": "Roughly a decade from class 12 to a permanent post, and posts are scarce in some disciplines. Intellectual freedom and job security once tenured are the genuine rewards.",
        "alternates": ["research-scientist", "teacher", "policy-analyst", "author"],
    },
    {
        "id": "special-educator", "title": "Special Educator", "cluster": "F", "family": "humanities",
        "degrees": ["BA Psychology", "B.Sc Psychology", "BA Sociology", "Occupational Therapy"],
        "blurb": "Teaches children with learning differences and disabilities.",
        "whatYouDo": ["Assess individual learning needs",
                      "Build individualised education plans",
                      "Adapt teaching and materials",
                      "Work closely with families and therapists"],
        "dayInLife": "Small-group and one-to-one teaching, plan reviews, and parent meetings.",
        "salary": {"entry": "Rs 3-6 LPA", "mid": "Rs 6-14 LPA", "senior": "Rs 14-35 LPA+"},
        "alternates": ["psychologist", "occupational-therapist", "teacher", "social-worker"],
    },
    {
        "id": "historian", "title": "Historian / Archivist", "cluster": "F", "family": "humanities",
        "degrees": ["BA History", "BA Anthropology", "BA Philosophy", "BA Political Science"],
        "blurb": "Researches and interprets the past from primary sources, and preserves the record.",
        "whatYouDo": ["Work with archives and primary documents",
                      "Build evidenced historical arguments",
                      "Publish, curate or teach",
                      "Preserve and catalogue collections"],
        "dayInLife": "Archives, reading, and writing that takes years to complete.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-40 LPA+"},
        "alternates": ["professor", "curator", "journalist", "policy-analyst"],
    },
    {
        "id": "curator", "title": "Museum Curator / Arts Manager", "cluster": "D", "family": "humanities",
        "degrees": ["BA History", "BFA", "BA Anthropology", "BA English", "B.Des"],
        "blurb": "Builds and interprets collections, and puts exhibitions together.",
        "whatYouDo": ["Research and acquire works for a collection",
                      "Design exhibitions and their narrative",
                      "Write catalogues and interpretation",
                      "Manage conservation and loans"],
        "dayInLife": "Collection research, exhibition planning, and a great deal of logistics.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-45 LPA+"},
        "alternates": ["historian", "artist", "media-manager", "professor"],
    },
    {
        "id": "author", "title": "Author / Writer", "cluster": "D", "family": "humanities",
        "degrees": ["BA English", "BA Journalism", "BA Linguistics", "BA Philosophy", "Content Creation", "BA History"],
        "blurb": "Writes books, screenplays or long-form work for publication.",
        "whatYouDo": ["Write consistently, mostly alone",
                      "Revise heavily and take editorial notes",
                      "Find an agent or publisher",
                      "Usually earn from adjacent work as well"],
        "dayInLife": "Writing hours protected against everything else, and the business of publishing around them.",
        "salary": {"entry": "Rarely a full income initially", "mid": "Rs 4-15 LPA", "senior": "Rs 15 LPA-uncapped"},
        "realityCheck": "Very few writers in India live on book income alone. Nearly all combine it with teaching, journalism, screenwriting or content work - and that is the normal arrangement, not a failure.",
        "alternates": ["editor", "journalist", "content-creator", "professor"],
    },
    {
        "id": "linguist", "title": "Linguist / Language Specialist", "cluster": "F", "family": "humanities",
        "degrees": ["BA Linguistics", "BA English", "BA Anthropology"],
        "blurb": "Studies how language works, applied to translation, technology and documentation.",
        "whatYouDo": ["Analyse phonetics, syntax and semantics",
                      "Document endangered languages",
                      "Build language data for speech and translation systems",
                      "Translate and localise"],
        "dayInLife": "Fieldwork or corpus analysis, and increasingly work alongside NLP engineers.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-22 LPA", "senior": "Rs 22-60 LPA+ (tech NLP roles highest)"},
        "alternates": ["ai-ml-engineer", "professor", "editor", "anthropologist"],
    },
    {
        "id": "anthropologist", "title": "Anthropologist / Sociologist", "cluster": "F", "family": "humanities",
        "degrees": ["BA Anthropology", "BA Sociology", "BA History", "BA Psychology"],
        "blurb": "Studies human societies and cultures, in research, development or industry.",
        "whatYouDo": ["Conduct ethnographic fieldwork",
                      "Analyse social structures and behaviour",
                      "Advise on programme and product design",
                      "Publish research"],
        "dayInLife": "Extended fieldwork, then long stretches of analysis and writing.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-20 LPA", "senior": "Rs 20-55 LPA+ (UX research pays notably better)"},
        "alternates": ["ux-designer", "social-worker", "policy-analyst", "professor"],
    },
    {
        "id": "diplomat", "title": "Diplomat / International Affairs Specialist", "cluster": "F", "family": "civil_services",
        "degrees": ["BA International Relations", "BA Political Science", "BA Economics", "BA History", "BA Public Policy"],
        "blurb": "Represents or advises on a country's interests abroad.",
        "whatYouDo": ["Analyse political and economic developments",
                      "Negotiate and maintain bilateral relationships",
                      "Support citizens abroad through consular work",
                      "Report to the ministry"],
        "dayInLife": "Reporting cables, meetings, events, and a posting that changes every few years.",
        "entranceExams": [
            {"name": "UPSC Civil Services (IFS)", "when": "After graduation", "opens": "The Indian Foreign Service"},
        ],
        "salary": {"entry": "Rs 7-12 LPA (plus foreign allowances abroad)", "mid": "Rs 12-25 LPA", "senior": "Rs 25-45 LPA"},
        "alternates": ["civil-servant", "policy-analyst", "economist", "journalist"],
    },
    # -------------------------------------------------- HOSPITALITY & SPORT
    {
        "id": "hotel-manager", "title": "Hotel / Hospitality Manager", "cluster": "H", "family": "hospitality",
        "degrees": ["BHM", "BHMCT", "Hotel Administration", "Hospitality Management", "Tourism Management", "BBA"],
        "blurb": "Runs a hotel or a department within one, balancing guest experience against margin.",
        "whatYouDo": ["Manage front office, housekeeping or food and beverage",
                      "Control cost, occupancy and revenue",
                      "Lead large, shift-based teams",
                      "Resolve guest problems immediately"],
        "dayInLife": "Floor presence across shifts, daily revenue numbers, and a guest complaint that needs fixing now.",
        "salary": {"entry": "Rs 3-6 LPA", "mid": "Rs 6-18 LPA", "senior": "Rs 18-60 LPA+ (General Manager)"},
        "alternates": ["chef", "event-manager", "travel-consultant", "operations-manager"],
    },
    {
        "id": "chef", "title": "Chef / Culinary Professional", "cluster": "H", "family": "hospitality",
        "degrees": ["Culinary Arts", "BHM", "BHMCT", "Hotel Administration", "B.Sc Food Nutrition & Dietetics"],
        "blurb": "Cooks professionally and runs a kitchen as a working operation.",
        "whatYouDo": ["Develop menus and standardise recipes",
                      "Run service under time pressure",
                      "Control food cost and wastage",
                      "Train and lead a kitchen brigade"],
        "dayInLife": "Prep from morning, service in the evening, and split shifts that include weekends.",
        "salary": {"entry": "Rs 2.5-6 LPA", "mid": "Rs 6-18 LPA", "senior": "Rs 18-60 LPA+ (own restaurant uncapped and risky)"},
        "realityCheck": "Physically hard, hot and long-houred, on low starting pay. Progression is fast for those who stay, and the skill is portable worldwide.",
        "alternates": ["hotel-manager", "food-technologist", "nutritionist", "entrepreneur"],
    },
    {
        "id": "event-manager", "title": "Event Manager", "cluster": "H", "family": "hospitality",
        "degrees": ["Event Management", "BHM", "Hospitality Management", "BBA", "Mass Communication", "Tourism Management"],
        "blurb": "Plans and delivers events where everything must work on the day.",
        "whatYouDo": ["Plan concept, budget and logistics",
                      "Coordinate vendors, venues and permissions",
                      "Run the event live and solve problems in real time",
                      "Reconcile budget afterwards"],
        "dayInLife": "Weeks of planning compressed into one day where nothing can be postponed.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-20 LPA", "senior": "Rs 20-60 LPA+"},
        "alternates": ["hotel-manager", "marketing-manager", "public-relations-specialist", "entrepreneur"],
    },
    {
        "id": "travel-consultant", "title": "Travel & Tourism Professional", "cluster": "H", "family": "hospitality",
        "degrees": ["Travel & Tourism", "Tourism Management", "BHM", "Hospitality Management", "BBA"],
        "blurb": "Designs and sells travel, and runs the operations behind it.",
        "whatYouDo": ["Design itineraries and price them",
                      "Manage bookings, suppliers and contracts",
                      "Handle problems while clients are travelling",
                      "Build destination and product knowledge"],
        "dayInLife": "Client planning, supplier negotiation, and a booking that changes at short notice.",
        "salary": {"entry": "Rs 2.5-6 LPA", "mid": "Rs 6-16 LPA", "senior": "Rs 16-45 LPA+"},
        "alternates": ["hotel-manager", "event-manager", "entrepreneur", "media-manager"],
    },
    {
        "id": "sports-scientist", "title": "Sports Scientist / Performance Specialist", "cluster": "H", "family": "allied_health",
        "degrees": ["Physiotherapy", "B.Sc Food Nutrition & Dietetics", "B.Sc Psychology", "Occupational Therapy"],
        "blurb": "Uses physiology, biomechanics and psychology to improve athletic performance.",
        "whatYouDo": ["Test and monitor athlete physiology",
                      "Design training and recovery programmes",
                      "Analyse movement and reduce injury risk",
                      "Work with coaches on load management"],
        "dayInLife": "Testing sessions, data analysis, and pitch-side or gym-floor work.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-20 LPA", "senior": "Rs 20-60 LPA+ (professional teams highest)"},
        "alternates": ["physiotherapist", "nutritionist", "sports-coach", "psychologist"],
    },
    {
        "id": "sports-coach", "title": "Sports Coach / Manager", "cluster": "H", "family": "hospitality",
        "degrees": ["Physiotherapy", "BA Psychology", "B.Sc Psychology", "Hospitality Management", "BBA"],
        "blurb": "Trains athletes or teams and manages their development.",
        "whatYouDo": ["Plan training programmes and seasons",
                      "Develop technical and tactical skill",
                      "Manage team selection and morale",
                      "Analyse opposition and performance data"],
        "dayInLife": "Training sessions, video analysis, and individual conversations that matter more than the drills.",
        "salary": {"entry": "Rs 2.5-6 LPA", "mid": "Rs 6-18 LPA", "senior": "Rs 18-60 LPA+ (professional level far higher)"},
        "alternates": ["sports-scientist", "physiotherapist", "teacher", "defence-officer"],
    },
]
