#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Career catalogue, part 1: engineering, software, science, medicine, agriculture.

Each entry names the DEGREES that lead to it, using the degree strings exactly
as they appear in the client streams workbook. That link is what makes the
dropdown work: a student picks a stream, we resolve which degrees they are
eligible for, and a career is offered when at least one of its degrees is open
to them, carrying the best verdict among those degrees.

`cluster` is the A-H career-cluster letter the scoring engine already uses
(see data/career-clusters.json), which is how a student's assessment result is
compared against the career they said they wanted.

Anything a career does not state is inherited from its family in
demo_11_12_families.py, so every career has a complete roadmap.
"""

CAREERS_STEM = [
    # ------------------------------------------------------ SOFTWARE & DATA
    {
        "id": "software-engineer", "title": "Software Engineer", "cluster": "B", "family": "software",
        "degrees": ["B.Tech Computer Science", "B.Tech CSE", "B.Sc CS", "BCA", "B.Sc Computer Science", "B.Tech ECE"],
        "blurb": "Designs and builds the systems that run apps, websites and services used by millions.",
        "whatYouDo": ["Turn a product requirement into working, tested code",
                      "Design how data flows and where it is stored",
                      "Review other engineers' code and get yours reviewed",
                      "Debug failures in systems you did not write"],
        "dayInLife": "Most of the day is reading code and thinking, not typing. A stand-up, a few hours of focused building, a code review, and a bug that turns out to be one wrong character.",
        "salary": {"entry": "Rs 6-25 LPA", "mid": "Rs 25-60 LPA", "senior": "Rs 60 LPA-2 Cr+"},
        "alternates": ["data-scientist", "ai-ml-engineer", "product-manager", "cybersecurity-analyst"],
    },
    {
        "id": "ai-ml-engineer", "title": "AI / Machine Learning Engineer", "cluster": "B", "family": "software",
        "degrees": ["B.Tech AI/ML", "B.Tech Computer Science", "B.Tech CSE", "B.Sc AI", "B.Tech Data Science", "B.Sc Data Science"],
        "blurb": "Builds systems that learn from data - recommendation engines, language models, vision systems.",
        "whatYouDo": ["Frame a business problem as a learning problem",
                      "Prepare and clean the data, which is most of the work",
                      "Train, evaluate and deploy models",
                      "Monitor models that quietly degrade in production"],
        "dayInLife": "Long stretches of data wrangling, short bursts of training runs, and a lot of measuring whether the new model is genuinely better than the old one.",
        "coreSkills": ["Linear algebra, probability and statistics", "Python and PyTorch or TensorFlow",
                       "Data engineering", "Experiment design", "Knowing when a simpler model is the right answer"],
        "salary": {"entry": "Rs 8-30 LPA", "mid": "Rs 30-70 LPA", "senior": "Rs 70 LPA-3 Cr+"},
        "realityCheck": "The field moves fast enough that what you learn in year 1 of college is partly obsolete by graduation. Mathematics is the part that does not expire - prioritise it.",
        "alternates": ["data-scientist", "software-engineer", "research-scientist", "robotics-engineer"],
    },
    {
        "id": "data-scientist", "title": "Data Scientist", "cluster": "B", "family": "software",
        "degrees": ["B.Tech Data Science", "B.Sc Data Science", "B.Sc Statistics", "B.Tech Computer Science",
                    "B.Sc Mathematics", "B.Tech CSE", "B.Sc Economics"],
        "blurb": "Finds decisions inside data - what is happening, why, and what the company should do about it.",
        "whatYouDo": ["Turn a vague business question into a measurable one",
                      "Build models and run experiments such as A/B tests",
                      "Visualise findings so non-technical people can act on them",
                      "Challenge conclusions the data does not actually support"],
        "dayInLife": "SQL and Python most of the morning, a stakeholder meeting where you explain what the numbers do and do not mean, and an afternoon defending a result.",
        "salary": {"entry": "Rs 6-22 LPA", "mid": "Rs 22-50 LPA", "senior": "Rs 50 LPA-1.5 Cr+"},
        "alternates": ["ai-ml-engineer", "business-analyst", "actuary", "statistician"],
    },
    {
        "id": "cybersecurity-analyst", "title": "Cybersecurity Analyst", "cluster": "B", "family": "software",
        "degrees": ["B.Sc Cybersecurity", "B.Tech Computer Science", "B.Tech CSE", "BCA", "B.Sc CS"],
        "blurb": "Defends systems and data against attack, and investigates what happened when defences fail.",
        "whatYouDo": ["Monitor systems for intrusion and respond to incidents",
                      "Test your own organisation's defences by attacking them",
                      "Harden infrastructure and enforce access controls",
                      "Investigate breaches and write up how they happened"],
        "dayInLife": "Alert triage, a penetration test, and a policy argument about why the convenient option is the unsafe one.",
        "buildNow": ["Set up a home lab and break into your own machines, legally",
                     "Learn networking properly - most security failures are network failures",
                     "Try capture-the-flag competitions; they are the standard proving ground"],
        "salary": {"entry": "Rs 5-18 LPA", "mid": "Rs 18-45 LPA", "senior": "Rs 45 LPA-1.2 Cr+"},
        "alternates": ["software-engineer", "cloud-devops-engineer", "forensic-accountant"],
    },
    {
        "id": "cloud-devops-engineer", "title": "Cloud / DevOps Engineer", "cluster": "B", "family": "software",
        "degrees": ["B.Tech Computer Science", "B.Tech CSE", "BCA", "B.Sc CS", "B.Tech ECE"],
        "blurb": "Builds and runs the infrastructure everything else is deployed on, and keeps it up.",
        "whatYouDo": ["Automate how software is built, tested and released",
                      "Design cloud infrastructure that scales and does not overspend",
                      "Be on call when production breaks",
                      "Make deployments boring, which is the highest compliment here"],
        "dayInLife": "Infrastructure-as-code in the morning, a pipeline that broke at noon, and capacity planning nobody notices until it is wrong.",
        "salary": {"entry": "Rs 5-20 LPA", "mid": "Rs 20-50 LPA", "senior": "Rs 50 LPA-1.5 Cr+"},
        "alternates": ["software-engineer", "cybersecurity-analyst", "systems-engineer"],
    },
    {
        "id": "game-developer", "title": "Game Developer", "cluster": "B", "family": "software",
        "degrees": ["B.Tech Computer Science", "B.Tech CSE", "BCA", "B.Sc CS", "B.Des", "Animation"],
        "blurb": "Builds interactive worlds - the code, physics and feel of how a game plays.",
        "whatYouDo": ["Programme game mechanics, physics and AI behaviour",
                      "Optimise so it runs smoothly on modest hardware",
                      "Work closely with artists and designers",
                      "Playtest relentlessly and cut what is not fun"],
        "dayInLife": "Building a mechanic, playing it fifty times, and discovering the fun was in the bug you were about to fix.",
        "buildNow": ["Make small games in Unity or Godot now - a finished tiny game is a real portfolio piece",
                     "Learn C# or C++", "Join a game jam; 48 hours teaches more than a semester"],
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-30 LPA", "senior": "Rs 30-80 LPA+"},
        "realityCheck": "Indian game studios pay below general software and hours around release can be brutal. Passion sustains it; do it knowing the trade.",
        "alternates": ["software-engineer", "animator", "vfx-artist", "product-designer"],
    },
    # ------------------------------------------------------- CORE ENGINEERING
    {
        "id": "mechanical-engineer", "title": "Mechanical Engineer", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech Mechanical", "B.Tech Aerospace", "B.Tech Agricultural Engineering"],
        "blurb": "Designs and builds machines and mechanical systems, from engines to manufacturing lines.",
        "whatYouDo": ["Model components in CAD and simulate how they behave",
                      "Choose materials and manufacturing processes",
                      "Test prototypes and iterate on what fails",
                      "Work with production teams to make a design manufacturable"],
        "dayInLife": "CAD and simulation, a shop-floor visit to see why the part does not fit, and a design review.",
        "salary": {"entry": "Rs 3.5-10 LPA", "mid": "Rs 10-25 LPA", "senior": "Rs 25-60 LPA+"},
        "realityCheck": "Core mechanical pays less at entry than software, and many graduates drift into IT. The ones who stay and specialise - EV, aerospace, robotics - do very well.",
        "alternates": ["automotive-engineer", "aerospace-engineer", "robotics-engineer", "product-designer"],
    },
    {
        "id": "civil-engineer", "title": "Civil / Structural Engineer", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech Civil", "B.Planning", "B.Plan-related programmes"],
        "blurb": "Designs and oversees the built environment - buildings, bridges, roads, water systems.",
        "whatYouDo": ["Analyse structures for load, stress and safety",
                      "Produce drawings and specifications contractors build from",
                      "Supervise construction and quality on site",
                      "Manage cost, schedule and statutory approvals"],
        "dayInLife": "Half at a desk with structural software, half on site where reality disagrees with the drawing.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-20 LPA", "senior": "Rs 20-50 LPA+ (own practice or PSU seniority)"},
        "realityCheck": "Site postings are often remote and the work is weather-exposed. Public infrastructure spending is strong, so demand is steady even when private construction is not.",
        "alternates": ["architect", "urban-planner", "construction-manager", "environmental-engineer"],
    },
    {
        "id": "electrical-engineer", "title": "Electrical & Electronics Engineer", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech EEE", "B.Tech ECE", "B.Tech Computer Science"],
        "blurb": "Designs the electrical and electronic systems inside power grids, vehicles and devices.",
        "whatYouDo": ["Design circuits, control systems and power electronics",
                      "Test hardware and diagnose faults",
                      "Work on embedded software that drives the hardware",
                      "Ensure systems meet safety and efficiency standards"],
        "dayInLife": "Circuit design, bench testing with an oscilloscope, and firmware that must fit in very little memory.",
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-28 LPA", "senior": "Rs 28-70 LPA+"},
        "alternates": ["robotics-engineer", "renewable-energy-engineer", "embedded-engineer", "software-engineer"],
    },
    {
        "id": "aerospace-engineer", "title": "Aerospace Engineer", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech Aerospace", "B.Tech Mechanical"],
        "blurb": "Designs aircraft, spacecraft and propulsion systems.",
        "whatYouDo": ["Model aerodynamics and structural loads",
                      "Design propulsion or airframe subsystems",
                      "Run simulations and wind-tunnel or flight tests",
                      "Work inside very tight safety certification requirements"],
        "dayInLife": "Simulation-heavy, with long review cycles - in aerospace nothing ships until it is provably safe.",
        "topColleges": ["IIT Bombay / Madras / Kanpur (Aerospace)", "IIST Thiruvananthapuram", "MIT Manipal", "Amity Institute of Aerospace"],
        "salary": {"entry": "Rs 5-14 LPA", "mid": "Rs 14-32 LPA", "senior": "Rs 32-75 LPA+"},
        "realityCheck": "A small field in India with ISRO, HAL, DRDO and a growing private space sector as the main employers. Rewarding, but fewer openings than mainstream branches.",
        "alternates": ["mechanical-engineer", "robotics-engineer", "research-scientist", "defence-officer"],
    },
    {
        "id": "robotics-engineer", "title": "Robotics & Automation Engineer", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech Mechanical", "B.Tech EEE", "B.Tech ECE", "B.Tech Computer Science", "B.Tech AI/ML"],
        "blurb": "Builds machines that sense, decide and act - factory automation, drones, autonomous systems.",
        "whatYouDo": ["Integrate mechanical, electronic and software subsystems",
                      "Write control and perception code",
                      "Calibrate sensors and test in the messy real world",
                      "Improve reliability, which is where most of the effort goes"],
        "dayInLife": "A robot that worked yesterday does not today, and finding out why spans three disciplines.",
        "salary": {"entry": "Rs 5-16 LPA", "mid": "Rs 16-38 LPA", "senior": "Rs 38-90 LPA+"},
        "alternates": ["mechanical-engineer", "ai-ml-engineer", "electrical-engineer", "embedded-engineer"],
    },
    {
        "id": "embedded-engineer", "title": "Embedded Systems Engineer", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech ECE", "B.Tech EEE", "B.Tech Computer Science", "B.Tech CSE"],
        "blurb": "Writes the software that runs inside physical devices - cars, medical equipment, appliances.",
        "whatYouDo": ["Programme microcontrollers in C or C++",
                      "Work within severe memory, power and timing limits",
                      "Debug with hardware tools, not just print statements",
                      "Meet safety standards for devices that must not fail"],
        "dayInLife": "Firmware, a logic analyser, and a bug that only appears when the device gets warm.",
        "salary": {"entry": "Rs 4-14 LPA", "mid": "Rs 14-32 LPA", "senior": "Rs 32-75 LPA+"},
        "alternates": ["electrical-engineer", "robotics-engineer", "software-engineer", "automotive-engineer"],
    },
    {
        "id": "automotive-engineer", "title": "Automotive / EV Engineer", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech Mechanical", "B.Tech EEE", "B.Tech ECE"],
        "blurb": "Designs vehicles and their systems, increasingly electric drivetrains and battery packs.",
        "whatYouDo": ["Design powertrain, chassis or battery subsystems",
                      "Test for performance, safety and range",
                      "Work to homologation and emissions standards",
                      "Cut cost per unit without losing reliability"],
        "dayInLife": "Design review, test-track or dynamometer data, and a supplier negotiation about a two-rupee component.",
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-28 LPA", "senior": "Rs 28-70 LPA+"},
        "alternates": ["mechanical-engineer", "electrical-engineer", "robotics-engineer", "renewable-energy-engineer"],
    },
    {
        "id": "chemical-engineer", "title": "Chemical / Process Engineer", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech Chemical", "B.Tech Food Technology", "B.Tech Environmental Engineering"],
        "blurb": "Designs and runs the processes that turn raw materials into fuels, medicines, foods and materials.",
        "whatYouDo": ["Design reactors, separation and heat-transfer systems",
                      "Scale a laboratory process up to a plant",
                      "Optimise yield, energy use and safety",
                      "Troubleshoot a running plant where downtime is expensive"],
        "dayInLife": "Process simulation, a plant round, and a safety review that must consider what happens when things go wrong.",
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-28 LPA", "senior": "Rs 28-65 LPA+"},
        "alternates": ["environmental-engineer", "food-technologist", "biotechnologist", "materials-scientist"],
    },
    {
        "id": "environmental-engineer", "title": "Environmental Engineer", "cluster": "G", "family": "engineering",
        "degrees": ["B.Tech Environmental Engineering", "B.Sc Environmental Science", "B.Tech Civil", "B.Tech Chemical"],
        "blurb": "Designs the systems that keep water, air and land usable - treatment, remediation, compliance.",
        "whatYouDo": ["Design water and waste treatment systems",
                      "Assess environmental impact of projects",
                      "Monitor pollution and enforce standards",
                      "Advise on emissions and sustainability targets"],
        "dayInLife": "Field sampling, modelling, and a compliance report that decides whether a project proceeds.",
        "salary": {"entry": "Rs 3.5-9 LPA", "mid": "Rs 9-22 LPA", "senior": "Rs 22-55 LPA+"},
        "alternates": ["environmental-scientist", "civil-engineer", "urban-planner", "chemical-engineer"],
    },
    {
        "id": "renewable-energy-engineer", "title": "Renewable Energy Engineer", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech EEE", "B.Tech Mechanical", "B.Tech Environmental Engineering", "B.Tech Chemical"],
        "blurb": "Designs and operates solar, wind, storage and grid systems for the energy transition.",
        "whatYouDo": ["Size and design generation and storage systems",
                      "Model output and financial return for a site",
                      "Integrate variable generation into the grid",
                      "Commission and maintain installations"],
        "dayInLife": "Yield modelling, a site survey, and a tender document.",
        "salary": {"entry": "Rs 4-11 LPA", "mid": "Rs 11-26 LPA", "senior": "Rs 26-65 LPA+"},
        "realityCheck": "One of the fastest-growing engineering areas in India on the back of national capacity targets. Sites are often remote in the early years.",
        "alternates": ["electrical-engineer", "environmental-engineer", "mechanical-engineer"],
    },
    {
        "id": "construction-manager", "title": "Construction / Project Manager", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech Civil", "B.Planning", "B.Arch", "B.Plan-related programmes"],
        "blurb": "Runs a construction project - the money, the schedule, the people and the risk.",
        "whatYouDo": ["Plan sequence, resources and budget",
                      "Coordinate contractors, consultants and authorities",
                      "Track progress against programme and cost",
                      "Resolve the problems that stop work on site"],
        "dayInLife": "Site walk at 8, contractor meeting at 11, and an afternoon of variation orders and cash flow.",
        "salary": {"entry": "Rs 4-10 LPA", "mid": "Rs 10-28 LPA", "senior": "Rs 28-80 LPA+"},
        "alternates": ["civil-engineer", "architect", "urban-planner", "operations-manager"],
    },
    {
        "id": "systems-engineer", "title": "Industrial / Systems Engineer", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech Mechanical", "B.Tech Computer Science", "B.Tech Civil", "B.Tech Chemical"],
        "blurb": "Makes complex operations work better - factories, logistics networks, service systems.",
        "whatYouDo": ["Map and measure how work actually flows",
                      "Model bottlenecks and simulate improvements",
                      "Redesign processes and layouts",
                      "Implement change with the people who do the work"],
        "dayInLife": "Time studies, a simulation model, and persuading a floor supervisor that the new layout is better.",
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-30 LPA", "senior": "Rs 30-70 LPA+"},
        "alternates": ["operations-manager", "management-consultant", "data-scientist", "mechanical-engineer"],
    },
    # ------------------------------------------------- ARCHITECTURE & PLANNING
    {
        "id": "architect", "title": "Architect", "cluster": "D", "family": "design",
        # B.Arch only. Calling yourself an Architect in India requires Council
        # of Architecture registration, which B.Des and Interior Design do not
        # confer. Listing them made this read as OPEN to commerce students.
        "degrees": ["B.Arch"],
        "blurb": "Designs buildings that have to be beautiful, buildable, legal and affordable at once.",
        "whatYouDo": ["Develop a design from brief to construction drawings",
                      "Balance client wishes, budget, byelaws and site",
                      "Coordinate structural, services and landscape consultants",
                      "Visit site to see the design survive contact with construction"],
        "dayInLife": "Drawing and modelling, a client presentation, and a byelaw that forces the whole plan to change.",
        "entranceExams": [
            {"name": "NATA", "when": "Class 12, Apr-Jul", "opens": "B.Arch at most architecture schools"},
            {"name": "JEE Main Paper 2", "when": "Class 12, Jan & Apr", "opens": "B.Arch at NITs, SPAs and IITs"},
        ],
        "topColleges": ["School of Planning & Architecture, Delhi", "CEPT Ahmedabad", "IIT Roorkee (Architecture)",
                        "Sir JJ College of Architecture Mumbai", "Manipal School of Architecture"],
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-22 LPA", "senior": "Rs 22-70 LPA+ (own practice uncapped)"},
        "realityCheck": "A five-year degree followed by low-paid early years is the norm; the profession rewards patience and a portfolio. Registration with the Council of Architecture is mandatory to call yourself an architect.",
        "alternates": ["urban-planner", "interior-designer", "civil-engineer", "product-designer"],
    },
    {
        "id": "urban-planner", "title": "Urban & Regional Planner", "cluster": "A", "family": "design",
        "degrees": ["B.Planning", "B.Plan-related programmes", "B.Arch", "BA Geography", "B.Sc Geology"],
        "blurb": "Decides how cities grow - land use, transport, housing and infrastructure.",
        "whatYouDo": ["Analyse demographic, land and transport data",
                      "Prepare development plans and zoning proposals",
                      "Run public consultation",
                      "Advise government on policy and approvals"],
        "dayInLife": "GIS analysis, a stakeholder meeting, and a master-plan document that will outlive you.",
        "salary": {"entry": "Rs 3.5-9 LPA", "mid": "Rs 9-22 LPA", "senior": "Rs 22-55 LPA+"},
        "alternates": ["architect", "civil-engineer", "policy-analyst", "environmental-engineer"],
    },
    # ---------------------------------------------------------------- MEDICAL
    {
        "id": "doctor", "title": "Doctor (MBBS)", "cluster": "C", "family": "medical",
        "degrees": ["MBBS"],
        "blurb": "Diagnoses and treats illness - the longest training in this list and the widest responsibility.",
        "whatYouDo": ["Take histories, examine, and reason towards a diagnosis",
                      "Order and interpret investigations",
                      "Manage treatment and follow-up",
                      "Explain serious things to frightened people"],
        "dayInLife": "Ward rounds, outpatient clinic, procedures, and notes. During residency, add nights and a permanently full list.",
        "salary": {"entry": "Rs 6-12 LPA (junior resident)", "mid": "Rs 12-35 LPA (post-MD)", "senior": "Rs 35 LPA-1 Cr+ (consultant or private practice)"},
        "alternates": ["surgeon", "dentist", "psychiatrist", "public-health-specialist", "medical-researcher"],
    },
    {
        "id": "surgeon", "title": "Surgeon", "cluster": "C", "family": "medical",
        "degrees": ["MBBS"],
        "blurb": "Treats through operation - the MBBS route followed by a surgical MS and super-specialisation.",
        "whatYouDo": ["Assess whether surgery is the right answer",
                      "Operate, often for many hours",
                      "Manage post-operative recovery and complications",
                      "Train juniors in the theatre"],
        "dayInLife": "Early rounds, a theatre list that overruns, and being called back at night.",
        "afterSchool": [
            {"stage": "MBBS", "years": "5.5 years", "what": "Including internship"},
            {"stage": "MS via NEET-PG", "years": "3 years", "what": "General surgery or a surgical specialty"},
            {"stage": "MCh super-specialisation", "years": "+3 years", "what": "Cardiothoracic, neuro, plastic and similar"},
        ],
        "salary": {"entry": "Rs 8-15 LPA", "mid": "Rs 20-50 LPA", "senior": "Rs 50 LPA-3 Cr+"},
        "realityCheck": "Roughly 13-15 years from class 12 to independent consultant surgeon, with physically demanding hours throughout.",
        "alternates": ["doctor", "dentist", "medical-researcher"],
    },
    {
        "id": "dentist", "title": "Dentist", "cluster": "C", "family": "medical",
        "degrees": ["BDS"],
        "blurb": "Diagnoses and treats oral health, from routine care to surgery and orthodontics.",
        "whatYouDo": ["Examine, diagnose and plan treatment",
                      "Carry out procedures with fine motor precision",
                      "Manage anxious patients",
                      "Run a practice, for most dentists eventually"],
        "dayInLife": "A booked appointment list, precise close-up work, and a practice to keep financially healthy.",
        "afterSchool": [
            {"stage": "BDS", "years": "5 years", "what": "4 years plus a year of rotating internship"},
            {"stage": "MDS (optional)", "years": "3 years", "what": "Orthodontics, endodontics, oral surgery via NEET-MDS"},
            {"stage": "Practice", "years": "After registration", "what": "Associate in a clinic, then usually your own"},
        ],
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-20 LPA", "senior": "Rs 20-60 LPA+ (own practice)"},
        "realityCheck": "Salaried dentistry pays modestly; the earnings come from owning a practice, which needs capital and business skill as well as clinical skill.",
        "alternates": ["doctor", "doctor", "surgeon", "physiotherapist"],
    },
    {
        "id": "ayush-practitioner", "title": "AYUSH Practitioner (BAMS / BHMS / BUMS / BSMS)", "cluster": "C", "family": "medical",
        "degrees": ["BAMS", "BHMS", "BUMS", "BSMS"],
        "blurb": "Practises Ayurveda, Homoeopathy, Unani or Siddha medicine, with a full clinical degree and registration.",
        "whatYouDo": ["Diagnose within your system's framework alongside modern diagnostics",
                      "Prescribe and manage treatment plans",
                      "Run a clinic or work in an integrative hospital",
                      "Advise on lifestyle and preventive regimes"],
        "dayInLife": "Consultations that run longer than allopathic ones, plus dispensary and follow-up.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-50 LPA+ (established practice)"},
        "realityCheck": "Government backing and wellness demand are growing, but recognition varies by state and employer. Check practice rights in the state you intend to work in.",
        "alternates": ["doctor", "nutritionist", "physiotherapist", "pharmacist"],
    },
    {
        "id": "veterinarian", "title": "Veterinarian", "cluster": "G", "family": "medical",
        "degrees": ["Veterinary / BVSc"],
        "blurb": "Treats animals - companion, livestock and wildlife - and protects public health through them.",
        "whatYouDo": ["Diagnose and treat animals that cannot describe symptoms",
                      "Perform surgery and preventive care",
                      "Advise livestock owners on herd health and productivity",
                      "Work on zoonotic disease control"],
        "dayInLife": "Clinic consultations, a farm call, and an emergency that arrives without warning.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-18 LPA", "senior": "Rs 18-45 LPA+"},
        "alternates": ["doctor", "agricultural-scientist", "wildlife-biologist", "microbiologist"],
    },
    {
        "id": "nurse", "title": "Nurse", "cluster": "C", "family": "allied_health",
        "degrees": ["B.Sc Nursing"],
        "blurb": "Delivers and coordinates most of the actual care a patient receives.",
        "whatYouDo": ["Monitor patients and escalate deterioration early",
                      "Administer medication and treatments",
                      "Coordinate between doctors, families and support staff",
                      "Specialise in critical care, theatre, paediatrics or oncology"],
        "dayInLife": "Shift handover, a full patient load, and the judgement calls that catch problems before they become emergencies.",
        "salary": {"entry": "Rs 3-6 LPA", "mid": "Rs 6-14 LPA", "senior": "Rs 14-35 LPA+ (far higher abroad)"},
        "realityCheck": "Chronically in demand worldwide, which makes international mobility unusually good. Shift work and emotional load are real and constant.",
        "alternates": ["physiotherapist", "doctor", "radiographer", "public-health-specialist"],
    },
    {
        "id": "physiotherapist", "title": "Physiotherapist", "cluster": "C", "family": "allied_health",
        "degrees": ["Physiotherapy", "Occupational Therapy"],
        "blurb": "Restores movement and function after injury, surgery or illness.",
        "whatYouDo": ["Assess movement and diagnose functional problems",
                      "Design and progress a rehabilitation programme",
                      "Deliver hands-on therapy",
                      "Keep patients motivated through slow recovery"],
        "dayInLife": "Back-to-back patients, hands-on work, and the satisfaction of someone walking who could not last month.",
        "salary": {"entry": "Rs 3-6 LPA", "mid": "Rs 6-15 LPA", "senior": "Rs 15-40 LPA+ (sports and private practice highest)"},
        "alternates": ["sports-scientist", "occupational-therapist", "nurse", "doctor"],
    },
    {
        "id": "occupational-therapist", "title": "Occupational Therapist", "cluster": "C", "family": "allied_health",
        "degrees": ["Occupational Therapy", "Physiotherapy", "B.Sc Psychology"],
        "blurb": "Helps people regain the ability to do the everyday things that matter to them.",
        "whatYouDo": ["Assess how a condition limits daily living",
                      "Design adaptations, aids and retraining",
                      "Work with children with developmental needs",
                      "Coach families and workplaces on accommodation"],
        "dayInLife": "Home or school visits, tailored activity plans, and progress measured in small independences.",
        "salary": {"entry": "Rs 3-6 LPA", "mid": "Rs 6-14 LPA", "senior": "Rs 14-35 LPA+"},
        "alternates": ["physiotherapist", "psychologist", "special-educator", "nurse"],
    },
    {
        "id": "pharmacist", "title": "Pharmacist / Pharmaceutical Scientist", "cluster": "C", "family": "allied_health",
        "degrees": ["Pharmacy"],
        "blurb": "Works on how medicines are formulated, tested, regulated and dispensed safely.",
        "whatYouDo": ["Dispense and counsel on medication and interactions",
                      "Formulate and test drug products in industry",
                      "Run quality control and regulatory submissions",
                      "Support clinical trials"],
        "dayInLife": "In industry, laboratory and documentation; in a hospital, verifying prescriptions and advising clinicians.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-20 LPA", "senior": "Rs 20-50 LPA+"},
        "alternates": ["biotechnologist", "chemist", "medical-researcher", "medical-lab-scientist"],
    },
    {
        "id": "medical-lab-scientist", "title": "Medical Laboratory Scientist", "cluster": "C", "family": "allied_health",
        "degrees": ["Medical Laboratory Technology", "Microbiology", "Biochemistry"],
        "blurb": "Runs the diagnostic tests most clinical decisions actually depend on.",
        "whatYouDo": ["Process and analyse clinical samples",
                      "Operate and calibrate analytical instruments",
                      "Enforce quality control so results can be trusted",
                      "Flag critical results immediately"],
        "dayInLife": "Sample runs, instrument maintenance, and quality checks that matter enormously and are invisible when done right.",
        "salary": {"entry": "Rs 2.5-6 LPA", "mid": "Rs 6-14 LPA", "senior": "Rs 14-30 LPA+"},
        "alternates": ["microbiologist", "biochemist", "geneticist", "radiographer"],
    },
    {
        "id": "radiographer", "title": "Radiographer / Imaging Technologist", "cluster": "C", "family": "allied_health",
        "degrees": ["Radiology / Imaging"],
        "blurb": "Produces the images - X-ray, CT, MRI, ultrasound - that diagnosis is built on.",
        "whatYouDo": ["Position patients and acquire diagnostic-quality images",
                      "Operate and maintain imaging equipment",
                      "Apply radiation-safety protocols rigorously",
                      "Work alongside radiologists on reporting"],
        "dayInLife": "A steady list of scans, some emergencies, and constant attention to dose and safety.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-16 LPA", "senior": "Rs 16-35 LPA+"},
        "alternates": ["medical-lab-scientist", "nurse", "doctor"],
    },
    {
        "id": "optometrist", "title": "Optometrist", "cluster": "C", "family": "allied_health",
        "degrees": ["Optometry"],
        "blurb": "Examines eyes, diagnoses vision problems and manages correction and eye health.",
        "whatYouDo": ["Perform eye examinations and vision testing",
                      "Prescribe lenses and vision therapy",
                      "Detect eye disease and refer on",
                      "Manage contact-lens and low-vision care"],
        "dayInLife": "Consultations, refraction, and increasingly screening for diabetic and age-related eye disease.",
        "salary": {"entry": "Rs 3-6 LPA", "mid": "Rs 6-14 LPA", "senior": "Rs 14-35 LPA+ (own clinic)"},
        "alternates": ["doctor", "medical-lab-scientist", "physiotherapist"],
    },
    {
        "id": "nutritionist", "title": "Nutritionist / Dietitian", "cluster": "C", "family": "allied_health",
        "degrees": ["B.Sc Food Nutrition & Dietetics", "B.Sc Agriculture"],
        "blurb": "Uses food and diet clinically - for disease management, sport, and public health.",
        "whatYouDo": ["Assess nutritional status and needs",
                      "Design diet plans for clinical conditions",
                      "Counsel patients through sustainable change",
                      "Advise institutions, teams or food companies"],
        "dayInLife": "Consultations, plan design, and the harder work of helping people actually stick to it.",
        "salary": {"entry": "Rs 2.5-6 LPA", "mid": "Rs 6-15 LPA", "senior": "Rs 15-40 LPA+ (private and sports practice highest)"},
        "alternates": ["food-technologist", "sports-scientist", "public-health-specialist", "chef"],
    },
    {
        "id": "public-health-specialist", "title": "Public Health Specialist", "cluster": "F", "family": "allied_health",
        "degrees": ["MBBS", "B.Sc Nursing", "B.Sc Environmental Science", "BA Sociology", "B.Sc Psychology"],
        "blurb": "Works on the health of populations rather than individuals - programmes, epidemiology, policy.",
        "whatYouDo": ["Analyse disease patterns across populations",
                      "Design and evaluate health programmes",
                      "Advise on policy and resource allocation",
                      "Coordinate outbreak response"],
        "dayInLife": "Data analysis, field programme review, and a policy brief for people who will act on it.",
        "topColleges": ["AIIMS New Delhi", "PHFI (Indian Institutes of Public Health)", "TISS Mumbai", "JIPMER"],
        "salary": {"entry": "Rs 4-10 LPA", "mid": "Rs 10-25 LPA", "senior": "Rs 25-60 LPA+ (WHO and global bodies higher)"},
        "alternates": ["doctor", "policy-analyst", "medical-researcher", "social-worker"],
    },
    # ------------------------------------------------------------- SCIENCES
    {
        "id": "research-scientist", "title": "Research Scientist", "cluster": "G", "family": "sciences",
        "degrees": ["B.Sc Physics", "B.Sc Chemistry", "B.Sc Mathematics", "B.Sc Biotechnology", "Biotechnology",
                    "B.Sc Environmental Science", "B.Sc Geology", "Genetics", "Biochemistry"],
        "blurb": "Investigates questions nobody has answered yet, and publishes what holds up.",
        "whatYouDo": ["Frame a question that is actually answerable",
                      "Design and run experiments",
                      "Analyse data honestly, including when it disagrees with you",
                      "Write papers and grant proposals"],
        "dayInLife": "Bench or computational work, a lab meeting, and reading. Progress is slow and then sudden.",
        "salary": {"entry": "Rs 4-9 LPA (JRF/SRF stipend during PhD)", "mid": "Rs 9-22 LPA", "senior": "Rs 22-60 LPA+ (industry R&D highest)"},
        "realityCheck": "A PhD is effectively mandatory and takes 4-6 years on a modest stipend. Deeply satisfying for the genuinely curious; frustrating for anyone who wanted a fast, defined ladder.",
        "alternates": ["data-scientist", "medical-researcher", "professor", "biotechnologist"],
    },
    {
        "id": "physicist", "title": "Physicist", "cluster": "G", "family": "sciences",
        "degrees": ["B.Sc Physics", "B.Tech Aerospace"],
        "blurb": "Studies matter, energy and the rules underneath them, in research or applied industry.",
        "whatYouDo": ["Build mathematical models of physical systems",
                      "Design experiments or run large simulations",
                      "Work with instrumentation and precision measurement",
                      "Apply physics in semiconductors, optics, energy or finance"],
        "dayInLife": "Mathematics, code, and instrumentation, in proportions that depend entirely on your subfield.",
        "salary": {"entry": "Rs 4-10 LPA", "mid": "Rs 10-28 LPA", "senior": "Rs 28-80 LPA+ (quant finance and semiconductors highest)"},
        "alternates": ["research-scientist", "data-scientist", "aerospace-engineer", "professor"],
    },
    {
        "id": "chemist", "title": "Chemist", "cluster": "G", "family": "sciences",
        "degrees": ["B.Sc Chemistry", "B.Tech Chemical", "Pharmacy", "Biochemistry"],
        "blurb": "Studies and creates substances - medicines, materials, fuels, everyday products.",
        "whatYouDo": ["Synthesise and characterise compounds",
                      "Run analytical methods and interpret spectra",
                      "Scale a reaction from milligrams to kilograms",
                      "Maintain safety and documentation standards"],
        "dayInLife": "Bench chemistry, instrument time, and a notebook that has to be defensible years later.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-20 LPA", "senior": "Rs 20-50 LPA+"},
        "alternates": ["chemical-engineer", "pharmacist", "materials-scientist", "research-scientist"],
    },
    {
        "id": "materials-scientist", "title": "Materials Scientist", "cluster": "G", "family": "sciences",
        "degrees": ["B.Sc Chemistry", "B.Sc Physics", "B.Tech Chemical", "B.Tech Mechanical"],
        "blurb": "Designs materials with the properties a technology needs - batteries, alloys, semiconductors.",
        "whatYouDo": ["Design and synthesise new materials",
                      "Characterise structure and properties",
                      "Test durability under real conditions",
                      "Work with engineers to get materials into products"],
        "dayInLife": "Sample preparation, electron microscopy, and property testing that takes weeks.",
        "salary": {"entry": "Rs 4-10 LPA", "mid": "Rs 10-26 LPA", "senior": "Rs 26-70 LPA+"},
        "alternates": ["chemist", "mechanical-engineer", "research-scientist", "chemical-engineer"],
    },
    {
        "id": "mathematician", "title": "Mathematician", "cluster": "G", "family": "sciences",
        "degrees": ["B.Sc Mathematics", "B.Sc Statistics"],
        "blurb": "Works on abstract structure, and on the applied mathematics behind cryptography, finance and modelling.",
        "whatYouDo": ["Prove results or build mathematical models",
                      "Apply mathematics to real systems",
                      "Collaborate with scientists and engineers",
                      "Teach and publish"],
        "dayInLife": "Paper, a whiteboard and long silences, punctuated by seminars.",
        "topColleges": ["Chennai Mathematical Institute", "ISI Kolkata / Bengaluru", "IISc Bengaluru", "IIT Kanpur / Bombay", "St Stephen's Delhi"],
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-35 LPA", "senior": "Rs 35 LPA-2 Cr+ (quantitative finance highest)"},
        "alternates": ["statistician", "data-scientist", "actuary", "quant-analyst", "professor"],
    },
    {
        "id": "statistician", "title": "Statistician", "cluster": "G", "family": "sciences",
        "degrees": ["B.Sc Statistics", "B.Sc Mathematics", "B.Sc Economics", "BBA Business Analytics"],
        "blurb": "Designs how data is collected and decides what it does and does not prove.",
        "whatYouDo": ["Design surveys, trials and sampling schemes",
                      "Choose and apply the right statistical model",
                      "Quantify uncertainty honestly",
                      "Advise on decisions taken under that uncertainty"],
        "dayInLife": "Study design, analysis in R or Python, and explaining to a client why their preferred conclusion is not supported.",
        "salary": {"entry": "Rs 5-14 LPA", "mid": "Rs 14-35 LPA", "senior": "Rs 35-90 LPA+"},
        "alternates": ["data-scientist", "actuary", "mathematician", "economist"],
    },
    {
        "id": "biotechnologist", "title": "Biotechnologist", "cluster": "G", "family": "sciences",
        "degrees": ["B.Tech Biotechnology", "B.Sc Biotechnology", "Biotechnology", "Genetics", "Microbiology", "Biochemistry"],
        "blurb": "Engineers biological systems to make medicines, foods, materials and diagnostics.",
        "whatYouDo": ["Culture cells and manipulate genetic material",
                      "Develop and optimise bioprocesses",
                      "Run assays and validate results",
                      "Scale laboratory work to production"],
        "dayInLife": "Sterile technique, incubation waits, and experiments measured in days rather than hours.",
        "salary": {"entry": "Rs 3-9 LPA", "mid": "Rs 9-24 LPA", "senior": "Rs 24-60 LPA+"},
        "realityCheck": "Indian biotech entry salaries lag engineering noticeably, and the strongest roles usually expect a master's. The pharma and vaccine sector is where the money is.",
        "alternates": ["research-scientist", "microbiologist", "geneticist", "pharmacist"],
    },
    {
        "id": "microbiologist", "title": "Microbiologist", "cluster": "G", "family": "sciences",
        "degrees": ["Microbiology", "B.Sc Biotechnology", "Biotechnology", "Biochemistry"],
        "blurb": "Studies microorganisms - in disease, in food safety, in industry and in the environment.",
        "whatYouDo": ["Isolate, culture and identify organisms",
                      "Test antimicrobial resistance",
                      "Ensure microbial safety in food and pharma production",
                      "Investigate outbreaks"],
        "dayInLife": "Plates, incubators, microscopy, and strict contamination discipline.",
        "salary": {"entry": "Rs 2.5-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-45 LPA+"},
        "alternates": ["biotechnologist", "medical-lab-scientist", "food-technologist", "research-scientist"],
    },
    {
        "id": "geneticist", "title": "Geneticist / Genomics Scientist", "cluster": "G", "family": "sciences",
        "degrees": ["Genetics", "B.Sc Biotechnology", "Biotechnology", "Biochemistry", "B.Tech Biotechnology"],
        "blurb": "Studies genes and genomes - inherited disease, diagnostics, crop and therapeutic development.",
        "whatYouDo": ["Sequence and analyse genomic data",
                      "Interpret variants clinically",
                      "Run genetic counselling or research studies",
                      "Apply gene-editing techniques"],
        "dayInLife": "Increasingly computational - large datasets, pipelines and statistics as much as bench work.",
        "salary": {"entry": "Rs 4-10 LPA", "mid": "Rs 10-26 LPA", "senior": "Rs 26-65 LPA+"},
        "alternates": ["biotechnologist", "medical-researcher", "data-scientist", "research-scientist"],
    },
    {
        "id": "biochemist", "title": "Biochemist", "cluster": "G", "family": "sciences",
        "degrees": ["Biochemistry", "B.Sc Chemistry", "B.Sc Biotechnology", "Biotechnology"],
        "blurb": "Studies the chemistry of living things - metabolism, proteins, drug action.",
        "whatYouDo": ["Purify and characterise proteins and enzymes",
                      "Study metabolic and signalling pathways",
                      "Support drug discovery and clinical diagnostics",
                      "Develop and validate assays"],
        "dayInLife": "Assay work, chromatography, and careful controls.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-20 LPA", "senior": "Rs 20-50 LPA+"},
        "alternates": ["biotechnologist", "chemist", "medical-lab-scientist", "research-scientist"],
    },
    {
        "id": "medical-researcher", "title": "Medical / Clinical Researcher", "cluster": "C", "family": "sciences",
        "degrees": ["MBBS", "B.Sc Biotechnology", "Biotechnology", "Pharmacy", "Biochemistry", "Genetics"],
        "blurb": "Runs the studies that decide whether a treatment actually works.",
        "whatYouDo": ["Design clinical trials and protocols",
                      "Manage ethics approval and regulatory compliance",
                      "Collect and analyse trial data",
                      "Publish and translate findings into practice"],
        "dayInLife": "Protocol writing, site coordination, data review, and a great deal of documentation.",
        "salary": {"entry": "Rs 4-10 LPA", "mid": "Rs 10-28 LPA", "senior": "Rs 28-70 LPA+"},
        "alternates": ["doctor", "research-scientist", "biotechnologist", "public-health-specialist"],
    },
    {
        "id": "environmental-scientist", "title": "Environmental Scientist", "cluster": "G", "family": "sciences",
        "degrees": ["B.Sc Environmental Science", "B.Sc Geology", "B.Sc Forestry", "B.Tech Environmental Engineering"],
        "blurb": "Studies environmental systems and how human activity changes them.",
        "whatYouDo": ["Sample and monitor air, water, soil and biodiversity",
                      "Model environmental impact",
                      "Prepare impact assessments and compliance reports",
                      "Advise on conservation and climate adaptation"],
        "dayInLife": "Fieldwork in bursts, laboratory and modelling in between, and reports that carry legal weight.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-20 LPA", "senior": "Rs 20-50 LPA+ (ESG consulting highest)"},
        "alternates": ["environmental-engineer", "wildlife-biologist", "geologist", "policy-analyst"],
    },
    {
        "id": "geologist", "title": "Geologist", "cluster": "G", "family": "sciences",
        "degrees": ["B.Sc Geology", "B.Sc Environmental Science"],
        "blurb": "Studies the Earth - resources, hazards, groundwater and the ground under construction.",
        "whatYouDo": ["Map and sample geological formations",
                      "Interpret seismic and remote-sensing data",
                      "Assess sites for construction, mining or water",
                      "Model hazards such as landslides and earthquakes"],
        "dayInLife": "Field seasons away from home, alternating with laboratory and modelling work.",
        "salary": {"entry": "Rs 3.5-9 LPA", "mid": "Rs 9-24 LPA", "senior": "Rs 24-60 LPA+ (oil, gas and mining highest)"},
        "alternates": ["environmental-scientist", "civil-engineer", "civil-engineer", "research-scientist"],
    },
    {
        "id": "wildlife-biologist", "title": "Wildlife Biologist / Conservationist", "cluster": "G", "family": "sciences",
        "degrees": ["B.Sc Forestry", "B.Sc Environmental Science", "B.Sc Biotechnology", "Veterinary / BVSc"],
        "blurb": "Studies and protects wild species and habitats.",
        "whatYouDo": ["Survey populations and habitat condition",
                      "Design and run conservation programmes",
                      "Work with communities on human-wildlife conflict",
                      "Advise policy and protected-area management"],
        "dayInLife": "Long field spells in difficult terrain, then data analysis and grant writing.",
        "topColleges": ["Wildlife Institute of India, Dehradun", "NCBS Bengaluru", "FRI Dehradun", "Ashoka Trust for Research in Ecology (ATREE)"],
        "salary": {"entry": "Rs 2.5-6 LPA", "mid": "Rs 6-15 LPA", "senior": "Rs 15-35 LPA+"},
        "realityCheck": "Pay is low relative to the qualifications required and posts are few. People do it because they cannot imagine doing anything else.",
        "alternates": ["environmental-scientist", "forest-officer", "veterinarian", "research-scientist"],
    },
    # --------------------------------------------------------- AGRICULTURE
    {
        "id": "agricultural-scientist", "title": "Agricultural Scientist", "cluster": "G", "family": "agriculture",
        "degrees": ["B.Sc Agriculture", "B.Sc Horticulture", "B.Tech Agricultural Engineering", "B.Sc Agribusiness"],
        "blurb": "Improves how food is grown - yield, resilience, soil health and sustainability.",
        "whatYouDo": ["Run field trials on varieties and practices",
                      "Study soil, pests and crop nutrition",
                      "Advise farmers and agri-businesses",
                      "Work on breeding and climate resilience"],
        "dayInLife": "Field plots through the season, laboratory analysis, and extension work with actual farmers.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-20 LPA", "senior": "Rs 20-45 LPA+ (ICAR scientist grade secure)"},
        "alternates": ["food-technologist", "agribusiness-manager", "environmental-scientist", "horticulturist"],
    },
    {
        "id": "food-technologist", "title": "Food Technologist", "cluster": "G", "family": "agriculture",
        "degrees": ["B.Tech Food Technology", "B.Tech Dairy Technology", "B.Sc Food Nutrition & Dietetics", "B.Sc Agriculture"],
        "blurb": "Develops food products and the processes that make them safe, stable and scalable.",
        "whatYouDo": ["Formulate products and run sensory testing",
                      "Design processing, packaging and shelf-life",
                      "Enforce food safety standards (FSSAI, HACCP)",
                      "Scale a recipe into a production line"],
        "dayInLife": "Pilot plant trials, tasting panels, and quality documentation.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-20 LPA", "senior": "Rs 20-50 LPA+"},
        "alternates": ["nutritionist", "chemical-engineer", "agricultural-scientist", "chef"],
    },
    {
        "id": "horticulturist", "title": "Horticulturist", "cluster": "G", "family": "agriculture",
        "degrees": ["B.Sc Horticulture", "B.Sc Agriculture", "B.Sc Forestry"],
        "blurb": "Specialises in fruit, vegetable, floriculture and plantation crops.",
        "whatYouDo": ["Manage orchards, nurseries and protected cultivation",
                      "Improve varieties and post-harvest handling",
                      "Advise on irrigation and crop protection",
                      "Develop high-value and export crops"],
        "dayInLife": "Field and greenhouse work driven by the season, plus market and supply-chain decisions.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-40 LPA+"},
        "alternates": ["agricultural-scientist", "agribusiness-manager", "environmental-scientist"],
    },
    {
        "id": "agribusiness-manager", "title": "Agribusiness Manager", "cluster": "E", "family": "agriculture",
        "degrees": ["B.Sc Agribusiness", "B.Sc Agriculture", "BBA", "B.Com", "B.Sc Horticulture"],
        "blurb": "Runs the business side of food and farming - supply chains, inputs, markets and agri-tech.",
        "whatYouDo": ["Manage procurement and supply chains from farm to market",
                      "Analyse commodity markets and pricing",
                      "Build farmer networks and producer organisations",
                      "Run agri-input, food processing or agri-tech operations"],
        "dayInLife": "Market data in the morning, field or mandi visits, and a logistics problem that changes weekly with the weather.",
        "topColleges": ["IIM Ahmedabad (Food & Agribusiness)", "IRMA Anand", "IARI New Delhi", "Symbiosis Institute of International Business"],
        "salary": {"entry": "Rs 4-10 LPA", "mid": "Rs 10-28 LPA", "senior": "Rs 28-70 LPA+"},
        "alternates": ["agricultural-scientist", "operations-manager", "business-analyst", "entrepreneur"],
    },
    {
        "id": "forest-officer", "title": "Forest Officer (IFS)", "cluster": "G", "family": "agriculture",
        "degrees": ["B.Sc Forestry", "B.Sc Agriculture", "B.Sc Environmental Science", "B.Sc Geology", "B.Sc Physics", "B.Sc Chemistry"],
        "blurb": "Manages forests and wildlife as a member of the Indian Forest Service.",
        "whatYouDo": ["Manage protected areas and forest resources",
                      "Enforce conservation law and tackle poaching",
                      "Handle human-wildlife conflict",
                      "Run afforestation and community forestry programmes"],
        "dayInLife": "Field patrols, administration, and negotiation between conservation and local livelihoods.",
        "entranceExams": [
            {"name": "UPSC Indian Forest Service", "when": "After graduation in a science or engineering subject",
             "opens": "The IFS - prelims shared with Civil Services"},
        ],
        "salary": {"entry": "Rs 7-12 LPA (plus housing and allowances)", "mid": "Rs 12-25 LPA", "senior": "Rs 25-40 LPA"},
        "alternates": ["wildlife-biologist", "civil-servant", "environmental-scientist"],
    },
]
