#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Career catalogue, part 4: depth for the thin domains.

The first three files covered the obvious careers and left some domains badly
under-served relative to how many students actually want them:

    Software & Data                6 careers   (the single most asked-for field)
    Law                            4
    Public Service & Policy        4
    Hospitality/Tourism/Lifestyle  5
    Medicine & Health Sciences     6
    Agriculture & Environment      5

A student who says "I want to work in technology" and is shown six options is
being under-served by the catalogue, not by the country. Same for a CEC or HEC
student, whose realistic paths concentrate in exactly the commerce, law, media
and public-service domains that were thinnest.

Same contract as part 1 - see demo_11_12_careers_stem.py for field meanings.
Degrees must exist in the client's streams workbook; alternates must resolve to
real career ids. build_demo_careers.py fails the build on either.
"""

CAREERS_EXTRA = [
    # ===================================================== SOFTWARE & DATA
    {
        "id": "full-stack-developer", "title": "Full-Stack Developer", "cluster": "B", "family": "software",
        "degrees": ["B.Tech Computer Science", "B.Tech CSE", "BCA", "B.Sc CS", "B.Sc Computer Science"],
        "blurb": "Builds both the part of a product people see and the part that makes it work.",
        "whatYouDo": ["Build interfaces users interact with",
                      "Build the server logic and database behind them",
                      "Own a feature from idea to deployment",
                      "Debug across the whole stack, wherever the fault actually is"],
        "dayInLife": "A feature that touches four layers, and a bug that could be in any of them.",
        "salary": {"entry": "Rs 5-20 LPA", "mid": "Rs 20-50 LPA", "senior": "Rs 50 LPA-1.5 Cr+"},
        "alternates": ["software-engineer", "mobile-app-developer", "ux-designer", "cloud-devops-engineer"],
    },
    {
        "id": "mobile-app-developer", "title": "Mobile App Developer", "cluster": "B", "family": "software",
        "degrees": ["B.Tech Computer Science", "B.Tech CSE", "BCA", "B.Sc CS", "B.Sc Computer Science"],
        "blurb": "Builds the apps people carry in their pocket, for Android and iOS.",
        "whatYouDo": ["Build and ship apps to the app stores",
                      "Work within battery, memory and offline constraints",
                      "Handle a huge range of devices and screen sizes",
                      "Respond to reviews and crash reports from real users"],
        "dayInLife": "A crash that only happens on one Android version, and a release checklist.",
        "salary": {"entry": "Rs 5-18 LPA", "mid": "Rs 18-45 LPA", "senior": "Rs 45 LPA-1.2 Cr+"},
        "alternates": ["full-stack-developer", "software-engineer", "ux-designer", "game-developer"],
    },
    {
        "id": "data-analyst", "title": "Data Analyst", "cluster": "B", "family": "software",
        "degrees": ["B.Sc Statistics", "B.Sc Data Science", "BBA Business Analytics", "B.Sc Economics",
                    "B.Com", "B.Sc Mathematics", "BCA", "B.Sc Computer Science"],
        "blurb": "Answers the questions a business asks of its own numbers.",
        "whatYouDo": ["Pull and clean data with SQL",
                      "Build dashboards people actually check",
                      "Investigate why a number moved",
                      "Present findings to teams who will act on them"],
        "dayInLife": "SQL, a dashboard, and explaining that the spike was a public holiday.",
        "buildNow": ["Learn SQL and Excel properly - both are learnable at school age",
                     "Analyse something you care about and publish the chart",
                     "Take Statistics or Economics if your board offers it"],
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-30 LPA", "senior": "Rs 30-70 LPA+"},
        "realityCheck": "One of the few technology routes genuinely open to commerce and humanities students without a B.Tech. Competition is heavy at entry; SQL fluency separates people fast.",
        "alternates": ["data-scientist", "business-analyst", "statistician", "business-intelligence-analyst"],
    },
    {
        "id": "business-intelligence-analyst", "title": "Business Intelligence Analyst", "cluster": "B", "family": "software",
        "degrees": ["BBA Business Analytics", "B.Sc Statistics", "B.Com", "B.Sc Data Science",
                    "BBA", "B.Sc Economics", "BCA"],
        "blurb": "Builds the reporting layer a company runs its decisions on.",
        "whatYouDo": ["Model data into something reportable",
                      "Build and maintain BI dashboards (Power BI, Tableau)",
                      "Define what each metric actually means",
                      "Automate the reports people were making by hand"],
        "dayInLife": "Data modelling, a dashboard rebuild, and a disagreement about how to define 'active user'.",
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-30 LPA", "senior": "Rs 30-65 LPA+"},
        "alternates": ["data-analyst", "business-analyst", "data-scientist", "database-administrator"],
    },
    {
        "id": "database-administrator", "title": "Database Administrator", "cluster": "B", "family": "software",
        "degrees": ["B.Tech Computer Science", "B.Tech CSE", "BCA", "B.Sc CS", "B.Sc Computer Science"],
        "blurb": "Keeps the data safe, fast and available - the part nobody notices until it breaks.",
        "whatYouDo": ["Design schemas and tune query performance",
                      "Run backups and rehearse recovery",
                      "Manage access and protect sensitive data",
                      "Plan capacity before it becomes a problem"],
        "dayInLife": "A slow query, a backup verification, and a migration planned for 2am.",
        "salary": {"entry": "Rs 4-14 LPA", "mid": "Rs 14-35 LPA", "senior": "Rs 35-80 LPA+"},
        "alternates": ["cloud-devops-engineer", "network-engineer", "software-engineer", "cybersecurity-analyst"],
    },
    {
        "id": "network-engineer", "title": "Network Engineer", "cluster": "B", "family": "software",
        "degrees": ["B.Tech Computer Science", "B.Tech CSE", "B.Tech ECE", "BCA", "B.Sc CS"],
        "blurb": "Designs and runs the networks everything else depends on.",
        "whatYouDo": ["Design network topology and routing",
                      "Diagnose faults across hardware and configuration",
                      "Secure and segment traffic",
                      "Keep uptime through failures nobody planned for"],
        "dayInLife": "A packet capture, a misconfigured switch, and a maintenance window.",
        "salary": {"entry": "Rs 3.5-12 LPA", "mid": "Rs 12-30 LPA", "senior": "Rs 30-70 LPA+"},
        "alternates": ["cloud-devops-engineer", "cybersecurity-analyst", "database-administrator", "it-support-specialist"],
    },
    {
        "id": "qa-engineer", "title": "QA / Test Engineer", "cluster": "B", "family": "software",
        "degrees": ["B.Tech Computer Science", "B.Tech CSE", "BCA", "B.Sc CS", "B.Sc Computer Science"],
        "blurb": "Finds what is broken before a customer does, and automates the finding.",
        "whatYouDo": ["Design test cases from requirements",
                      "Write automated test suites",
                      "Reproduce and document defects precisely",
                      "Argue for quality when a deadline says otherwise"],
        "dayInLife": "A failing test, a flaky one that is worse, and a release sign-off.",
        "salary": {"entry": "Rs 3.5-12 LPA", "mid": "Rs 12-28 LPA", "senior": "Rs 28-60 LPA+"},
        "realityCheck": "Often treated as an entry point rather than a career, which is a mistake - automation and performance testing pay comparably to development.",
        "alternates": ["software-engineer", "full-stack-developer", "cloud-devops-engineer"],
    },
    {
        "id": "it-support-specialist", "title": "IT Support Specialist", "cluster": "B", "family": "software",
        "degrees": ["BCA", "B.Sc CS", "B.Sc Computer Science", "B.Tech Computer Science"],
        "blurb": "Keeps an organisation's technology working for the people using it.",
        "whatYouDo": ["Diagnose and resolve hardware and software faults",
                      "Manage accounts, devices and access",
                      "Explain technical things to non-technical people patiently",
                      "Spot the pattern behind repeated tickets"],
        "dayInLife": "A ticket queue, a laptop that will not boot, and a rollout to plan.",
        "salary": {"entry": "Rs 2.5-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-40 LPA+"},
        "realityCheck": "The most accessible entry into technology - a BCA or a vocational IT course is enough. Progression depends on picking a specialism (cloud, security, networks) rather than staying on the helpdesk.",
        "alternates": ["network-engineer", "cloud-devops-engineer", "cybersecurity-analyst", "database-administrator"],
    },
    {
        "id": "technical-writer", "title": "Technical Writer", "cluster": "D", "family": "software",
        "degrees": ["BA English", "B.Tech Computer Science", "BCA", "B.Sc CS", "BA Journalism", "Content Creation"],
        "blurb": "Writes the documentation that decides whether a product can be used at all.",
        "whatYouDo": ["Turn engineering detail into something a reader can follow",
                      "Structure documentation so answers are findable",
                      "Test the instructions by following them",
                      "Work closely with engineers who assume too much"],
        "dayInLife": "Reading a spec, writing a guide, and discovering step 4 does not work.",
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-28 LPA", "senior": "Rs 28-60 LPA+"},
        "realityCheck": "A rare route where strong English plus technical curiosity beats a computer-science degree. Genuinely open to humanities students.",
        "alternates": ["editor", "software-engineer", "ux-designer", "journalist"],
    },
    {
        "id": "blockchain-developer", "title": "Blockchain Developer", "cluster": "B", "family": "software",
        "degrees": ["B.Tech Computer Science", "B.Tech CSE", "B.Sc CS", "BCA", "B.Sc Cybersecurity"],
        "blurb": "Builds decentralised systems and the contracts that run on them.",
        "whatYouDo": ["Write and audit smart contracts",
                      "Design systems where mistakes cannot be undone",
                      "Work on cryptography and consensus",
                      "Think adversarially about every line"],
        "dayInLife": "Contract logic, a security review, and testing against an attacker's imagination.",
        "salary": {"entry": "Rs 6-22 LPA", "mid": "Rs 22-55 LPA", "senior": "Rs 55 LPA-2 Cr+"},
        "realityCheck": "Volatile sector with real swings in hiring. The underlying skills - cryptography, distributed systems, security - transfer well if the market turns.",
        "alternates": ["software-engineer", "cybersecurity-analyst", "full-stack-developer"],
    },
    # ================================================== HOSPITALITY & SPORT
    {
        "id": "restaurant-manager", "title": "Restaurant Manager", "cluster": "H", "family": "hospitality",
        "degrees": ["BHM", "BHMCT", "Hotel Administration", "Hospitality Management", "Culinary Arts", "BBA"],
        "blurb": "Runs a restaurant as a business and as an experience, at the same time.",
        "whatYouDo": ["Run service and lead the floor team",
                      "Control food cost, wastage and margins",
                      "Handle complaints while service continues around you",
                      "Hire, roster and train staff"],
        "dayInLife": "Prep check, a full dinner service, and the day's numbers at midnight.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-50 LPA+"},
        "alternates": ["hotel-manager", "chef", "event-manager", "entrepreneur"],
    },
    {
        "id": "baker-patissier", "title": "Baker & Pâtissier", "cluster": "H", "family": "hospitality",
        "degrees": ["Culinary Arts", "BHM", "BHMCT", "Hotel Administration", "B.Sc Food Nutrition & Dietetics"],
        "blurb": "Specialises in bread, pastry and desserts - the most technical corner of a kitchen.",
        "whatYouDo": ["Work to precise ratios and temperatures",
                      "Develop products and manage shelf life",
                      "Start work very early, most days",
                      "Scale a recipe without losing what made it good"],
        "dayInLife": "A 4am start, several bakes running at once, and everything sold by noon.",
        "salary": {"entry": "Rs 2.5-6 LPA", "mid": "Rs 6-15 LPA", "senior": "Rs 15-45 LPA+ (own bakery)"},
        "realityCheck": "The most chemistry-like discipline in a kitchen and the least forgiving of guesswork. Early hours are permanent, not a phase.",
        "alternates": ["chef", "restaurant-manager", "food-technologist", "entrepreneur"],
    },
    {
        "id": "fitness-trainer", "title": "Fitness Trainer / Strength Coach", "cluster": "H", "family": "hospitality",
        "degrees": ["Physiotherapy", "B.Sc Food Nutrition & Dietetics", "BHM", "Hospitality Management", "B.Sc Psychology"],
        "blurb": "Trains people to move better and get stronger, safely.",
        "whatYouDo": ["Assess movement and design programmes",
                      "Coach technique and correct it live",
                      "Keep people coming back, which is the hard part",
                      "Build a client base, often self-employed"],
        "dayInLife": "Early and late sessions with a gap in the middle, and clients who need motivating more than instructing.",
        "salary": {"entry": "Rs 2.5-6 LPA", "mid": "Rs 6-18 LPA", "senior": "Rs 18-50 LPA+ (own studio or online)"},
        "alternates": ["sports-coach", "sports-scientist", "physiotherapist", "nutritionist"],
    },
    {
        "id": "cabin-crew", "title": "Cabin Crew / Airline Service", "cluster": "H", "family": "hospitality",
        "degrees": ["BHM", "Hospitality Management", "Tourism Management", "Travel & Tourism", "Hotel Administration"],
        "blurb": "Looks after passengers in the air, and is trained first as a safety professional.",
        "whatYouDo": ["Deliver safety procedures and emergency response",
                      "Look after passengers through long shifts",
                      "Handle medical incidents and difficult behaviour",
                      "Work rotating rosters across time zones"],
        "dayInLife": "A pre-flight briefing, several sectors, and a night stop somewhere else.",
        "salary": {"entry": "Rs 4-8 LPA", "mid": "Rs 8-18 LPA", "senior": "Rs 18-40 LPA+"},
        "realityCheck": "Recruited on service instinct and safety training, not on a specific degree. Physically demanding, with irregular sleep that some people never adjust to.",
        "alternates": ["travel-consultant", "hotel-manager", "event-manager"],
    },
    {
        "id": "adventure-guide", "title": "Adventure & Eco-Tourism Guide", "cluster": "H", "family": "hospitality",
        "degrees": ["Travel & Tourism", "Tourism Management", "BHM", "B.Sc Forestry", "B.Sc Environmental Science"],
        "blurb": "Leads people safely through places they could not go alone.",
        "whatYouDo": ["Lead treks, dives, climbs or wildlife trips",
                      "Carry responsibility for group safety",
                      "Read weather, terrain and people",
                      "Interpret the landscape so the trip means something"],
        "dayInLife": "Long days outdoors, an equipment check that matters, and a group whose pace you must manage.",
        "salary": {"entry": "Rs 2.5-6 LPA", "mid": "Rs 6-15 LPA", "senior": "Rs 15-40 LPA+ (own operation)"},
        "realityCheck": "Seasonal in most of India, so many guides pair it with a second income. Certification (mountaineering, dive, wilderness first aid) matters far more than the degree.",
        "alternates": ["travel-consultant", "wildlife-biologist", "sports-coach", "event-manager"],
    },
    {
        "id": "wellness-instructor", "title": "Yoga & Wellness Instructor", "cluster": "H", "family": "hospitality",
        "degrees": ["Physiotherapy", "B.Sc Psychology", "BHM", "Hospitality Management", "B.Sc Food Nutrition & Dietetics"],
        "blurb": "Teaches movement, breathing and recovery, in studios, resorts or online.",
        "whatYouDo": ["Plan and teach classes for mixed abilities",
                      "Adapt for injury and limitation safely",
                      "Build a following, often independently",
                      "Keep learning the anatomy behind the practice"],
        "dayInLife": "Morning and evening classes, private sessions between, and content to keep an audience.",
        "salary": {"entry": "Rs 2.5-6 LPA", "mid": "Rs 6-16 LPA", "senior": "Rs 16-45 LPA+"},
        "alternates": ["fitness-trainer", "physiotherapist", "nutritionist", "sports-coach"],
    },
    {
        "id": "pilot", "title": "Commercial Pilot", "cluster": "H", "family": "hospitality",
        "degrees": ["B.Sc Physics", "B.Sc Mathematics", "B.Tech Aerospace", "BHM", "Tourism Management"],
        "blurb": "Flies commercial aircraft, on a licence that takes years and money to earn.",
        "whatYouDo": ["Plan and fly sectors within tight procedure",
                      "Make decisions with incomplete information",
                      "Maintain currency through constant checks",
                      "Carry final responsibility for everyone on board"],
        "dayInLife": "Briefing, several sectors, and a standard of procedural discipline that never relaxes.",
        "entranceExams": [
            {"name": "DGCA Class 1 Medical", "when": "Before you start training", "opens": "Eligibility to train at all - do this first"},
            {"name": "Commercial Pilot Licence (CPL)", "when": "After Class 12 with Physics & Maths", "opens": "Flying training at a DGCA-approved school"},
            {"name": "Airline cadet programmes", "when": "Class 12 onward", "opens": "Sponsored routes with major carriers"},
        ],
        "salary": {"entry": "Rs 8-20 LPA (first officer)", "mid": "Rs 20-60 LPA", "senior": "Rs 60 LPA-1.5 Cr+ (captain)"},
        "realityCheck": "Physics and Maths at class 12 are mandatory, and self-funded CPL training costs upwards of Rs 40-60 lakh with no guaranteed job at the end. Take the Class 1 medical before spending anything.",
        "alternates": ["aerospace-engineer", "defence-officer", "cabin-crew", "travel-consultant"],
    },
    # ============================================================== LAW
    {
        "id": "ip-lawyer", "title": "Intellectual Property Lawyer", "cluster": "F", "family": "law",
        "degrees": ["BA LLB", "BBA LLB", "B.Sc LLB", "B.Com LLB", "LLB after graduation"],
        "blurb": "Protects patents, trademarks, copyright and designs - law with a technical core.",
        "whatYouDo": ["Draft and prosecute patent and trademark applications",
                      "Advise on infringement and licensing",
                      "Litigate IP disputes",
                      "Read enough science to argue about it"],
        "dayInLife": "A patent specification, a prior-art search, and an opposition deadline.",
        "salary": {"entry": "Rs 6-16 LPA", "mid": "Rs 16-45 LPA", "senior": "Rs 45 LPA-2 Cr+"},
        "realityCheck": "A science or engineering background is a real advantage here and is the one branch of law where B.Sc LLB pays off directly.",
        "alternates": ["corporate-lawyer", "legal-advisor", "cyber-law-specialist", "litigator"],
    },
    {
        "id": "cyber-law-specialist", "title": "Cyber Law & Data Privacy Specialist", "cluster": "F", "family": "law",
        "degrees": ["BA LLB", "BBA LLB", "B.Sc LLB", "B.Com LLB", "LLB after graduation"],
        "blurb": "Works on data protection, cybercrime and the law that is still catching up with technology.",
        "whatYouDo": ["Advise on data protection compliance",
                      "Handle breach response and regulator notification",
                      "Work on cybercrime prosecution or defence",
                      "Draft policies for how data may be used"],
        "dayInLife": "A privacy impact assessment, a breach clock ticking, and regulation that changed last month.",
        "salary": {"entry": "Rs 6-16 LPA", "mid": "Rs 16-45 LPA", "senior": "Rs 45 LPA-1.5 Cr+"},
        "alternates": ["corporate-lawyer", "compliance-officer", "cybersecurity-analyst", "legal-advisor"],
    },
    {
        "id": "human-rights-lawyer", "title": "Human Rights & Public Interest Lawyer", "cluster": "F", "family": "law",
        "degrees": ["BA LLB", "BBA LLB", "B.Com LLB", "B.Sc LLB", "LLB after graduation"],
        "blurb": "Litigates and advocates for people who could not otherwise reach the courts.",
        "whatYouDo": ["Take public interest litigation",
                      "Represent clients who cannot pay",
                      "Work with NGOs and civil-society organisations",
                      "Push for policy change through the courts"],
        "dayInLife": "Court, a field visit, and funding applications that keep the work alive.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-20 LPA", "senior": "Rs 20-50 LPA+"},
        "realityCheck": "Pays a fraction of corporate law for harder work. The people who sustain it usually plan their finances around it from the start.",
        "alternates": ["litigator", "policy-analyst", "social-worker", "judge"],
    },
    {
        "id": "legal-researcher", "title": "Legal Researcher & Analyst", "cluster": "F", "family": "law",
        "degrees": ["BA LLB", "BBA LLB", "B.Com LLB", "B.Sc LLB", "BA Political Science", "LLB after graduation"],
        "blurb": "Researches law for chambers, think-tanks, courts and legal publishers.",
        "whatYouDo": ["Research case law and legislative history",
                      "Write briefing notes and opinions",
                      "Support judges, senior counsel or policy teams",
                      "Track legislation as it changes"],
        "dayInLife": "Databases, precedent, and a memo that must be exactly right.",
        "salary": {"entry": "Rs 4-10 LPA", "mid": "Rs 10-25 LPA", "senior": "Rs 25-60 LPA+"},
        "alternates": ["litigator", "policy-analyst", "judge", "legal-advisor"],
    },
    # ============================================== PUBLIC SERVICE & POLICY
    {
        "id": "police-officer", "title": "Police Officer (State Services)", "cluster": "F", "family": "civil_services",
        "degrees": ["BA Political Science", "BA Sociology", "BA History", "B.Com", "B.Sc Physics",
                    "BA LLB", "B.Tech Computer Science", "BA Psychology"],
        "blurb": "Enforces law and keeps public order, through the state police services.",
        "whatYouDo": ["Investigate crime and build cases",
                      "Lead a station or a unit",
                      "Manage public order and emergencies",
                      "Work with communities to prevent crime"],
        "dayInLife": "Unpredictable by definition, on shifts that ignore the calendar.",
        "entranceExams": [
            {"name": "State PSC (Deputy SP)", "when": "After graduation", "opens": "State police services"},
            {"name": "UPSC Civil Services (IPS)", "when": "After graduation", "opens": "The Indian Police Service"},
            {"name": "SSC CPO / state SI exams", "when": "After graduation", "opens": "Sub-inspector entry"},
        ],
        "salary": {"entry": "Rs 6-11 LPA (plus housing and allowances)", "mid": "Rs 11-22 LPA", "senior": "Rs 22-40 LPA"},
        "alternates": ["civil-servant", "defence-officer", "litigator", "forensic-scientist"],
    },
    {
        "id": "customs-officer", "title": "Customs & Revenue Officer", "cluster": "F", "family": "civil_services",
        "degrees": ["B.Com", "B.Com Hons", "BA Economics", "B.Sc Economics", "BBA", "BA Political Science"],
        "blurb": "Works on tax, customs and revenue enforcement for the government.",
        "whatYouDo": ["Assess and collect indirect and direct tax",
                      "Investigate evasion and smuggling",
                      "Clear goods at ports and airports",
                      "Interpret a body of rules that changes yearly"],
        "dayInLife": "Assessment files, an inspection, and a dispute headed for appeal.",
        "entranceExams": [
            {"name": "UPSC Civil Services (IRS)", "when": "After graduation", "opens": "Indian Revenue Service"},
            {"name": "SSC CGL", "when": "After graduation", "opens": "Inspector and Examiner grades in customs and income tax"},
        ],
        "salary": {"entry": "Rs 6-11 LPA (plus allowances)", "mid": "Rs 11-22 LPA", "senior": "Rs 22-40 LPA"},
        "realityCheck": "SSC CGL makes this one of the most reachable government routes for a commerce graduate - far better odds than UPSC, with real responsibility.",
        "alternates": ["civil-servant", "chartered-accountant", "auditor", "compliance-officer"],
    },
    {
        "id": "ngo-programme-manager", "title": "NGO / Development Programme Manager", "cluster": "F", "family": "civil_services",
        "degrees": ["BA Sociology", "BA Public Policy", "BA Political Science", "BA Psychology",
                    "BA Anthropology", "BA Economics", "B.Com", "BBA"],
        "blurb": "Runs development programmes - the money, the people and whether it actually worked.",
        "whatYouDo": ["Design programmes and write the proposals that fund them",
                      "Manage budgets, teams and field operations",
                      "Measure impact honestly, including when it is small",
                      "Report to donors and communities alike"],
        "dayInLife": "A field review, a donor report, and a budget that must stretch.",
        "salary": {"entry": "Rs 3.5-9 LPA", "mid": "Rs 9-22 LPA", "senior": "Rs 22-55 LPA+ (large foundations higher)"},
        "alternates": ["social-worker", "policy-analyst", "public-health-specialist", "operations-manager"],
    },
    {
        "id": "librarian-information-scientist", "title": "Librarian & Information Scientist", "cluster": "F", "family": "humanities",
        "degrees": ["BA English", "BA History", "BA Linguistics", "B.Sc Computer Science", "BA Philosophy", "BCA"],
        "blurb": "Organises knowledge so people can find it - in libraries, archives and increasingly databases.",
        "whatYouDo": ["Catalogue and classify collections",
                      "Build and manage digital repositories",
                      "Teach people how to research properly",
                      "Preserve material that would otherwise be lost"],
        "dayInLife": "Cataloguing, a research enquiry, and a digitisation project.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-16 LPA", "senior": "Rs 16-35 LPA+"},
        "alternates": ["historian", "curator", "technical-writer", "teacher"],
    },
    {
        "id": "education-administrator", "title": "School Principal / Education Administrator", "cluster": "F", "family": "humanities",
        "degrees": ["BA English", "BA History", "B.Sc Physics", "B.Sc Mathematics", "BA Economics",
                    "BA Psychology", "B.Sc Chemistry", "BA Political Science"],
        "blurb": "Runs a school - the teaching, the staff, the finances and the parents.",
        "whatYouDo": ["Lead teaching quality and curriculum",
                      "Manage staff, budgets and admissions",
                      "Handle parents, boards and inspections",
                      "Set the culture the school actually has"],
        "dayInLife": "A staff issue before assembly, a parent meeting, and a budget review.",
        "salary": {"entry": "Rs 5-10 LPA (after teaching years)", "mid": "Rs 10-25 LPA", "senior": "Rs 25-60 LPA+ (international schools)"},
        "realityCheck": "Nobody starts here - it is 8-15 years of teaching first, plus usually an M.Ed or management qualification.",
        "alternates": ["teacher", "special-educator", "hr-manager", "professor"],
    },
    # ================================================ MEDICINE & ALLIED HEALTH
    {
        "id": "paramedic", "title": "Paramedic / Emergency Care Technician", "cluster": "C", "family": "allied_health",
        "degrees": ["B.Sc Nursing", "Physiotherapy", "Medical Laboratory Technology", "Radiology / Imaging"],
        "blurb": "Delivers emergency care where the emergency is, before hospital.",
        "whatYouDo": ["Assess and stabilise critically ill patients",
                      "Perform emergency procedures under pressure",
                      "Make decisions alone, quickly, on partial information",
                      "Hand over cleanly to the receiving team"],
        "dayInLife": "Long quiet stretches broken by calls where minutes matter.",
        "salary": {"entry": "Rs 2.5-6 LPA", "mid": "Rs 6-14 LPA", "senior": "Rs 14-30 LPA+"},
        "realityCheck": "Emotionally heavy and comparatively poorly paid in India, though the skill is respected everywhere and travels internationally.",
        "alternates": ["nurse", "doctor", "radiographer", "physiotherapist"],
    },
    {
        "id": "speech-therapist", "title": "Speech & Language Therapist", "cluster": "C", "family": "allied_health",
        "degrees": ["Occupational Therapy", "Physiotherapy", "B.Sc Psychology", "B.Sc Nursing"],
        "blurb": "Treats speech, language and swallowing difficulties, in children and after injury.",
        "whatYouDo": ["Assess communication and swallowing",
                      "Deliver therapy over long courses",
                      "Work with families and schools",
                      "Measure progress that is often slow"],
        "dayInLife": "Sessions with children and stroke patients, and a great deal of patience.",
        "salary": {"entry": "Rs 3-6 LPA", "mid": "Rs 6-15 LPA", "senior": "Rs 15-40 LPA+ (private practice)"},
        "alternates": ["occupational-therapist", "audiologist", "special-educator", "psychologist"],
    },
    {
        "id": "audiologist", "title": "Audiologist", "cluster": "C", "family": "allied_health",
        "degrees": ["Occupational Therapy", "B.Sc Psychology", "B.Sc Nursing", "Optometry"],
        "blurb": "Diagnoses hearing and balance disorders and manages hearing technology.",
        "whatYouDo": ["Test hearing across ages, including newborns",
                      "Fit and tune hearing aids and implants",
                      "Diagnose balance disorders",
                      "Counsel families through diagnosis"],
        "dayInLife": "Booth testing, device fitting, and a newborn screening list.",
        "salary": {"entry": "Rs 3-6 LPA", "mid": "Rs 6-15 LPA", "senior": "Rs 15-38 LPA+"},
        "alternates": ["speech-therapist", "optometrist", "occupational-therapist", "medical-lab-scientist"],
    },
    {
        "id": "genetic-counsellor", "title": "Genetic Counsellor", "cluster": "C", "family": "allied_health",
        "degrees": ["Genetics", "B.Sc Biotechnology", "Biotechnology", "B.Sc Nursing", "Biochemistry"],
        "blurb": "Helps families understand inherited risk and what to do about it.",
        "whatYouDo": ["Interpret genetic test results",
                      "Explain risk to families in plain terms",
                      "Support decisions that are rarely simple",
                      "Work alongside clinicians and laboratories"],
        "dayInLife": "Long consultations, careful pedigree work, and conversations that change lives.",
        "salary": {"entry": "Rs 4-9 LPA", "mid": "Rs 9-22 LPA", "senior": "Rs 22-50 LPA+"},
        "realityCheck": "Small but growing field in India as genomic testing spreads. Needs a master's; the counselling skill matters as much as the genetics.",
        "alternates": ["geneticist", "medical-researcher", "psychologist", "biotechnologist"],
    },
    {
        "id": "hospital-administrator", "title": "Hospital Administrator", "cluster": "E", "family": "allied_health",
        "degrees": ["B.Sc Nursing", "BBA", "B.Com", "MBBS", "BMS", "Medical Laboratory Technology"],
        "blurb": "Runs the non-clinical side of a hospital so the clinical side can work.",
        "whatYouDo": ["Manage operations, staffing and patient flow",
                      "Control budgets and procurement",
                      "Meet accreditation and regulatory standards",
                      "Resolve the friction between clinical and commercial pressures"],
        "dayInLife": "Bed occupancy, a supplier issue, and an accreditation audit.",
        "salary": {"entry": "Rs 4-10 LPA", "mid": "Rs 10-28 LPA", "senior": "Rs 28-70 LPA+"},
        "alternates": ["operations-manager", "public-health-specialist", "hr-manager", "business-analyst"],
    },
    # ================================================ AGRICULTURE & ENVIRONMENT
    {
        "id": "fisheries-scientist", "title": "Fisheries & Aquaculture Scientist", "cluster": "G", "family": "agriculture",
        "degrees": ["B.F.Sc Fisheries", "B.Sc Agriculture", "B.Sc Environmental Science", "B.Sc Biotechnology"],
        "blurb": "Works on fish farming, marine resources and the science behind both.",
        "whatYouDo": ["Manage aquaculture systems and water quality",
                      "Study fish health, breeding and nutrition",
                      "Advise on sustainable harvesting",
                      "Support processing and export standards"],
        "dayInLife": "Pond or hatchery work, water testing, and a harvest cycle to plan.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-40 LPA+"},
        "realityCheck": "India is among the world's largest fish producers and the sector is short of qualified people - an uncrowded route with real demand.",
        "alternates": ["agricultural-scientist", "environmental-scientist", "food-technologist", "wildlife-biologist"],
    },
    {
        "id": "dairy-technologist", "title": "Dairy Technologist", "cluster": "G", "family": "agriculture",
        "degrees": ["B.Tech Dairy Technology", "B.Tech Food Technology", "B.Sc Agriculture", "B.Sc Food Nutrition & Dietetics"],
        "blurb": "Works on milk and its products - processing, safety, and the science of it.",
        "whatYouDo": ["Run and improve dairy processing",
                      "Develop products and manage shelf life",
                      "Enforce hygiene and quality standards",
                      "Work with cooperatives and supply chains"],
        "dayInLife": "Plant floor, laboratory checks, and a cold chain that cannot break.",
        "salary": {"entry": "Rs 3.5-8 LPA", "mid": "Rs 8-20 LPA", "senior": "Rs 20-45 LPA+"},
        "alternates": ["food-technologist", "agricultural-scientist", "chemical-engineer", "agribusiness-manager"],
    },
    {
        "id": "soil-scientist", "title": "Soil & Water Scientist", "cluster": "G", "family": "agriculture",
        "degrees": ["B.Sc Agriculture", "B.Sc Environmental Science", "B.Sc Geology", "B.Sc Chemistry", "B.Sc Forestry"],
        "blurb": "Studies soil health, irrigation and water use - the base layer of food production.",
        "whatYouDo": ["Test and map soil chemistry and structure",
                      "Design irrigation and drainage",
                      "Advise on fertiliser and land restoration",
                      "Work on salinity, erosion and groundwater"],
        "dayInLife": "Field sampling in season, laboratory analysis after, and recommendations farmers can act on.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-42 LPA+"},
        "alternates": ["agricultural-scientist", "environmental-scientist", "geologist", "horticulturist"],
    },
    {
        "id": "sustainability-analyst", "title": "Sustainability & ESG Analyst", "cluster": "G", "family": "agriculture",
        "degrees": ["B.Sc Environmental Science", "B.Sc Economics", "B.Com", "BBA",
                    "B.Tech Environmental Engineering", "B.Sc Statistics", "BA Economics"],
        "blurb": "Measures and reports what an organisation does to the environment, and what it should do instead.",
        "whatYouDo": ["Measure emissions, water and waste footprints",
                      "Prepare ESG and sustainability disclosures",
                      "Advise on decarbonisation and compliance",
                      "Challenge claims that do not survive the data"],
        "dayInLife": "Emissions data, a disclosure deadline, and a business unit that dislikes the finding.",
        "salary": {"entry": "Rs 4-11 LPA", "mid": "Rs 11-28 LPA", "senior": "Rs 28-70 LPA+"},
        "realityCheck": "Growing quickly on the back of mandatory disclosure rules, and unusually open to commerce and economics graduates as well as science ones.",
        "alternates": ["environmental-scientist", "business-analyst", "policy-analyst", "environmental-engineer"],
    },
    # ============================================================ ENGINEERING
    {
        "id": "quality-engineer", "title": "Quality & Reliability Engineer", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech Mechanical", "B.Tech Chemical", "B.Tech ECE", "B.Tech EEE", "B.Tech Food Technology"],
        "blurb": "Makes sure what is manufactured actually meets specification, every time.",
        "whatYouDo": ["Design inspection and testing regimes",
                      "Investigate defects to root cause",
                      "Run statistical process control",
                      "Hold production to standard when schedules push back"],
        "dayInLife": "Inspection data, a failure investigation, and a supplier audit.",
        "salary": {"entry": "Rs 3.5-9 LPA", "mid": "Rs 9-22 LPA", "senior": "Rs 22-50 LPA+"},
        "alternates": ["mechanical-engineer", "systems-engineer", "chemical-engineer", "qa-engineer"],
    },
    {
        "id": "building-services-engineer", "title": "Building Services (HVAC) Engineer", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech Mechanical", "B.Tech EEE", "B.Tech Civil", "B.Tech Environmental Engineering"],
        "blurb": "Designs the heating, cooling, water and power systems inside buildings.",
        "whatYouDo": ["Size and design HVAC and plumbing systems",
                      "Model energy performance",
                      "Coordinate with architects and structural engineers",
                      "Commission systems and fix what does not perform"],
        "dayInLife": "Load calculations, a coordination clash, and a site commissioning visit.",
        "salary": {"entry": "Rs 3.5-9 LPA", "mid": "Rs 9-22 LPA", "senior": "Rs 22-55 LPA+"},
        "alternates": ["mechanical-engineer", "renewable-energy-engineer", "civil-engineer", "architect"],
    },
    {
        "id": "water-resources-engineer", "title": "Water Resources Engineer", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech Civil", "B.Tech Environmental Engineering", "B.Tech Agricultural Engineering", "B.Sc Geology"],
        "blurb": "Designs how water is stored, moved, treated and kept away from where it should not be.",
        "whatYouDo": ["Design dams, canals, drainage and supply networks",
                      "Model floods and groundwater",
                      "Plan irrigation at scale",
                      "Work on climate resilience for water systems"],
        "dayInLife": "Hydraulic modelling, a site survey, and a monsoon design case.",
        "salary": {"entry": "Rs 3.5-9 LPA", "mid": "Rs 9-22 LPA", "senior": "Rs 22-55 LPA+"},
        "alternates": ["civil-engineer", "environmental-engineer", "geologist", "urban-planner"],
    },
    {
        "id": "safety-engineer", "title": "Industrial Safety Engineer", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech Chemical", "B.Tech Mechanical", "B.Tech Civil", "B.Tech Environmental Engineering", "B.Tech EEE"],
        "blurb": "Keeps industrial sites from hurting the people who work on them.",
        "whatYouDo": ["Assess hazards and design controls",
                      "Investigate incidents and near-misses",
                      "Run safety training and audits",
                      "Stop work when it is not safe, and defend that decision"],
        "dayInLife": "A site walk, a risk assessment, and a conversation about a shortcut somebody took.",
        "salary": {"entry": "Rs 3.5-9 LPA", "mid": "Rs 9-22 LPA", "senior": "Rs 22-55 LPA+"},
        "alternates": ["chemical-engineer", "quality-engineer", "systems-engineer", "environmental-engineer"],
    },
    {
        "id": "packaging-technologist", "title": "Packaging Technologist", "cluster": "A", "family": "engineering",
        "degrees": ["B.Tech Food Technology", "B.Tech Chemical", "B.Tech Mechanical", "B.Sc Chemistry", "Product Design"],
        "blurb": "Designs packaging that protects a product, survives transport and is not wasteful.",
        "whatYouDo": ["Select materials and design structures",
                      "Test for drop, compression and shelf life",
                      "Cut cost and material without losing protection",
                      "Meet food-contact and sustainability regulation"],
        "dayInLife": "Material trials, a drop-test rig, and a supplier negotiation about grammage.",
        "salary": {"entry": "Rs 3.5-9 LPA", "mid": "Rs 9-20 LPA", "senior": "Rs 20-45 LPA+"},
        "alternates": ["food-technologist", "product-designer", "chemical-engineer", "materials-scientist"],
    },
    # ================================================ MEDIA & COMMUNICATION
    {
        "id": "sound-engineer", "title": "Sound Engineer / Audio Producer", "cluster": "D", "family": "media",
        "degrees": ["Film & Television", "Broadcasting", "Digital Media", "Mass Communication", "B.Des"],
        "blurb": "Records, mixes and masters sound for music, film, podcasts and live events.",
        "whatYouDo": ["Record and mix multi-track audio",
                      "Run live sound for events",
                      "Design sound for film and games",
                      "Master to the standard each platform expects"],
        "dayInLife": "A session, a mix revision, and an ear that needs rest.",
        "salary": {"entry": "Rs 2.5-7 LPA", "mid": "Rs 7-20 LPA", "senior": "Rs 20-55 LPA+"},
        "alternates": ["cinematographer", "filmmaker", "content-creator", "media-manager"],
    },
    {
        "id": "screenwriter", "title": "Screenwriter", "cluster": "D", "family": "media",
        "degrees": ["Film & Television", "BA English", "Mass Communication", "BA Journalism", "Content Creation"],
        "blurb": "Writes the scripts films, series and advertising are built from.",
        "whatYouDo": ["Develop story, structure and character",
                      "Write and rewrite to notes, repeatedly",
                      "Pitch ideas to people who will say no",
                      "Work to format and production constraints"],
        "dayInLife": "Pages in the morning, notes in the afternoon, and a rewrite that is the fourth.",
        "salary": {"entry": "Project-based, often modest", "mid": "Rs 6-25 LPA", "senior": "Rs 25 LPA-uncapped"},
        "realityCheck": "Income is project-based and irregular. Most working screenwriters also write for advertising, corporate video or streaming to smooth it out.",
        "alternates": ["author", "filmmaker", "editor", "content-creator"],
    },
    {
        "id": "social-media-manager", "title": "Social Media Manager", "cluster": "E", "family": "media",
        "degrees": ["Digital Media", "Mass Communication", "Advertising", "BA Journalism", "BBA", "Content Creation"],
        "blurb": "Runs an organisation's presence and community on social platforms.",
        "whatYouDo": ["Plan and publish content calendars",
                      "Grow and moderate a community",
                      "Run paid social alongside organic",
                      "Handle the day something goes wrong publicly"],
        "dayInLife": "Scheduling, replies, performance review, and a comment thread to manage.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-22 LPA", "senior": "Rs 22-55 LPA+"},
        "alternates": ["digital-marketer", "content-creator", "brand-manager", "public-relations-specialist"],
    },
    {
        "id": "news-anchor", "title": "News Anchor / Broadcast Presenter", "cluster": "D", "family": "media",
        "degrees": ["Broadcasting", "Journalism", "BA Journalism", "Mass Communication", "BA Mass Communication", "BA Political Science"],
        "blurb": "Presents news and programmes live, and carries the credibility of what is said.",
        "whatYouDo": ["Present live to camera, unscripted when it matters",
                      "Research and prepare the stories you read",
                      "Interview under time pressure",
                      "Hold a line when a broadcast goes wrong"],
        "dayInLife": "Prep, rehearsal, and a live bulletin where nothing can be taken back.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-25 LPA", "senior": "Rs 25 LPA-1.5 Cr+ (national anchors)"},
        "alternates": ["journalist", "media-manager", "public-relations-specialist", "content-creator"],
    },
    # ================================================== COMMERCE & FINANCE
    {
        "id": "tax-consultant", "title": "Tax Consultant", "cluster": "E", "family": "commerce",
        "degrees": ["B.Com", "B.Com Hons", "CA", "CMA", "ACCA", "BBA Finance", "B.Com LLB"],
        "blurb": "Advises individuals and businesses on tax, and defends the position taken.",
        "whatYouDo": ["Prepare and file returns",
                      "Plan structures within the law",
                      "Represent clients in assessments and appeals",
                      "Keep pace with a code that changes every budget"],
        "dayInLife": "Filings, a notice from the department, and a client wanting a number to be smaller.",
        "salary": {"entry": "Rs 3.5-9 LPA", "mid": "Rs 9-25 LPA", "senior": "Rs 25-80 LPA+ (own practice)"},
        "alternates": ["chartered-accountant", "auditor", "compliance-officer", "customs-officer"],
    },
    {
        "id": "insurance-underwriter", "title": "Insurance Underwriter", "cluster": "E", "family": "commerce",
        "degrees": ["B.Com", "BBA", "B.Sc Statistics", "Actuarial Science", "B.Sc Economics", "BBA Finance", "BA Economics"],
        "blurb": "Decides what risk an insurer will take on, and at what price.",
        "whatYouDo": ["Assess risk on proposals",
                      "Set terms, exclusions and pricing",
                      "Balance growth against loss ratio",
                      "Work with actuaries and claims teams"],
        "dayInLife": "Case files, a pricing decision, and a portfolio review.",
        "salary": {"entry": "Rs 3.5-9 LPA", "mid": "Rs 9-24 LPA", "senior": "Rs 24-60 LPA+"},
        "alternates": ["actuary", "financial-analyst", "banker", "auditor"],
    },
    {
        "id": "retail-manager", "title": "Retail & Category Manager", "cluster": "E", "family": "commerce",
        "degrees": ["BBA", "BMS", "B.Com", "BBM", "BBA Business Analytics"],
        "blurb": "Decides what a shop or platform sells, at what price, and makes the margin work.",
        "whatYouDo": ["Select and buy the product range",
                      "Set pricing and promotions",
                      "Manage stock, markdowns and supplier terms",
                      "Read sales data and act on it weekly"],
        "dayInLife": "Sales numbers, a supplier meeting, and a range decision for next season.",
        "salary": {"entry": "Rs 3.5-9 LPA", "mid": "Rs 9-25 LPA", "senior": "Rs 25-70 LPA+"},
        "alternates": ["operations-manager", "brand-manager", "business-analyst", "marketing-manager"],
    },
    {
        "id": "real-estate-analyst", "title": "Real Estate & Infrastructure Analyst", "cluster": "E", "family": "commerce",
        "degrees": ["B.Com", "BBA Finance", "B.Sc Finance", "B.Sc Economics", "B.Planning", "BBA", "BA Economics"],
        "blurb": "Values property and infrastructure projects and advises on whether they are worth building.",
        "whatYouDo": ["Model project cash flows and returns",
                      "Value assets and analyse markets",
                      "Assess planning, legal and construction risk",
                      "Advise investors and developers"],
        "dayInLife": "A feasibility model, a site visit, and an investment committee paper.",
        "salary": {"entry": "Rs 4-11 LPA", "mid": "Rs 11-30 LPA", "senior": "Rs 30-80 LPA+"},
        "alternates": ["financial-analyst", "urban-planner", "construction-manager", "investment-banker"],
    },
    # ============================================================== DESIGN
    {
        "id": "jewellery-designer", "title": "Jewellery & Accessory Designer", "cluster": "D", "family": "design",
        "degrees": ["Fashion Design", "B.Des", "BFA", "Product Design"],
        "blurb": "Designs jewellery and accessories, where craft and manufacture meet.",
        "whatYouDo": ["Sketch and CAD-model pieces",
                      "Work with karigars, casters and stone setters",
                      "Balance material cost against design",
                      "Develop collections to a price point"],
        "dayInLife": "Design work, a workshop visit, and a sample that needs another iteration.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-50 LPA+ (own label)"},
        "alternates": ["fashion-designer", "product-designer", "textile-designer", "artist"],
    },
    {
        "id": "motion-graphics-designer", "title": "Motion Graphics Designer", "cluster": "D", "family": "design",
        "degrees": ["Animation", "Communication Design", "B.Des", "VFX", "Digital Media", "BFA"],
        "blurb": "Makes design move - titles, explainers, adverts and interface animation.",
        "whatYouDo": ["Animate typography, illustration and interface",
                      "Storyboard short-form pieces",
                      "Work to brand systems and tight formats",
                      "Deliver fast, often daily"],
        "dayInLife": "After Effects, a client revision, and a render that takes longer than the edit.",
        "salary": {"entry": "Rs 3-9 LPA", "mid": "Rs 9-24 LPA", "senior": "Rs 24-60 LPA+"},
        "alternates": ["animator", "graphic-designer", "vfx-artist", "ux-designer"],
    },
    {
        "id": "exhibition-designer", "title": "Exhibition & Retail Space Designer", "cluster": "D", "family": "design",
        "degrees": ["Interior Design", "B.Des", "B.Arch", "Product Design", "BFA"],
        "blurb": "Designs spaces people walk through - shops, museums, stands and installations.",
        "whatYouDo": ["Design spatial layout and visitor flow",
                      "Design fixtures, graphics and lighting",
                      "Work to build budgets and short install windows",
                      "Be on site through the build"],
        "dayInLife": "Drawings and models, a fabricator call, and an overnight install.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-20 LPA", "senior": "Rs 20-50 LPA+"},
        "alternates": ["interior-designer", "architect", "curator", "graphic-designer"],
    },
    # ================================================ HUMANITIES & SCIENCES
    {
        "id": "archaeologist", "title": "Archaeologist", "cluster": "G", "family": "humanities",
        "degrees": ["BA History", "BA Anthropology", "BA Geography", "B.Sc Geology"],
        "blurb": "Recovers and interprets the material past, in the field and the laboratory.",
        "whatYouDo": ["Survey and excavate sites",
                      "Record and conserve finds",
                      "Date and interpret material evidence",
                      "Publish, and advise on heritage protection"],
        "dayInLife": "Field seasons of slow, careful digging, then months of analysis and writing.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-40 LPA+ (ASI and academia)"},
        "alternates": ["historian", "curator", "anthropologist", "geologist"],
    },
    {
        "id": "translator-interpreter", "title": "Translator & Interpreter", "cluster": "F", "family": "humanities",
        "degrees": ["BA Linguistics", "BA English", "BA International Relations", "BA History", "BA Philosophy"],
        "blurb": "Moves meaning between languages, in documents or in real time.",
        "whatYouDo": ["Translate documents accurately and idiomatically",
                      "Interpret live at meetings and conferences",
                      "Localise content for a different culture, not just language",
                      "Specialise - legal, medical and technical pay most"],
        "dayInLife": "Either deep solitary document work, or intense live sessions with no undo.",
        "salary": {"entry": "Rs 3-8 LPA", "mid": "Rs 8-22 LPA", "senior": "Rs 22-60 LPA+ (conference interpreting highest)"},
        "realityCheck": "Machine translation has taken the low end of this market. What remains, and pays well, is anything where being wrong is expensive.",
        "alternates": ["linguist", "author", "diplomat", "editor"],
    },
    {
        "id": "career-counsellor", "title": "Career Counsellor", "cluster": "F", "family": "humanities",
        "degrees": ["BA Psychology", "B.Sc Psychology", "BA Sociology", "BA English", "BBA"],
        "blurb": "Helps students and adults work out what to do next, and why.",
        "whatYouDo": ["Assess interests, aptitude and circumstances",
                      "Explain options students have never heard of",
                      "Manage family expectations alongside the student's",
                      "Keep current on entrances, courses and the job market"],
        "dayInLife": "Sessions with students, a worried parent, and reading to stay current.",
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-45 LPA+ (private practice)"},
        "alternates": ["psychologist", "teacher", "special-educator", "hr-manager"],
    },
    {
        "id": "forensic-scientist", "title": "Forensic Scientist", "cluster": "G", "family": "sciences",
        "degrees": ["B.Sc Chemistry", "B.Sc Biotechnology", "Genetics", "Microbiology", "Biochemistry", "B.Sc Physics"],
        "blurb": "Analyses physical evidence for criminal investigations, and defends it in court.",
        "whatYouDo": ["Analyse DNA, toxicology, documents or ballistics",
                      "Maintain chain of custody without exception",
                      "Write reports that will be challenged",
                      "Give expert evidence under cross-examination"],
        "dayInLife": "Laboratory analysis, meticulous documentation, and occasional court appearances.",
        "salary": {"entry": "Rs 3.5-8 LPA", "mid": "Rs 8-20 LPA", "senior": "Rs 20-45 LPA+"},
        "alternates": ["chemist", "geneticist", "medical-lab-scientist", "police-officer"],
    },
    {
        "id": "astronomer", "title": "Astronomer / Astrophysicist", "cluster": "G", "family": "sciences",
        "degrees": ["B.Sc Physics", "B.Sc Mathematics", "B.Tech Aerospace"],
        "blurb": "Studies stars, galaxies and the physics of the universe.",
        "whatYouDo": ["Analyse observational data from telescopes and satellites",
                      "Build computational models of physical systems",
                      "Write and defend telescope-time proposals",
                      "Publish, and collaborate internationally"],
        "dayInLife": "Overwhelmingly computational - large datasets, simulation code and papers.",
        "topColleges": ["IISc Bengaluru", "IUCAA Pune", "IISER Pune / Kolkata", "TIFR Mumbai", "Raman Research Institute"],
        "salary": {"entry": "Rs 4-9 LPA (fellowship during PhD)", "mid": "Rs 9-22 LPA", "senior": "Rs 22-50 LPA+"},
        "realityCheck": "Very few permanent posts and a long PhD-plus-postdoc road. The computational and statistical skills transfer strongly into data science, which is where many end up.",
        "alternates": ["physicist", "research-scientist", "data-scientist", "aerospace-engineer"],
    },
]
