#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Career catalogue, part 2: commerce, finance, management, law, public service.

Same contract as part 1 - see demo_11_12_careers_stem.py for the field meanings.
"""

CAREERS_COMMERCE = [
    # ------------------------------------------------------- ACCOUNTING & AUDIT
    {
        "id": "chartered-accountant", "title": "Chartered Accountant (CA)", "cluster": "E", "family": "commerce",
        "degrees": ["CA", "B.Com", "B.Com Hons", "B.Sc Finance", "BBA Finance"],
        "blurb": "Audits, advises and signs off on the financial truth of a business.",
        "whatYouDo": ["Audit financial statements and test whether they are true",
                      "Advise on tax structure and compliance",
                      "Handle mergers, valuations and due diligence",
                      "Sign off on filings, with your name and liability attached"],
        "dayInLife": "During audit season, very long days inside a client's books. Outside it, advisory work and client meetings.",
        "entranceExams": [
            {"name": "CA Foundation", "when": "After Class 12, Jun & Dec", "opens": "Entry to the ICAI qualification"},
            {"name": "CA Intermediate", "when": "After Foundation", "opens": "Articleship - three years of paid practical training"},
            {"name": "CA Final", "when": "After articleship", "opens": "Membership of ICAI"},
        ],
        "afterSchool": [
            {"stage": "CA Foundation", "years": "Straight after Class 12", "what": "Can be taken alongside a B.Com"},
            {"stage": "Intermediate + 3-year articleship", "years": "3-4 years", "what": "Paid training inside a practising firm"},
            {"stage": "CA Final", "years": "4-5 years total", "what": "Then practice, industry, or a Big Four firm"},
        ],
        "topColleges": ["ICAI (the qualification itself)", "SRCC / Hindu, Delhi (for the parallel B.Com)",
                        "St Xavier's Mumbai / Kolkata", "Christ University Bengaluru"],
        "coreSkills": ["Accounting standards", "Tax law", "Audit scepticism", "Excel", "Explaining numbers to non-finance people"],
        "buildNow": ["Take Accountancy in class 11-12 if available - it removes a real early hurdle",
                     "Start CA Foundation right after boards; the earlier you begin the earlier you qualify",
                     "Get genuinely fast at Excel"],
        "salary": {"entry": "Rs 8-14 LPA (fresh CA)", "mid": "Rs 14-35 LPA", "senior": "Rs 35 LPA-1.5 Cr+ (partner)"},
        "realityCheck": "Pass rates at each level are low and many take multiple attempts; four years is the fast case, not the average. It is however one of the few high-earning routes needing no expensive college.",
        "alternates": ["company-secretary", "cost-accountant", "investment-banker", "financial-analyst", "auditor"],
    },
    {
        "id": "company-secretary", "title": "Company Secretary (CS)", "cluster": "E", "family": "commerce",
        "degrees": ["CS", "B.Com", "B.Com Hons", "BBA", "BA LLB", "B.Com LLB"],
        "blurb": "Keeps a company legally sound - governance, board process and regulatory filings.",
        "whatYouDo": ["Ensure compliance with the Companies Act and SEBI rules",
                      "Run board and shareholder meetings properly",
                      "Advise directors on their legal duties",
                      "Handle filings, disclosures and corporate restructuring"],
        "dayInLife": "Board papers, statutory registers, and a filing deadline that is not negotiable.",
        "entranceExams": [
            {"name": "CSEET", "when": "After Class 12, four sittings a year", "opens": "ICSI Executive programme"},
            {"name": "CS Executive & Professional", "when": "After CSEET", "opens": "ICSI membership after practical training"},
        ],
        "salary": {"entry": "Rs 5-10 LPA", "mid": "Rs 10-25 LPA", "senior": "Rs 25-70 LPA+"},
        "alternates": ["chartered-accountant", "corporate-lawyer", "compliance-officer", "cost-accountant"],
    },
    {
        "id": "cost-accountant", "title": "Cost & Management Accountant (CMA)", "cluster": "E", "family": "commerce",
        "degrees": ["CMA", "B.Com", "B.Com Hons", "BBA Finance", "B.Sc Finance"],
        "blurb": "Works out what things actually cost, and how a business can make more per unit.",
        "whatYouDo": ["Build costing systems for products and services",
                      "Analyse margins and variances",
                      "Support pricing and make-or-buy decisions",
                      "Drive budgeting and cost control"],
        "dayInLife": "Cost models, a variance that needs explaining, and a manufacturing team who see costs differently.",
        "salary": {"entry": "Rs 5-10 LPA", "mid": "Rs 10-24 LPA", "senior": "Rs 24-60 LPA+"},
        "alternates": ["chartered-accountant", "financial-analyst", "business-analyst", "operations-manager"],
    },
    {
        "id": "auditor", "title": "Internal Auditor / Risk Analyst", "cluster": "E", "family": "commerce",
        "degrees": ["B.Com", "B.Com Hons", "CA", "CMA", "BBA Finance", "ACCA"],
        "blurb": "Checks whether a company's controls actually work before something goes wrong.",
        "whatYouDo": ["Test financial and operational controls",
                      "Identify fraud and process risk",
                      "Report findings to audit committees",
                      "Recommend and follow up on fixes"],
        "dayInLife": "Sampling, process walkthroughs, and difficult conversations about what you found.",
        "salary": {"entry": "Rs 5-11 LPA", "mid": "Rs 11-28 LPA", "senior": "Rs 28-70 LPA+"},
        "alternates": ["chartered-accountant", "compliance-officer", "financial-analyst", "forensic-accountant"],
    },
    {
        "id": "forensic-accountant", "title": "Forensic Accountant", "cluster": "E", "family": "commerce",
        "degrees": ["CA", "B.Com Hons", "B.Com", "CMA", "ACCA"],
        "blurb": "Investigates financial fraud and traces where money actually went.",
        "whatYouDo": ["Reconstruct transactions from incomplete records",
                      "Trace funds through entities and accounts",
                      "Quantify losses for litigation",
                      "Give expert evidence in court"],
        "dayInLife": "Deep document analysis, data forensics, and reports written to survive cross-examination.",
        "salary": {"entry": "Rs 6-12 LPA", "mid": "Rs 12-30 LPA", "senior": "Rs 30-80 LPA+"},
        "alternates": ["chartered-accountant", "auditor", "litigator", "cybersecurity-analyst"],
    },
    # ------------------------------------------------------------- FINANCE
    {
        "id": "investment-banker", "title": "Investment Banker", "cluster": "E", "family": "commerce",
        "degrees": ["B.Com Hons", "BBA Finance", "B.Sc Finance", "CFA pathway", "B.Sc Economics", "BBA", "CA"],
        "blurb": "Advises companies on raising capital, buying and selling businesses.",
        "whatYouDo": ["Build valuation and financial models",
                      "Prepare pitch books and information memoranda",
                      "Run due diligence on transactions",
                      "Negotiate and execute deals"],
        "dayInLife": "Modelling and pitch decks, frequently until well past midnight during a live deal.",
        "topColleges": ["SRCC Delhi", "St Xavier's Mumbai", "NMIMS Mumbai", "IIM Indore/Rohtak (IPM)", "Ashoka University"],
        "coreSkills": ["Financial modelling", "Valuation", "Accounting fluency", "Stamina", "Precision under time pressure"],
        "salary": {"entry": "Rs 12-30 LPA", "mid": "Rs 30-80 LPA", "senior": "Rs 80 LPA-5 Cr+"},
        "realityCheck": "Among the highest-paying entry routes in India and among the most demanding. 80-100 hour weeks in the analyst years are normal, not exceptional.",
        "alternates": ["financial-analyst", "quant-analyst", "management-consultant", "portfolio-manager"],
    },
    {
        "id": "financial-analyst", "title": "Financial Analyst", "cluster": "E", "family": "commerce",
        "degrees": ["B.Com Hons", "B.Sc Finance", "BBA Finance", "CFA pathway", "B.Sc Economics", "B.Com", "ACCA"],
        "blurb": "Analyses company and market performance to guide investment and business decisions.",
        "whatYouDo": ["Build forecasts and financial models",
                      "Analyse industries and competitors",
                      "Write research notes with a clear recommendation",
                      "Support budgeting and planning inside a company"],
        "dayInLife": "Model updates, earnings calls, and a view you have to defend when the market disagrees.",
        "salary": {"entry": "Rs 5-14 LPA", "mid": "Rs 14-35 LPA", "senior": "Rs 35 LPA-1 Cr+"},
        "alternates": ["investment-banker", "equity-research-analyst", "business-analyst", "actuary"],
    },
    {
        "id": "equity-research-analyst", "title": "Equity Research Analyst", "cluster": "E", "family": "commerce",
        "degrees": ["CFA pathway", "B.Com Hons", "B.Sc Finance", "BBA Finance", "B.Sc Economics"],
        "blurb": "Studies companies in depth and publishes a view on what their shares are worth.",
        "whatYouDo": ["Model a company's economics in detail",
                      "Meet management and test their claims",
                      "Publish buy/sell/hold recommendations",
                      "Be measured publicly on whether you were right"],
        "dayInLife": "Reading filings, updating models, and writing notes fund managers act on.",
        "salary": {"entry": "Rs 8-18 LPA", "mid": "Rs 18-45 LPA", "senior": "Rs 45 LPA-2 Cr+"},
        "alternates": ["financial-analyst", "investment-banker", "quant-analyst", "portfolio-manager"],
    },
    {
        "id": "quant-analyst", "title": "Quantitative Analyst", "cluster": "E", "family": "commerce",
        "degrees": ["B.Sc Mathematics", "B.Sc Statistics", "B.Tech Computer Science", "B.Sc Physics",
                    "B.Sc Data Science", "Actuarial Science", "B.Tech CSE"],
        "blurb": "Builds mathematical trading and risk models at funds and banks.",
        "whatYouDo": ["Develop and backtest trading strategies",
                      "Model derivatives pricing and risk",
                      "Write production-grade research code",
                      "Work with very large market datasets"],
        "dayInLife": "Mathematics and code, with results measured directly in profit and loss.",
        "topColleges": ["ISI Kolkata", "Chennai Mathematical Institute", "IIT Bombay / Delhi / Kanpur", "IISc Bengaluru"],
        "salary": {"entry": "Rs 15-45 LPA", "mid": "Rs 45 LPA-1.2 Cr", "senior": "Rs 1-5 Cr+"},
        "realityCheck": "The highest-paying route open to a strong mathematics student, and the most selective. Firms hire a handful of people a year, almost entirely from a few institutions.",
        "alternates": ["mathematician", "data-scientist", "actuary", "investment-banker"],
    },
    {
        "id": "actuary", "title": "Actuary", "cluster": "E", "family": "commerce",
        "degrees": ["Actuarial Science", "B.Sc Statistics", "B.Sc Mathematics", "B.Sc Finance", "B.Sc Economics"],
        "blurb": "Prices risk and uncertainty - insurance, pensions and long-term financial guarantees.",
        "whatYouDo": ["Model mortality, morbidity and claims",
                      "Price insurance products",
                      "Value long-term liabilities",
                      "Advise on solvency and reserving"],
        "dayInLife": "Statistical modelling, regulatory reporting, and studying for the next exam for several years.",
        "entranceExams": [
            {"name": "IAI ACET", "when": "After Class 12, twice a year", "opens": "Institute of Actuaries of India student membership"},
            {"name": "IFoA / IAI actuarial exams", "when": "Over 5-8 years", "opens": "Fellowship, and the senior roles that need it"},
        ],
        "salary": {"entry": "Rs 6-14 LPA", "mid": "Rs 14-40 LPA", "senior": "Rs 40 LPA-1.5 Cr+ (Fellow)"},
        "realityCheck": "Qualification takes 5-8 years of exams alongside full-time work, with low pass rates. Very few qualified actuaries in India, so those who finish are in strong demand.",
        "alternates": ["statistician", "quant-analyst", "financial-analyst", "data-scientist"],
    },
    {
        "id": "portfolio-manager", "title": "Portfolio / Fund Manager", "cluster": "E", "family": "commerce",
        "degrees": ["CFA pathway", "B.Com Hons", "B.Sc Finance", "BBA Finance", "B.Sc Economics"],
        "blurb": "Decides where a pool of other people's money is invested.",
        "whatYouDo": ["Set investment strategy and asset allocation",
                      "Select securities and size positions",
                      "Manage risk and drawdown",
                      "Answer to investors for performance"],
        "dayInLife": "Markets, research, and decisions whose consequences are public and measured daily.",
        "salary": {"entry": "Rs 10-25 LPA (analyst first)", "mid": "Rs 25-80 LPA", "senior": "Rs 80 LPA-5 Cr+"},
        "realityCheck": "Nobody starts here. It is 5-10 years of analyst work first, and the seat is given to a small number of people with a track record.",
        "alternates": ["equity-research-analyst", "investment-banker", "quant-analyst", "financial-analyst"],
    },
    {
        "id": "banker", "title": "Banking Professional", "cluster": "E", "family": "commerce",
        "degrees": ["B.Com", "B.Com Hons", "BBA", "BBA Finance", "BMS", "B.Sc Economics", "B.Sc Finance"],
        "blurb": "Works in retail, corporate or investment banking - lending, deposits, treasury and relationships.",
        "whatYouDo": ["Assess creditworthiness and structure loans",
                      "Manage client relationships and portfolios",
                      "Handle treasury and regulatory requirements",
                      "Drive product and branch performance"],
        "dayInLife": "Client meetings, credit files, and targets that reset every quarter.",
        "entranceExams": [
            {"name": "IBPS PO / SBI PO", "when": "After graduation", "opens": "Public sector bank officer roles"},
            {"name": "RBI Grade B", "when": "After graduation", "opens": "The central bank - among the most sought-after finance jobs in India"},
        ],
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-30 LPA", "senior": "Rs 30-80 LPA+"},
        "alternates": ["financial-analyst", "chartered-accountant", "civil-servant", "business-analyst"],
    },
    {
        "id": "compliance-officer", "title": "Compliance & Risk Officer", "cluster": "E", "family": "commerce",
        "degrees": ["B.Com", "B.Com Hons", "CS", "BA LLB", "B.Com LLB", "CA", "ACCA"],
        "blurb": "Keeps a regulated business on the right side of its rules.",
        "whatYouDo": ["Interpret regulation and translate it into policy",
                      "Monitor transactions and flag breaches",
                      "Handle regulator queries and inspections",
                      "Train staff on obligations"],
        "dayInLife": "Policy review, monitoring reports, and saying no to commercially attractive ideas.",
        "salary": {"entry": "Rs 5-11 LPA", "mid": "Rs 11-30 LPA", "senior": "Rs 30-80 LPA+"},
        "alternates": ["auditor", "company-secretary", "corporate-lawyer", "chartered-accountant"],
    },
    # ---------------------------------------------------------- MANAGEMENT
    {
        "id": "management-consultant", "title": "Management Consultant", "cluster": "E", "family": "commerce",
        "degrees": ["BBA", "BMS", "B.Com Hons", "B.Sc Economics", "BBA Business Analytics", "B.Tech Computer Science", "B.Com"],
        "blurb": "Is brought in to solve a company's hardest problems, then leaves.",
        "whatYouDo": ["Structure an ambiguous problem into answerable parts",
                      "Analyse data and interview people across a client",
                      "Build a recommendation and the case for it",
                      "Present to executives who will push back"],
        "dayInLife": "Analysis, interviews and slides, often on a client site away from home four days a week.",
        "topColleges": ["IIM Indore/Rohtak (IPM)", "SRCC Delhi", "NMIMS Mumbai", "St Xavier's Mumbai", "Ashoka University"],
        "coreSkills": ["Structured problem solving", "Excel and PowerPoint at a high level", "Executive communication",
                       "Learning an industry in two weeks", "Working under constant deadline"],
        "salary": {"entry": "Rs 10-25 LPA", "mid": "Rs 25-70 LPA", "senior": "Rs 70 LPA-4 Cr+ (partner)"},
        "realityCheck": "Excellent training and exit options, with travel and hours that are hard to sustain past a few years for most people.",
        "alternates": ["business-analyst", "investment-banker", "product-manager", "entrepreneur"],
    },
    {
        "id": "product-manager", "title": "Product Manager", "cluster": "E", "family": "commerce",
        "degrees": ["B.Tech Computer Science", "B.Tech CSE", "BBA", "BMS", "B.Sc Economics", "BBA Business Analytics", "B.Des"],
        "blurb": "Decides what a product should do and why, and gets it built.",
        "whatYouDo": ["Work out what users actually need, not what they ask for",
                      "Prioritise ruthlessly against limited engineering time",
                      "Write specifications and align design and engineering",
                      "Measure whether what shipped worked"],
        "dayInLife": "User conversations, a prioritisation argument, and a launch metric that did not move as expected.",
        "salary": {"entry": "Rs 8-25 LPA", "mid": "Rs 25-60 LPA", "senior": "Rs 60 LPA-2.5 Cr+"},
        "realityCheck": "Rarely an entry-level job; most product managers arrive from engineering, design, consulting or analytics after a few years.",
        "alternates": ["business-analyst", "management-consultant", "ux-designer", "software-engineer"],
    },
    {
        "id": "business-analyst", "title": "Business Analyst", "cluster": "E", "family": "commerce",
        "degrees": ["BBA Business Analytics", "BBA", "B.Com", "B.Sc Economics", "B.Sc Statistics", "BMS", "B.Com Hons"],
        "blurb": "Sits between business questions and data, and turns one into the other.",
        "whatYouDo": ["Define the metrics a team should be judged on",
                      "Build dashboards and analyse performance",
                      "Document requirements for technical teams",
                      "Recommend process and system changes"],
        "dayInLife": "SQL, a dashboard nobody reads until it moves, and a requirements workshop.",
        "salary": {"entry": "Rs 5-14 LPA", "mid": "Rs 14-35 LPA", "senior": "Rs 35-90 LPA+"},
        "alternates": ["data-scientist", "product-manager", "management-consultant", "financial-analyst"],
    },
    {
        "id": "marketing-manager", "title": "Marketing Manager", "cluster": "E", "family": "commerce",
        "degrees": ["BBA", "BMS", "BBM", "B.Com", "Advertising & Brand Communication", "Mass Communication", "B.Com Hons"],
        "blurb": "Decides how a product is positioned, priced and promoted, and owns the result.",
        "whatYouDo": ["Research the market and define positioning",
                      "Plan campaigns across channels and budgets",
                      "Work with creative and media teams",
                      "Measure acquisition cost against lifetime value"],
        "dayInLife": "Campaign performance in the morning, a creative review, and a budget conversation.",
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-35 LPA", "senior": "Rs 35 LPA-1.5 Cr+ (CMO)"},
        "alternates": ["digital-marketer", "brand-manager", "product-manager", "advertising-professional"],
    },
    {
        "id": "digital-marketer", "title": "Digital Marketing Specialist", "cluster": "E", "family": "commerce",
        "degrees": ["BBA", "Digital Media", "Mass Communication", "B.Com", "Advertising", "BMS", "Content Creation"],
        "blurb": "Acquires and retains customers through search, social, content and paid media.",
        "whatYouDo": ["Run and optimise paid campaigns",
                      "Improve organic search and content performance",
                      "Analyse funnels and conversion",
                      "Test relentlessly and kill what does not work"],
        "dayInLife": "Dashboards, ad platforms, creative briefs, and an experiment log.",
        "buildNow": ["Run a real account - a page, a channel, a small shop - and grow it. Results beat certificates",
                     "Learn Google Analytics and Meta Ads Manager; both are free to study",
                     "Write. Every digital marketing role is partly a writing role"],
        "salary": {"entry": "Rs 3-9 LPA", "mid": "Rs 9-25 LPA", "senior": "Rs 25-70 LPA+"},
        "alternates": ["marketing-manager", "content-creator", "brand-manager", "business-analyst"],
    },
    {
        "id": "brand-manager", "title": "Brand Manager", "cluster": "E", "family": "commerce",
        "degrees": ["BBA", "BMS", "Advertising & Brand Communication", "Mass Communication", "B.Com", "BBM"],
        "blurb": "Owns what a brand means and how it grows, effectively running it as a business.",
        "whatYouDo": ["Set brand strategy and positioning",
                      "Manage the product portfolio and pricing",
                      "Brief and judge creative work",
                      "Own the profit and loss for the brand"],
        "dayInLife": "Consumer research, a creative review, and a margin conversation with sales.",
        "salary": {"entry": "Rs 6-15 LPA", "mid": "Rs 15-40 LPA", "senior": "Rs 40 LPA-1.5 Cr+"},
        "alternates": ["marketing-manager", "product-manager", "advertising-professional", "management-consultant"],
    },
    {
        "id": "hr-manager", "title": "Human Resources Manager", "cluster": "F", "family": "commerce",
        "degrees": ["BBA", "BMS", "BA Psychology", "B.Sc Psychology", "BA Sociology", "B.Com", "BBM"],
        "blurb": "Builds and looks after the people side of an organisation.",
        "whatYouDo": ["Hire, and design how hiring is done",
                      "Handle performance, pay and progression",
                      "Resolve conflict and manage exits",
                      "Shape culture and retention"],
        "dayInLife": "Interviews, a difficult employee conversation, and policy work.",
        "topColleges": ["XLRI Jamshedpur (HR)", "TISS Mumbai", "Symbiosis (SCMHRD)", "Christ University"],
        "salary": {"entry": "Rs 4-10 LPA", "mid": "Rs 10-28 LPA", "senior": "Rs 28-90 LPA+ (CHRO)"},
        "alternates": ["psychologist", "management-consultant", "operations-manager", "social-worker"],
    },
    {
        "id": "operations-manager", "title": "Operations / Supply Chain Manager", "cluster": "E", "family": "commerce",
        "degrees": ["BBA", "BMS", "B.Com", "B.Tech Mechanical", "BBA Business Analytics", "B.Sc Agribusiness", "BBM"],
        "blurb": "Makes sure things actually get made, moved and delivered, at cost and on time.",
        "whatYouDo": ["Plan production, inventory and logistics",
                      "Manage suppliers and negotiate contracts",
                      "Cut cost and cycle time without breaking service",
                      "Handle the disruption that arrives every week"],
        "dayInLife": "Daily numbers, a supplier escalation, and a process fix that saves a small amount many times over.",
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-32 LPA", "senior": "Rs 32-90 LPA+ (COO)"},
        "alternates": ["systems-engineer", "business-analyst", "agribusiness-manager", "management-consultant"],
    },
    {
        "id": "entrepreneur", "title": "Entrepreneur / Founder", "cluster": "E", "family": "commerce",
        "degrees": ["BBA", "BMS", "B.Com", "B.Tech Computer Science", "B.Des", "B.Sc Agribusiness", "BBM", "B.Com Hons"],
        "blurb": "Builds a business from nothing, and carries the risk of it.",
        "whatYouDo": ["Find a problem people will pay to have solved",
                      "Build the first version and sell it yourself",
                      "Hire, raise money, and manage cash",
                      "Do whatever is most broken that week"],
        "dayInLife": "There is no typical day, which is exactly the appeal and exactly the difficulty.",
        "buildNow": ["Start something small now and sell to real strangers - the lesson is in the selling",
                     "Learn basic accounting; founders who cannot read their own numbers get into trouble",
                     "Build one hard skill (code, design, sales) so you can make the first version yourself"],
        "salary": {"entry": "Often nothing for 1-3 years", "mid": "Highly variable", "senior": "Rs 0 to unbounded"},
        "realityCheck": "Most new businesses do not succeed, and the honest expected value is lower than a good salaried career. It is worth it if the work itself is what you want.",
        "alternates": ["product-manager", "management-consultant", "marketing-manager", "agribusiness-manager"],
    },
    {
        "id": "economist", "title": "Economist", "cluster": "E", "family": "commerce",
        "degrees": ["B.Sc Economics", "BA Economics", "B.Com Hons", "B.Sc Statistics", "B.Sc Mathematics"],
        "blurb": "Analyses how economies and markets behave, for government, banks or research bodies.",
        "whatYouDo": ["Model economic behaviour and forecast indicators",
                      "Evaluate the impact of policy",
                      "Publish research and briefings",
                      "Advise on strategy under macro uncertainty"],
        "dayInLife": "Data and econometrics, a policy note, and a forecast you will be held to.",
        "topColleges": ["Delhi School of Economics", "ISI Kolkata", "Madras School of Economics", "Ashoka University", "JNU", "IGIDR Mumbai"],
        "salary": {"entry": "Rs 5-14 LPA", "mid": "Rs 14-35 LPA", "senior": "Rs 35 LPA-1 Cr+"},
        "alternates": ["policy-analyst", "financial-analyst", "statistician", "data-scientist"],
    },
    # ----------------------------------------------------------------- LAW
    {
        "id": "corporate-lawyer", "title": "Corporate Lawyer", "cluster": "F", "family": "law",
        "degrees": ["BA LLB", "BBA LLB", "B.Com LLB", "B.Sc LLB", "LLB after graduation"],
        "blurb": "Advises companies on transactions, contracts and regulation.",
        "whatYouDo": ["Draft and negotiate contracts",
                      "Run legal due diligence on deals",
                      "Advise on regulatory and competition issues",
                      "Structure transactions to manage risk"],
        "dayInLife": "Drafting, mark-ups, and deal calls that run late. Very document-heavy.",
        "salary": {"entry": "Rs 12-20 LPA (tier-1 firm)", "mid": "Rs 20-60 LPA", "senior": "Rs 60 LPA-3 Cr+ (partner)"},
        "alternates": ["litigator", "company-secretary", "compliance-officer", "judge"],
    },
    {
        "id": "litigator", "title": "Litigator / Advocate", "cluster": "F", "family": "law",
        "degrees": ["BA LLB", "BBA LLB", "B.Com LLB", "B.Sc LLB", "LLB after graduation"],
        "blurb": "Argues cases in court on behalf of clients.",
        "whatYouDo": ["Research law and build the argument",
                      "Draft pleadings and written submissions",
                      "Appear and argue before courts",
                      "Advise clients on their real chances"],
        "dayInLife": "Court in the morning, chamber work in the afternoon, and reading late.",
        "salary": {"entry": "Rs 1.5-6 LPA (junior in chambers)", "mid": "Rs 6-30 LPA", "senior": "Rs 30 LPA-10 Cr+ (senior counsel)"},
        "realityCheck": "The first few years genuinely pay very little while you learn in a senior's chambers. The ceiling for those who establish themselves is higher than almost any other profession.",
        "alternates": ["corporate-lawyer", "judge", "civil-servant", "journalist"],
    },
    {
        "id": "judge", "title": "Judge / Judicial Officer", "cluster": "F", "family": "law",
        "degrees": ["BA LLB", "BBA LLB", "B.Com LLB", "B.Sc LLB", "LLB after graduation"],
        "blurb": "Decides cases, entering through the state judicial services examination.",
        "whatYouDo": ["Hear matters and assess evidence",
                      "Apply law impartially and write reasoned judgments",
                      "Manage a very heavy case list",
                      "Progress from district judiciary upward"],
        "dayInLife": "Court hours, then judgment writing, with a docket that never empties.",
        "entranceExams": [
            {"name": "State Judicial Services (Civil Judge)", "when": "After LLB, varies by state", "opens": "Entry to the district judiciary"},
        ],
        "salary": {"entry": "Rs 8-14 LPA (plus housing and allowances)", "mid": "Rs 14-25 LPA", "senior": "Rs 25-40 LPA (High Court and above higher)"},
        "alternates": ["litigator", "civil-servant", "corporate-lawyer"],
    },
    {
        "id": "legal-advisor", "title": "In-house Legal Counsel", "cluster": "F", "family": "law",
        "degrees": ["BA LLB", "BBA LLB", "B.Com LLB", "B.Sc LLB", "CS", "LLB after graduation"],
        "blurb": "The lawyer inside a company rather than in a firm.",
        "whatYouDo": ["Advise business teams on day-to-day legal risk",
                      "Draft and review the company's contracts",
                      "Manage external counsel and disputes",
                      "Build compliance into how the business operates"],
        "dayInLife": "Contract review, a commercial team wanting a fast answer, and risk judgement calls.",
        "salary": {"entry": "Rs 6-14 LPA", "mid": "Rs 14-40 LPA", "senior": "Rs 40 LPA-2 Cr+ (General Counsel)"},
        "alternates": ["corporate-lawyer", "compliance-officer", "company-secretary"],
    },
    # ------------------------------------------------------- PUBLIC SERVICE
    {
        "id": "civil-servant", "title": "Civil Servant (IAS / IPS / IFS)", "cluster": "F", "family": "civil_services",
        "degrees": ["BA Political Science", "BA History", "BA Economics", "BA Public Policy", "BA Sociology",
                    "B.Com", "B.Tech Computer Science", "MBBS", "BA LLB", "B.Sc Physics", "BA English", "BA Geography"],
        "blurb": "Administers government - districts, policy, policing or diplomacy.",
        "whatYouDo": ["Implement government programmes at scale",
                      "Take decisions affecting very large numbers of people",
                      "Coordinate departments, budgets and crises",
                      "Advise ministers on policy"],
        "dayInLife": "Field inspections, public grievances, files, and an emergency that displaces the plan.",
        "salary": {"entry": "Rs 7-12 LPA (plus housing, transport and allowances)", "mid": "Rs 12-25 LPA", "senior": "Rs 25-40 LPA"},
        "realityCheck": "Enormous responsibility and influence at a young age, on a pay scale far below the private sector. Selection is under 0.2% of applicants, so a genuine plan B is essential.",
        "alternates": ["policy-analyst", "judge", "forest-officer", "defence-officer", "economist"],
    },
    {
        "id": "policy-analyst", "title": "Public Policy Analyst", "cluster": "F", "family": "civil_services",
        "degrees": ["BA Public Policy", "BA Political Science", "BA Economics", "B.Sc Economics", "BA Sociology",
                    "BA International Relations", "B.Sc Statistics"],
        "blurb": "Researches and designs policy for think-tanks, government and international bodies.",
        "whatYouDo": ["Evaluate what a policy actually achieved",
                      "Model the effect of proposed changes",
                      "Write briefs decision-makers will read",
                      "Engage stakeholders and the public"],
        "dayInLife": "Data work, fieldwork, and writing that has to be short enough to be read by a minister.",
        "topColleges": ["TISS Mumbai", "Ashoka University (Kautilya)", "NLSIU Bengaluru", "JNU", "IIM Bangalore (Public Policy)"],
        "salary": {"entry": "Rs 4-12 LPA", "mid": "Rs 12-30 LPA", "senior": "Rs 30-80 LPA+ (multilateral bodies higher)"},
        "alternates": ["civil-servant", "economist", "social-worker", "urban-planner"],
    },
    {
        "id": "defence-officer", "title": "Defence Services Officer", "cluster": "F", "family": "civil_services",
        "degrees": ["B.Sc Physics", "B.Sc Mathematics", "B.Tech Mechanical", "B.Tech Computer Science",
                    "BA History", "B.Tech Aerospace", "B.Com", "B.Sc Chemistry"],
        "blurb": "Commissioned officer in the Army, Navy or Air Force.",
        "whatYouDo": ["Lead and train personnel",
                      "Plan and execute operations",
                      "Maintain readiness of equipment and units",
                      "Take responsibility for people's lives"],
        "dayInLife": "Training, unit administration and postings that move you across the country every few years.",
        "entranceExams": [
            {"name": "NDA", "when": "Class 12, twice a year - the direct route from school", "opens": "National Defence Academy"},
            {"name": "CDS", "when": "After graduation", "opens": "IMA, INA, AFA and OTA"},
            {"name": "AFCAT / TES / SSB", "when": "Class 12 or graduation", "opens": "Air Force and technical entries"},
        ],
        "salary": {"entry": "Rs 8-13 LPA (plus housing, medical and allowances)", "mid": "Rs 13-25 LPA", "senior": "Rs 25-45 LPA"},
        "realityCheck": "NDA is one of the few routes that starts straight after class 12. It asks for physical fitness and a willingness to be posted anywhere, and the commitment is long.",
        "alternates": ["civil-servant", "aerospace-engineer", "aerospace-engineer", "sports-coach"],
    },
    {
        "id": "social-worker", "title": "Social Worker / Development Professional", "cluster": "F", "family": "humanities",
        "degrees": ["BA Sociology", "BA Psychology", "B.Sc Psychology", "BA Anthropology", "BA Public Policy", "BA Political Science"],
        "blurb": "Works directly on social problems - with communities, NGOs or government programmes.",
        "whatYouDo": ["Work with vulnerable individuals and communities",
                      "Design and run development programmes",
                      "Advocate for rights and access to services",
                      "Measure whether interventions actually helped"],
        "dayInLife": "Field visits, casework, and reporting to funders.",
        "topColleges": ["TISS Mumbai", "Delhi School of Social Work", "Christ University", "Azim Premji University"],
        "salary": {"entry": "Rs 3-7 LPA", "mid": "Rs 7-18 LPA", "senior": "Rs 18-45 LPA+ (large foundations higher)"},
        "realityCheck": "Emotionally demanding and modestly paid, with real and visible impact. Burnout is common; the people who last build boundaries early.",
        "alternates": ["psychologist", "policy-analyst", "public-health-specialist", "teacher"],
    },
]
