/**
 * Class 8 Assessment Questions - 60 questions
 * Source: class8sheet.xlsx (VERIFIED AND ACCURATE)
 * Generated with 100% accuracy from source data
 */

export interface AssessmentQuestion {
  id: number;
  question: string;
  dimension: string;
  dimensionCode: string;
  options: { label: string; text: string; mapping: string }[];
  hint?: string;
}

export const DIMENSION_ORDER = [
  'Personality Preferences',
  'Career Interests RIASEC',
  'Aptitude & Reasoning',
  'Multiple Intelligence Strengths',
  'Motivators & Values',
  'Learning Preferences',
  'Emotional & Social Awareness',
  'Creativity & Future Readiness',
];

export const DIMENSION_LABELS = {
  Personality: 'Personality Preferences',
  RIASEC: 'Career Interests',
  Aptitude: 'Aptitude & Reasoning',
  StrengthDomains: 'Strength Domains',
  Motivators: 'Motivators & Values',
  LearningStyle: 'Learning Style',
  EmotionalAwareness: 'Emotional Awareness',
  Creativity: 'Creativity & Future Readiness',
};

export const DIMENSION_DESCRIPTIONS = {
  Personality: 'Understand your work style and preferences',
  RIASEC: 'Discover career interests aligned with your passions',
  Aptitude: 'Assess your reasoning and problem-solving abilities',
  StrengthDomains: 'Identify your natural intelligences and strengths',
  Motivators: 'Learn what drives and motivates you',
  LearningStyle: 'Find out how you learn best',
  EmotionalAwareness: 'Explore your emotional and social skills',
  Creativity: 'Assess your creative thinking and adaptability',
};

export const QUESTIONS_PER_DIMENSION = {
  Personality: { start: 1, end: 10, count: 10 },
  RIASEC: { start: 11, end: 20, count: 10 },
  Aptitude: { start: 21, end: 30, count: 10 },
  StrengthDomains: { start: 31, end: 38, count: 8 },
  Motivators: { start: 39, end: 45, count: 7 },
  LearningStyle: { start: 46, end: 50, count: 5 },
  EmotionalAwareness: { start: 51, end: 55, count: 5 },
  Creativity: { start: 56, end: 60, count: 5 },
};

export const CLASS8_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 1,
    question: 'In a group project, you usually:',
    dimension: 'Personality Preferences',
    dimensionCode: 'PP',
    options: [
      { label: 'A', text: 'Take charge and assign tasks', mapping: 'PP-D' },
      { label: 'B', text: 'Support others and keep harmony', mapping: 'PP-S' },
      { label: 'C', text: 'Focus on your own part and finish it perfectly', mapping: 'PP-A' },
      { label: 'D', text: 'Explore new ideas and suggest changes', mapping: 'PP-C' },
    ],
  },
  {
    id: 2,
    question: 'When plans change suddenly, you tend to:',
    dimension: 'Personality Preferences',
    dimensionCode: 'PP',
    options: [
      { label: 'A', text: 'Quickly make a new plan', mapping: 'PP-D' },
      { label: 'B', text: 'Check how others feel and adapt', mapping: 'PP-S' },
      { label: 'C', text: 'Stick to what still makes logical sense', mapping: 'PP-A' },
      { label: 'D', text: 'See it as a chance to try something different', mapping: 'PP-C' },
    ],
  },
  {
    id: 3,
    question: 'At a party, you are most likely to:',
    dimension: 'Personality Preferences',
    dimensionCode: 'PP',
    options: [
      { label: 'A', text: 'Meet many new people', mapping: 'PP-D' },
      { label: 'B', text: 'Stay with a few close friends', mapping: 'PP-S' },
      { label: 'C', text: 'Observe and join when comfortable', mapping: 'PP-A' },
      { label: 'D', text: 'Start an interesting conversation or activity', mapping: 'PP-C' },
    ],
  },
  {
    id: 4,
    question: 'When solving a problem, you prefer to:',
    dimension: 'Personality Preferences',
    dimensionCode: 'PP',
    options: [
      { label: 'A', text: 'Decide fast and act', mapping: 'PP-D' },
      { label: 'B', text: 'Talk it through with others', mapping: 'PP-S' },
      { label: 'C', text: 'Analyze all details before choosing', mapping: 'PP-A' },
      { label: 'D', text: 'Imagine multiple creative solutions', mapping: 'PP-C' },
    ],
  },
  {
    id: 5,
    question: 'Your ideal weekend looks like:',
    dimension: 'Personality Preferences',
    dimensionCode: 'PP',
    options: [
      { label: 'A', text: 'A busy schedule with many activities', mapping: 'PP-D' },
      { label: 'B', text: 'Time with family or close friends', mapping: 'PP-S' },
      { label: 'C', text: 'A quiet day to read or think', mapping: 'PP-A' },
      { label: 'D', text: 'Trying something new or artistic', mapping: 'PP-C' },
    ],
  },
  {
    id: 6,
    question: 'When receiving feedback, you:',
    dimension: 'Personality Preferences',
    dimensionCode: 'PP',
    options: [
      { label: 'A', text: 'Want direct, clear points to improve', mapping: 'PP-D' },
      { label: 'B', text: 'Care most about tone and relationship', mapping: 'PP-S' },
      { label: 'C', text: 'Focus on accuracy and logic of comments', mapping: 'PP-A' },
      { label: 'D', text: 'Look for ideas to grow in unique ways', mapping: 'PP-C' },
    ],
  },
  {
    id: 7,
    question: 'In conflicts, you usually:',
    dimension: 'Personality Preferences',
    dimensionCode: 'PP',
    options: [
      { label: 'A', text: 'Confront the issue directly', mapping: 'PP-D' },
      { label: 'B', text: 'Try to calm everyone and find middle ground', mapping: 'PP-S' },
      { label: 'C', text: 'Step back and think before responding', mapping: 'PP-A' },
      { label: 'D', text: 'Reframe the situation in a new way', mapping: 'PP-C' },
    ],
  },
  {
    id: 8,
    question: 'You feel most energized when:',
    dimension: 'Personality Preferences',
    dimensionCode: 'PP',
    options: [
      { label: 'A', text: 'Leading or organizing something', mapping: 'PP-D' },
      { label: 'B', text: 'Helping or connecting with people', mapping: 'PP-S' },
      { label: 'C', text: 'Working deeply on a challenging task', mapping: 'PP-A' },
      { label: 'D', text: 'Exploring new concepts or possibilities', mapping: 'PP-C' },
    ],
  },
  {
    id: 9,
    question: 'When making big decisions, you rely most on:',
    dimension: 'Personality Preferences',
    dimensionCode: 'PP',
    options: [
      { label: 'A', text: 'Your goals and drive', mapping: 'PP-D' },
      { label: 'B', text: 'Your values and impact on others', mapping: 'PP-S' },
      { label: 'C', text: 'Facts, data, and pros/cons', mapping: 'PP-A' },
      { label: 'D', text: 'Your intuition and vision', mapping: 'PP-C' },
    ],
  },
  {
    id: 10,
    question: 'People would describe you as more:',
    dimension: 'Personality Preferences',
    dimensionCode: 'PP',
    options: [
      { label: 'A', text: 'Decisive and action-oriented', mapping: 'PP-D' },
      { label: 'B', text: 'Warm and supportive', mapping: 'PP-S' },
      { label: 'C', text: 'Logical and careful', mapping: 'PP-A' },
      { label: 'D', text: 'Imaginative and open-minded', mapping: 'PP-C' },
    ],
  },
  {
    id: 11,
    question: 'Which task would you enjoy most?',
    dimension: 'Career Interests - RIASEC',
    dimensionCode: 'RI',
    options: [
      { label: 'A', text: 'Building or repairing a device', mapping: 'R' },
      { label: 'B', text: 'Designing an experiment to test an idea', mapping: 'I' },
      { label: 'C', text: 'Creating a poster, story, or artwork', mapping: 'A' },
      { label: 'D', text: 'Teaching or mentoring someone', mapping: 'S' },
      { label: 'E', text: 'Leading a team to reach a target', mapping: 'E' },
    ],
  },
  {
    id: 12,
    question: 'In a future job, you would prefer to spend time:',
    dimension: 'Career Interests - RIASEC',
    dimensionCode: 'RI',
    options: [
      { label: 'A', text: 'Working with tools, machines, or outdoors', mapping: 'R' },
      { label: 'B', text: 'Analyzing data, codes, or research papers', mapping: 'I' },
      { label: 'C', text: 'Designing visuals, content, or experiences', mapping: 'A' },
      { label: 'D', text: 'Counseling, coaching, or supporting people', mapping: 'S' },
      { label: 'E', text: 'Planning projects, sales, or strategies', mapping: 'E' },
    ],
  },
  {
    id: 13,
    question: 'Which school subject feels most natural?',
    dimension: 'Career Interests - RIASEC',
    dimensionCode: 'RI',
    options: [
      { label: 'A', text: 'Physics lab / workshop / vocational skills', mapping: 'R' },
      { label: 'B', text: 'Mathematics / computer science / research', mapping: 'I' },
      { label: 'C', text: 'Art / music / creative writing / design', mapping: 'A' },
      { label: 'D', text: 'Psychology / social work / education', mapping: 'S' },
      { label: 'E', text: 'Business / entrepreneurship / leadership roles', mapping: 'E' },
    ],
  },
  {
    id: 14,
    question: 'You feel most proud when you:',
    dimension: 'Career Interests - RIASEC',
    dimensionCode: 'RI',
    options: [
      { label: 'A', text: 'Fix something that was broken', mapping: 'R' },
      { label: 'B', text: 'Solve a complex puzzle or problem', mapping: 'I' },
      { label: 'C', text: 'Make something original and expressive', mapping: 'A' },
      { label: 'D', text: 'Help someone improve their life', mapping: 'S' },
      { label: 'E', text: 'Achieve a measurable result or win', mapping: 'E' },
    ],
  },
  {
    id: 15,
    question: 'Your ideal work environment is:',
    dimension: 'Career Interests - RIASEC',
    dimensionCode: 'RI',
    options: [
      { label: 'A', text: 'Hands-on, practical, possibly outdoors', mapping: 'R' },
      { label: 'B', text: 'Quiet, analytical, research-focused', mapping: 'I' },
      { label: 'C', text: 'Flexible, creative, visually stimulating', mapping: 'A' },
      { label: 'D', text: 'People-centered, collaborative, caring', mapping: 'S' },
      { label: 'E', text: 'Dynamic, competitive, goal-driven', mapping: 'E' },
    ],
  },
  {
    id: 16,
    question: 'Which project sounds most exciting?',
    dimension: 'Career Interests - RIASEC',
    dimensionCode: 'RI',
    options: [
      { label: 'A', text: 'Constructing a model bridge or robot', mapping: 'R' },
      { label: 'B', text: 'Writing a research report or code', mapping: 'I' },
      { label: 'C', text: 'Designing a campaign or short film', mapping: 'A' },
      { label: 'D', text: 'Organizing a community support program', mapping: 'S' },
      { label: 'E', text: 'Launching a small business or event', mapping: 'E' },
    ],
  },
  {
    id: 17,
    question: 'You like tasks that involve:',
    dimension: 'Career Interests - RIASEC',
    dimensionCode: 'RI',
    options: [
      { label: 'A', text: 'Physical activity and tangible results', mapping: 'R' },
      { label: 'B', text: 'Deep thinking and abstract concepts', mapping: 'I' },
      { label: 'C', text: 'Imagination and self-expression', mapping: 'A' },
      { label: 'D', text: 'Communication and emotional support', mapping: 'S' },
      { label: 'E', text: 'Influence, negotiation, and leadership', mapping: 'E' },
    ],
  },
  {
    id: 18,
    question: 'When choosing electives, you lean toward:',
    dimension: 'Career Interests - RIASEC',
    dimensionCode: 'RI',
    options: [
      { label: 'A', text: 'Engineering, IT hardware, or trades', mapping: 'R' },
      { label: 'B', text: 'Science, math, or data analysis', mapping: 'I' },
      { label: 'C', text: 'Arts, media, or design', mapping: 'A' },
      { label: 'D', text: 'Humanities, counseling, or teaching', mapping: 'S' },
      { label: 'E', text: 'Management, marketing, or finance', mapping: 'E' },
    ],
  },
  {
    id: 19,
    question: 'You would rather be known as someone who:',
    dimension: 'Career Interests - RIASEC',
    dimensionCode: 'RI',
    options: [
      { label: 'A', text: 'Gets things built and working', mapping: 'R' },
      { label: 'B', text: 'Discovers new knowledge or solutions', mapping: 'I' },
      { label: 'C', text: 'Creates beautiful or meaningful work', mapping: 'A' },
      { label: 'D', text: 'Makes a positive difference in lives', mapping: 'S' },
      { label: 'E', text: 'Leads and achieves big outcomes', mapping: 'E' },
    ],
  },
  {
    id: 20,
    question: 'Long-term, you see yourself in a role that is mainly:',
    dimension: 'Career Interests - RIASEC',
    dimensionCode: 'RI',
    options: [
      { label: 'A', text: 'Technical / hands-on specialist', mapping: 'R' },
      { label: 'B', text: 'Researcher / analyst / scientist', mapping: 'I' },
      { label: 'C', text: 'Artist / designer / content creator', mapping: 'A' },
      { label: 'D', text: 'Educator / counselor / helper', mapping: 'S' },
      { label: 'E', text: 'Manager / entrepreneur / leader', mapping: 'E' },
    ],
  },
  {
    id: 21,
    question: 'If 3, 6, 12, 24, ... what comes next?',
    dimension: 'Aptitude & Reasoning',
    dimensionCode: 'AR',
    options: [
      { label: 'A', text: '30', mapping: 'AR-Numeric_pattern-Incorrect' },
      { label: 'B', text: '36', mapping: 'AR-Numeric_pattern-Incorrect' },
      { label: 'C', text: '48', mapping: 'AR-Numeric_pattern-Correct' },
      { label: 'D', text: '50', mapping: 'AR-Numeric_pattern-Incorrect' },
    ],
  },
  {
    id: 22,
    question: 'All roses are flowers. Some flowers fade quickly. Therefore:',
    dimension: 'Aptitude & Reasoning',
    dimensionCode: 'AR',
    options: [
      { label: 'A', text: 'All roses fade quickly', mapping: 'AR-Verbal_logic-Incorrect' },
      { label: 'B', text: 'Some roses may fade quickly', mapping: 'AR-Verbal_logic-Correct' },
      { label: 'C', text: 'No roses fade quickly', mapping: 'AR-Verbal_logic-Incorrect' },
      { label: 'D', text: 'Roses never fade', mapping: 'AR-Verbal_logic-Incorrect' },
    ],
  },
  {
    id: 23,
    question: 'A train travels 60 km in 1 hour. How far in 2.5 hours at the same speed?',
    dimension: 'Aptitude & Reasoning',
    dimensionCode: 'AR',
    options: [
      { label: 'A', text: '120 km', mapping: 'AR-Numeric_reasoning-Incorrect' },
      { label: 'B', text: '130 km', mapping: 'AR-Numeric_reasoning-Incorrect' },
      { label: 'C', text: '150 km', mapping: 'AR-Numeric_reasoning-Correct' },
      { label: 'D', text: '180 km', mapping: 'AR-Numeric_reasoning-Incorrect' },
    ],
  },
  {
    id: 24,
    question: 'Which word does NOT belong? Apple, Carrot, Banana, Mango',
    dimension: 'Aptitude & Reasoning',
    dimensionCode: 'AR',
    options: [
      { label: 'A', text: 'Apple', mapping: 'AR-Verbal_classification-Incorrect' },
      { label: 'B', text: 'Carrot', mapping: 'AR-Verbal_classification-Correct' },
      { label: 'C', text: 'Banana', mapping: 'AR-Verbal_classification-Incorrect' },
      { label: 'D', text: 'Mango', mapping: 'AR-Verbal_classification-Incorrect' },
    ],
  },
  {
    id: 25,
    question: 'Coding: If BOOK -> CPPL, how is PEN coded?',
    dimension: 'Aptitude & Reasoning',
    dimensionCode: 'AR',
    options: [
      { label: 'A', text: 'QFO', mapping: 'AR-Coding/Pattern-Correct' },
      { label: 'B', text: 'QFM', mapping: 'AR-Coding/Pattern-Incorrect' },
      { label: 'C', text: 'ODM', mapping: 'AR-Coding/Pattern-Incorrect' },
      { label: 'D', text: 'QEN', mapping: 'AR-Coding/Pattern-Incorrect' },
    ],
  },
  {
    id: 26,
    question: 'Look at the pattern: 2, 3, 5, 8, 12, ... what is next?',
    dimension: 'Aptitude & Reasoning',
    dimensionCode: 'AR',
    options: [
      { label: 'A', text: '15', mapping: 'AR-Numeric_sequence-Incorrect' },
      { label: 'B', text: '16', mapping: 'AR-Numeric_sequence-Incorrect' },
      { label: 'C', text: '17', mapping: 'AR-Numeric_sequence-Correct' },
      { label: 'D', text: '18', mapping: 'AR-Numeric_sequence-Incorrect' },
    ],
  },
  {
    id: 27,
    question: 'A box has 4 red and 6 blue balls. One ball drawn. Probability of red?',
    dimension: 'Aptitude & Reasoning',
    dimensionCode: 'AR',
    options: [
      { label: 'A', text: '0.2', mapping: 'AR-Probability-Incorrect' },
      { label: 'B', text: '0.4', mapping: 'AR-Probability-Correct' },
      { label: 'C', text: '0.5', mapping: 'AR-Probability-Incorrect' },
      { label: 'D', text: '0.6', mapping: 'AR-Probability-Incorrect' },
    ],
  },
  {
    id: 28,
    question: 'If all A are B, and some B are C, then:',
    dimension: 'Aptitude & Reasoning',
    dimensionCode: 'AR',
    options: [
      { label: 'A', text: 'All A are C', mapping: 'AR-Logical_deduction-Incorrect' },
      { label: 'B', text: 'Some A may be C', mapping: 'AR-Logical_deduction-Correct' },
      { label: 'C', text: 'No A are C', mapping: 'AR-Logical_deduction-Incorrect' },
      { label: 'D', text: 'All C are A', mapping: 'AR-Logical_deduction-Incorrect' },
    ],
  },
  {
    id: 29,
    question: 'Series: triangle, square, pentagon, ... what comes next?',
    dimension: 'Aptitude & Reasoning',
    dimensionCode: 'AR',
    options: [
      { label: 'A', text: 'Hexagon', mapping: 'AR-Visual_pattern-Correct' },
      { label: 'B', text: 'Circle', mapping: 'AR-Visual_pattern-Incorrect' },
      { label: 'C', text: 'Rectangle', mapping: 'AR-Visual_pattern-Incorrect' },
      { label: 'D', text: 'Star', mapping: 'AR-Visual_pattern-Incorrect' },
    ],
  },
  {
    id: 30,
    question: '3 shirts and 2 pants. How many outfits (1 shirt + 1 pant)?',
    dimension: 'Aptitude & Reasoning',
    dimensionCode: 'AR',
    options: [
      { label: 'A', text: '5', mapping: 'AR-Combinatorics-Incorrect' },
      { label: 'B', text: '6', mapping: 'AR-Combinatorics-Correct' },
      { label: 'C', text: '7', mapping: 'AR-Combinatorics-Incorrect' },
      { label: 'D', text: '8', mapping: 'AR-Combinatorics-Incorrect' },
    ],
  },
  {
    id: 31,
    question: 'You feel strongest when you:',
    dimension: 'MI-Inspired Strength Domains',
    dimensionCode: 'MI',
    options: [
      { label: 'A', text: 'Write, speak, or tell stories clearly', mapping: 'Linguistic' },
      { label: 'B', text: 'Solve puzzles, calculations, or logical problems', mapping: 'Logical-Math' },
      { label: 'C', text: 'Visualize maps, diagrams, or designs', mapping: 'Spatial' },
      { label: 'D', text: 'Use your body in sports, dance, or crafts', mapping: 'Bodily-Kinesthetic' },
      { label: 'E', text: 'Understand rhythms, melodies, or sounds', mapping: 'Musical' },
    ],
  },
  {
    id: 32,
    question: 'In group work, your main strength is:',
    dimension: 'MI-Inspired Strength Domains',
    dimensionCode: 'MI',
    options: [
      { label: 'A', text: 'Explaining ideas in words', mapping: 'Linguistic' },
      { label: 'B', text: 'Structuring the plan logically', mapping: 'Logical-Math' },
      { label: 'C', text: 'Creating visuals or layouts', mapping: 'Spatial' },
      { label: 'D', text: 'Demonstrating or building prototypes', mapping: 'Bodily-Kinesthetic' },
      { label: 'E', text: 'Sensing group mood and guiding harmony', mapping: 'Interpersonal' },
    ],
  },
  {
    id: 33,
    question: 'You learn best by:',
    dimension: 'MI-Inspired Strength Domains',
    dimensionCode: 'MI',
    options: [
      { label: 'A', text: 'Reading and discussing', mapping: 'Linguistic' },
      { label: 'B', text: 'Practicing problems step by step', mapping: 'Logical-Math' },
      { label: 'C', text: 'Drawing or using images', mapping: 'Spatial' },
      { label: 'D', text: 'Doing hands-on activities', mapping: 'Bodily-Kinesthetic' },
      { label: 'E', text: 'Using music, rhythm, or patterns', mapping: 'Musical' },
    ],
  },
  {
    id: 34,
    question: 'People often come to you for help with:',
    dimension: 'MI-Inspired Strength Domains',
    dimensionCode: 'MI',
    options: [
      { label: 'A', text: 'Writing or speaking tasks', mapping: 'Linguistic' },
      { label: 'B', text: 'Math, logic, or tech issues', mapping: 'Logical-Math' },
      { label: 'C', text: 'Designing or visualizing things', mapping: 'Spatial' },
      { label: 'D', text: 'Physical tasks or demonstrations', mapping: 'Bodily-Kinesthetic' },
      { label: 'E', text: 'Understanding feelings or relationships', mapping: 'Interpersonal' },
    ],
  },
  {
    id: 35,
    question: 'Your favorite type of project is one that uses:',
    dimension: 'MI-Inspired Strength Domains',
    dimensionCode: 'MI',
    options: [
      { label: 'A', text: 'Words, debates, or narratives', mapping: 'Linguistic' },
      { label: 'B', text: 'Data, experiments, or models', mapping: 'Logical-Math' },
      { label: 'C', text: 'Colors, shapes, or spaces', mapping: 'Spatial' },
      { label: 'D', text: 'Movement, tools, or materials', mapping: 'Bodily-Kinesthetic' },
      { label: 'E', text: 'Sounds, beats, or musical elements', mapping: 'Musical' },
    ],
  },
  {
    id: 36,
    question: 'You notice details most in:',
    dimension: 'MI-Inspired Strength Domains',
    dimensionCode: 'MI',
    options: [
      { label: 'A', text: 'Language, tone, and meaning', mapping: 'Linguistic' },
      { label: 'B', text: 'Numbers, patterns, and structures', mapping: 'Logical-Math' },
      { label: 'C', text: 'Images, layouts, and visuals', mapping: 'Spatial' },
      { label: 'D', text: 'Motion, posture, and physical cues', mapping: 'Bodily-Kinesthetic' },
      { label: 'E', text: 'Rhythm, pitch, and sound patterns', mapping: 'Musical' },
    ],
  },
  {
    id: 37,
    question: 'When relaxed, you enjoy:',
    dimension: 'MI-Inspired Strength Domains',
    dimensionCode: 'MI',
    options: [
      { label: 'A', text: 'Reading, writing, or podcasts', mapping: 'Linguistic' },
      { label: 'B', text: 'Strategy games or brain teasers', mapping: 'Logical-Math' },
      { label: 'C', text: 'Drawing, photography, or design', mapping: 'Spatial' },
      { label: 'D', text: 'Sports, dance, or making things', mapping: 'Bodily-Kinesthetic' },
      { label: 'E', text: 'Listening to or creating music', mapping: 'Musical' },
    ],
  },
  {
    id: 38,
    question: 'You feel most \'in flow\' when:',
    dimension: 'MI-Inspired Strength Domains',
    dimensionCode: 'MI',
    options: [
      { label: 'A', text: 'Crafting a powerful message', mapping: 'Linguistic' },
      { label: 'B', text: 'Solving a tough logical challenge', mapping: 'Logical-Math' },
      { label: 'C', text: 'Creating something visually striking', mapping: 'Spatial' },
      { label: 'D', text: 'Moving your body skillfully', mapping: 'Bodily-Kinesthetic' },
      { label: 'E', text: 'Working with sounds or musical ideas', mapping: 'Musical' },
    ],
  },
  {
    id: 39,
    question: 'What matters most in your work?',
    dimension: 'Motivators & Values',
    dimensionCode: 'MV',
    options: [
      { label: 'A', text: 'Achievement and recognition', mapping: 'Achievement' },
      { label: 'B', text: 'Helping others and making impact', mapping: 'Service' },
      { label: 'C', text: 'Freedom and creativity', mapping: 'Autonomy' },
      { label: 'D', text: 'Stability and security', mapping: 'Security' },
      { label: 'E', text: 'Learning and growth', mapping: 'Growth' },
    ],
  },
  {
    id: 40,
    question: 'You feel most motivated when:',
    dimension: 'Motivators & Values',
    dimensionCode: 'MV',
    options: [
      { label: 'A', text: 'You reach clear targets and win', mapping: 'Achievement' },
      { label: 'B', text: 'You see positive change in people', mapping: 'Service' },
      { label: 'C', text: 'You express your unique ideas', mapping: 'Autonomy' },
      { label: 'D', text: 'You have a steady, predictable routine', mapping: 'Security' },
      { label: 'E', text: 'You master new skills and knowledge', mapping: 'Growth' },
    ],
  },
  {
    id: 41,
    question: 'Which value guides you most?',
    dimension: 'Motivators & Values',
    dimensionCode: 'MV',
    options: [
      { label: 'A', text: 'Success', mapping: 'Achievement' },
      { label: 'B', text: 'Compassion', mapping: 'Service' },
      { label: 'C', text: 'Authenticity', mapping: 'Autonomy' },
      { label: 'D', text: 'Safety', mapping: 'Security' },
      { label: 'E', text: 'Curiosity', mapping: 'Growth' },
    ],
  },
  {
    id: 42,
    question: 'In your career, you prioritize:',
    dimension: 'Motivators & Values',
    dimensionCode: 'MV',
    options: [
      { label: 'A', text: 'Status and influence', mapping: 'Achievement' },
      { label: 'B', text: 'Service and contribution', mapping: 'Service' },
      { label: 'C', text: 'Originality and self-expression', mapping: 'Autonomy' },
      { label: 'D', text: 'Job security and benefits', mapping: 'Security' },
      { label: 'E', text: 'Continuous development', mapping: 'Growth' },
    ],
  },
  {
    id: 43,
    question: 'You would accept a lower salary if the job offered:',
    dimension: 'Motivators & Values',
    dimensionCode: 'MV',
    options: [
      { label: 'A', text: 'Faster promotion and visibility', mapping: 'Achievement' },
      { label: 'B', text: 'Meaningful social impact', mapping: 'Service' },
      { label: 'C', text: 'Creative freedom', mapping: 'Autonomy' },
      { label: 'D', text: 'Very stable, low-stress conditions', mapping: 'Security' },
      { label: 'E', text: 'Strong learning opportunities', mapping: 'Growth' },
    ],
  },
  {
    id: 44,
    question: 'When setting goals, you focus on:',
    dimension: 'Motivators & Values',
    dimensionCode: 'MV',
    options: [
      { label: 'A', text: 'Beating benchmarks and others', mapping: 'Achievement' },
      { label: 'B', text: 'Improving lives around you', mapping: 'Service' },
      { label: 'C', text: 'Being true to your vision', mapping: 'Autonomy' },
      { label: 'D', text: 'Reducing risk and uncertainty', mapping: 'Security' },
      { label: 'E', text: 'Expanding your capabilities', mapping: 'Growth' },
    ],
  },
  {
    id: 45,
    question: 'Long-term, you want to be remembered for:',
    dimension: 'Motivators & Values',
    dimensionCode: 'MV',
    options: [
      { label: 'A', text: 'Your achievements and leadership', mapping: 'Achievement' },
      { label: 'B', text: 'Your kindness and service', mapping: 'Service' },
      { label: 'C', text: 'Your creativity and originality', mapping: 'Autonomy' },
      { label: 'D', text: 'Your reliability and steadiness', mapping: 'Security' },
      { label: 'E', text: 'Your wisdom and learning', mapping: 'Growth' },
    ],
  },
  {
    id: 46,
    question: 'You understand new topics best when:',
    dimension: 'Learning Preferences',
    dimensionCode: 'LP',
    options: [
      { label: 'A', text: 'You hear explanations and discussions', mapping: 'Auditory-Social' },
      { label: 'B', text: 'You read texts and notes', mapping: 'Read-Write' },
      { label: 'C', text: 'You see diagrams, charts, or videos', mapping: 'Visual' },
      { label: 'D', text: 'You practice by doing tasks', mapping: 'Kinesthetic' },
    ],
  },
  {
    id: 47,
    question: 'For exams, you prefer to prepare by:',
    dimension: 'Learning Preferences',
    dimensionCode: 'LP',
    options: [
      { label: 'A', text: 'Group study and talking through concepts', mapping: 'Auditory-Social' },
      { label: 'B', text: 'Making detailed written notes', mapping: 'Read-Write' },
      { label: 'C', text: 'Using mind maps and visuals', mapping: 'Visual' },
      { label: 'D', text: 'Solving many practice questions', mapping: 'Kinesthetic' },
    ],
  },
  {
    id: 48,
    question: 'In class, you learn most when the teacher:',
    dimension: 'Learning Preferences',
    dimensionCode: 'LP',
    options: [
      { label: 'A', text: 'Explains clearly and invites questions', mapping: 'Auditory-Social' },
      { label: 'B', text: 'Provides good handouts and readings', mapping: 'Read-Write' },
      { label: 'C', text: 'Uses slides, images, and examples', mapping: 'Visual' },
      { label: 'D', text: 'Gives hands-on activities and labs', mapping: 'Kinesthetic' },
    ],
  },
  {
    id: 49,
    question: 'When stuck on a problem, you first:',
    dimension: 'Learning Preferences',
    dimensionCode: 'LP',
    options: [
      { label: 'A', text: 'Ask someone to explain it', mapping: 'Auditory-Social' },
      { label: 'B', text: 'Look up written solutions or theory', mapping: 'Read-Write' },
      { label: 'C', text: 'Draw or visualize the situation', mapping: 'Visual' },
      { label: 'D', text: 'Try different approaches practically', mapping: 'Kinesthetic' },
    ],
  },
  {
    id: 50,
    question: 'Your ideal study session includes:',
    dimension: 'Learning Preferences',
    dimensionCode: 'LP',
    options: [
      { label: 'A', text: 'Discussion with peers or a tutor', mapping: 'Auditory-Social' },
      { label: 'B', text: 'Quiet reading and summarizing', mapping: 'Read-Write' },
      { label: 'C', text: 'Visual aids and color-coded notes', mapping: 'Visual' },
      { label: 'D', text: 'Active problem-solving and experiments', mapping: 'Kinesthetic' },
    ],
  },
  {
    id: 51,
    question: 'When a friend is upset, you usually:',
    dimension: 'Emotional & Social Awareness',
    dimensionCode: 'ES',
    options: [
      { label: 'A', text: 'Listen carefully and validate feelings', mapping: 'Empathic' },
      { label: 'B', text: 'Offer practical solutions', mapping: 'Problem-Focused' },
      { label: 'C', text: 'Give them space until they are ready', mapping: 'Self-Regulated' },
      { label: 'D', text: 'Share a similar experience to relate', mapping: 'Expressive' },
    ],
  },
  {
    id: 52,
    question: 'In a tense group situation, you tend to:',
    dimension: 'Emotional & Social Awareness',
    dimensionCode: 'ES',
    options: [
      { label: 'A', text: 'Notice everyone emotions quickly', mapping: 'Empathic' },
      { label: 'B', text: 'Focus on fixing the main issue', mapping: 'Problem-Focused' },
      { label: 'C', text: 'Stay calm and observe', mapping: 'Self-Regulated' },
      { label: 'D', text: 'Use humor to lighten the mood', mapping: 'Expressive' },
    ],
  },
  {
    id: 53,
    question: 'You understand your own emotions best by:',
    dimension: 'Emotional & Social Awareness',
    dimensionCode: 'ES',
    options: [
      { label: 'A', text: 'Talking about them with someone', mapping: 'Empathic' },
      { label: 'B', text: 'Writing or reflecting privately', mapping: 'Self-Regulated' },
      { label: 'C', text: 'Noticing body sensations and reactions', mapping: 'Self-Regulated' },
      { label: 'D', text: 'Expressing them through art or activity', mapping: 'Expressive' },
    ],
  },
  {
    id: 54,
    question: 'When someone criticizes you, you first feel:',
    dimension: 'Emotional & Social Awareness',
    dimensionCode: 'ES',
    options: [
      { label: 'A', text: 'Hurt but try to understand their view', mapping: 'Empathic' },
      { label: 'B', text: 'Defensive and want to explain', mapping: 'Defensive' },
      { label: 'C', text: 'Curious about what is true in it', mapping: 'Growth-Oriented' },
      { label: 'D', text: 'Detached and analytical', mapping: 'Analytical' },
    ],
  },
  {
    id: 55,
    question: 'In relationships, you value most:',
    dimension: 'Emotional & Social Awareness',
    dimensionCode: 'ES',
    options: [
      { label: 'A', text: 'Emotional honesty and depth', mapping: 'Empathic' },
      { label: 'B', text: 'Loyalty and reliability', mapping: 'Secure' },
      { label: 'C', text: 'Respect for boundaries', mapping: 'Boundary-Aware' },
      { label: 'D', text: 'Fun and shared experiences', mapping: 'Expressive' },
    ],
  },
  {
    id: 56,
    question: 'When facing a new challenge, you:',
    dimension: 'Creativity & Future Readiness',
    dimensionCode: 'CF',
    options: [
      { label: 'A', text: 'Generate many possible ideas quickly', mapping: 'Divergent' },
      { label: 'B', text: 'Research what others have done', mapping: 'Analytical' },
      { label: 'C', text: 'Adapt existing solutions creatively', mapping: 'Integrative' },
      { label: 'D', text: 'Wait for clarity before acting', mapping: 'Cautious' },
    ],
  },
  {
    id: 57,
    question: 'You feel most creative when:',
    dimension: 'Creativity & Future Readiness',
    dimensionCode: 'CF',
    options: [
      { label: 'A', text: 'There are no strict rules', mapping: 'Divergent' },
      { label: 'B', text: 'You have some constraints to work within', mapping: 'Structured-Creative' },
      { label: 'C', text: 'You can combine different fields', mapping: 'Integrative' },
      { label: 'D', text: 'You have time to experiment', mapping: 'Experimental' },
    ],
  },
  {
    id: 58,
    question: 'About future trends (AI, tech, etc.), you:',
    dimension: 'Creativity & Future Readiness',
    dimensionCode: 'CF',
    options: [
      { label: 'A', text: 'Excitedly explore and experiment', mapping: 'Early-Adopter' },
      { label: 'B', text: 'Carefully study pros and cons', mapping: 'Analytical' },
      { label: 'C', text: 'Think how to use them in your domain', mapping: 'Applied' },
      { label: 'D', text: 'Prefer to adopt once they are stable', mapping: 'Late-Adopter' },
    ],
  },
  {
    id: 59,
    question: 'When planning your future, you:',
    dimension: 'Creativity & Future Readiness',
    dimensionCode: 'CF',
    options: [
      { label: 'A', text: 'Imagine several possible paths', mapping: 'Divergent' },
      { label: 'B', text: 'Make a detailed step-by-step plan', mapping: 'Planner' },
      { label: 'C', text: 'Keep options open and adapt', mapping: 'Adaptive' },
      { label: 'D', text: 'Follow a proven, traditional route', mapping: 'Traditional' },
    ],
  },
  {
    id: 60,
    question: 'You see change as:',
    dimension: 'Creativity & Future Readiness',
    dimensionCode: 'CF',
    options: [
      { label: 'A', text: 'An opportunity to innovate', mapping: 'Innovative' },
      { label: 'B', text: 'A problem to analyze', mapping: 'Analytical' },
      { label: 'C', text: 'A chance to grow flexibly', mapping: 'Adaptive' },
      { label: 'D', text: 'Something to manage cautiously', mapping: 'Cautious' },
    ],
  },
];
